// Generated by tools/bundle.py from problems/polynomial/factorization_of_polynomials/solution.cpp. Edit that file instead.
// Factorization of a monic f of degree N <= 100 over F_p, p prime <= 998244353, into monic
// irreducibles with multiplicities: square-free decomposition, roots of the linear part, then
// Berlekamp (factor.hpp for odd p, gf2.hpp for p = 2). Design and log: notes.md.
#include <cstdint>
#include <vector>

// lib/io/io.hpp
// Fast integer and text I/O on file descriptors (stdin and stdout by default).
// Linux, x86-64 with AVX2. Design and measurements: lib/io/notes.md.
//
//   io::Reader in;                            // takes all of stdin
//   io::Writer out;                           // flushes in its destructor
//   const auto n = in.read<std::uint32_t>();
//   std::vector<std::uint32_t> a(n);
//   in.read(a.data(), n);                     // bulk; AVX2 for uint32_t
//   const auto s = in.read<std::uint64_t, 16>();  // promise: at most 16 digits (faster)
//   out.write("n = ", n, '\n');               // any mix of integers, chars, strings
//   out.write<16>(s, '\n');                   // promise: integers of at most 16 digits
//   out.write_array(a.data(), n, ' ');        // bulk; AVX2 for uint32_t
//   out.write('\n');
//
// Input: tokens separated by whitespace (any bytes <= ' '). Integer tokens are an optional '-'
// (signed types only) followed by decimal digits, and fit the requested type. Reading past the
// last token is undefined. The 64 bytes before the input and after its end are readable zeros, so
// custom parsers may load up to 64 bytes around any token from word().

#include <fcntl.h>
#include <immintrin.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <unistd.h>

#include <algorithm>
#include <array>
#include <bit>
#include <cerrno>
#include <concepts>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <string_view>
#include <type_traits>

namespace io {
namespace detail {

// Zero bytes before and after the input. Loads reach at most 63 bytes past either end.
inline constexpr std::size_t kPadding = 64;
inline constexpr std::size_t kPage = 4096;

// Input as mapped or read: data [start, end), kPadding zero bytes before and after it.
struct Input {
    char* base;           // allocation or mapping to release
    std::size_t mapped;   // bytes mapped, or 0 for a heap buffer
    const char* start;
    const char* end;
};

inline Input map_input(int fd, std::size_t size) {
    const off_t offset = ::lseek(fd, 0, SEEK_CUR);
    if (offset < 0 || std::size_t(offset) >= size) return {};
    // One anonymous zero page before the file. After it, the rest of the last file page reads as
    // zero; if fewer than kPadding bytes remain, one more anonymous page follows.
    const std::size_t file_bytes = (size + kPage - 1) & ~(kPage - 1);
    const std::size_t mapped = kPage + file_bytes + (file_bytes - size < kPadding ? kPage : 0);
    void* base = ::mmap(nullptr, mapped, PROT_READ, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
    if (base == MAP_FAILED) return {};
    char* const file = static_cast<char*>(base) + kPage;
    if (::mmap(file, file_bytes, PROT_READ, MAP_PRIVATE | MAP_FIXED, fd, 0) == MAP_FAILED) {
        ::munmap(base, mapped);
        return {};
    }
    return {static_cast<char*>(base), mapped, file + offset, file + size};
}

// Capacity bytes for data, with kPadding bytes before and after; returns the data start.
inline char* allocate(std::size_t capacity) {
    auto* p = static_cast<char*>(std::aligned_alloc(64, capacity + 2 * kPadding));
    if (!p) std::abort();
    std::memset(p, 0, kPadding);
    return p + kPadding;
}

// Reads fd until end of file, or until size bytes for a regular file of that size.
inline Input read_input(int fd, std::size_t size = std::size_t(-1)) {
    std::size_t done = 0, capacity = std::size_t(1) << 16;
    char* data = allocate(capacity);
    while (done < size) {
        if (done == capacity) {
            char* bigger = allocate(capacity *= 2);
            std::memcpy(bigger, data, done);
            std::free(data - kPadding);
            data = bigger;
        }
        const ssize_t got = ::read(fd, data + done, capacity - done);
        if (got > 0) done += std::size_t(got);
        else if (got == 0) break;
        else if (errno != EINTR) std::abort();
    }
    std::memset(data + done, 0, kPadding);
    return {data - kPadding, 0, data, data + done};
}

// Files over kMapAbove bytes are mapped; smaller ones and other inputs are read, which takes
// fewer system calls.
inline constexpr std::size_t kMapAbove = std::size_t(1) << 16;

inline Input open_input(int fd) {
    struct stat st;
    if (::fstat(fd, &st) == 0 && S_ISREG(st.st_mode)) {
        const auto size = std::size_t(st.st_size);
        if (size <= kMapAbove) return read_input(fd, size);
        if (const Input input = map_input(fd, size); input.base) return input;
    }
    return read_input(fd);
}

inline void release(const Input& input) {
    if (input.mapped) ::munmap(input.base, input.mapped);
    else std::free(input.base);
}

// Bit i set iff byte i is whitespace (<= ' ').
inline unsigned separators(__m128i bytes) {
    return unsigned(_mm_movemask_epi8(_mm_cmpgt_epi8(_mm_set1_epi8(' ' + 1), bytes)));
}

inline std::uint32_t separators(__m256i bytes) {
    return std::uint32_t(_mm256_movemask_epi8(_mm256_cmpgt_epi8(_mm256_set1_epi8(' ' + 1), bytes)));
}

// Separators in the 64-byte aligned block.
inline std::uint64_t block_separators(const char* block) {
    const std::uint64_t low = separators(_mm256_load_si256(reinterpret_cast<const __m256i*>(block)));
    const std::uint64_t high = separators(_mm256_load_si256(reinterpret_cast<const __m256i*>(block + 32)));
    return low | high << 32;
}

// The 16 bytes at kRightAlign[n + 1] move the first n bytes (1 <= n <= 16) of a 16-byte window
// to its end and zero the rest: byte k + 1 is k - 16 for 16 <= k < 32, else -128. For the other
// lengths (-1, 0, 17..32) byte 15 of the window is negative, which marks the token as invalid.
alignas(64) inline constexpr auto kRightAlign = [] {
    std::array<std::int8_t, 64> t{};
    for (int k = -1; k < 63; ++k) t[k + 1] = k >= 16 && k < 32 ? std::int8_t(k - 16) : std::int8_t(-128);
    return t;
}();

// Shuffle control for a token of length index - 1.
inline __m128i align_row(std::size_t index) {
    return _mm_loadu_si128(reinterpret_cast<const __m128i*>(kRightAlign.data() + index));
}

// Right-aligned digits (byte values 0..9) -> 4-digit groups, one per dword.
inline __m128i digit_groups(__m128i digits) {
    return _mm_madd_epi16(_mm_maddubs_epi16(digits, _mm_set1_epi16(0x010A)), _mm_set1_epi32(0x00010064));
}

inline __m256i digit_groups(__m256i digits) {
    return _mm256_madd_epi16(_mm256_maddubs_epi16(digits, _mm256_set1_epi16(0x010A)), _mm256_set1_epi32(0x00010064));
}

// Value of the first n digits (0 <= n <= 16) of the window. Result < 10^16.
inline std::uint64_t parse16(__m128i window, unsigned n) {
    const __m128i digits = _mm_shuffle_epi8(_mm_subs_epu8(window, _mm_set1_epi8('0')), align_row(n + 1));
    const __m128i groups = digit_groups(digits);
    const __m128i halves = _mm_madd_epi16(_mm_packus_epi32(groups, groups), _mm_set1_epi32(0x00012710));
    const auto both = std::uint64_t(_mm_cvtsi128_si64(halves));  // 8-digit halves, high one first
    return (both & 0xFFFFFFFF) * 100000000 + (both >> 32);
}

// kKeep[32 - k..64 - k) keeps the last k bytes of 32.
alignas(64) inline constexpr auto kKeep = [] {
    std::array<std::uint8_t, 64> t{};
    for (std::size_t i = 32; i < 64; ++i) t[i] = 0xFF;
    return t;
}();

// Value of the n <= 16 digits that end at end. Bytes below '0' before them (a sign) count as 0.
inline std::uint64_t parse_ending16(const char* end, unsigned n) {
    const __m128i bytes = _mm_loadu_si128(reinterpret_cast<const __m128i*>(end - 16));
    const __m128i keep = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kKeep.data() + 16 + n));
    const __m128i groups = digit_groups(_mm_and_si128(_mm_subs_epu8(bytes, _mm_set1_epi8('0')), keep));
    const __m128i halves = _mm_madd_epi16(_mm_packus_epi32(groups, groups), _mm_set1_epi32(0x00012710));
    const auto both = std::uint64_t(_mm_cvtsi128_si64(halves));  // 8-digit halves, high one first
    return (both & 0xFFFFFFFF) * 100000000 + (both >> 32);
}

// Value of the n <= 24 digits that end at end; at most 20 for a result below 2^64.
inline std::uint64_t parse_ending24(const char* end, unsigned n) {
    const __m256i bytes = _mm256_loadu_si256(reinterpret_cast<const __m256i*>(end - 32));
    const __m256i keep = _mm256_loadu_si256(reinterpret_cast<const __m256i*>(kKeep.data() + n));
    const __m256i groups = digit_groups(_mm256_and_si256(_mm256_subs_epu8(bytes, _mm256_set1_epi8('0')), keep));
    // 8-digit quarters; the first is 0. Dword 1 of the low lane, dwords 0 and 1 of the high lane.
    const __m256i quarters = _mm256_madd_epi16(_mm256_packus_epi32(groups, groups), _mm256_set1_epi32(0x00012710));
    const std::uint64_t high = std::uint64_t(_mm256_extract_epi64(quarters, 0)) >> 32;
    const auto low = std::uint64_t(_mm256_extract_epi64(quarters, 2));
    return (high * 100000000 + (low & 0xFFFFFFFF)) * 100000000 + (low >> 32);
}

// kQuad[x] for x < 10^4: its 4 digits with leading zeros, first digit in the lowest byte.
alignas(64) inline constexpr auto kQuad = [] {
    std::array<std::uint32_t, 10000> t{};
    for (std::uint32_t x = 0; x < t.size(); ++x)
        t[x] = ('0' + x / 1000) | ('0' + x / 100 % 10) << 8 | ('0' + x / 10 % 10) << 16 | ('0' + x % 10) << 24;
    return t;
}();

// Digits of x (x >= 1) = (x + kDigitCount32[floor(log2(x))]) >> 32: the low word of an entry
// carries into the high word exactly when x reaches the next power of ten.
inline constexpr auto kDigitCount32 = [] {
    std::array<std::uint64_t, 32> t{};
    for (int i = 0; i < 32; ++i) {
        const std::uint64_t low = std::uint64_t(1) << i, high = 2 * low - 1;
        std::uint64_t digits = 0, power = 1;
        while (power <= low) power *= 10, ++digits;
        t[i] = (digits << 32) + (power <= high ? (std::uint64_t(1) << 32) - power : 0);
    }
    return t;
}();

inline unsigned digit_count(std::uint32_t x) {
    return unsigned((x + kDigitCount32[31 - std::countl_zero(x | 1)]) >> 32);
}

// Digits of x = kDigitCount64[0][b] + (x > kDigitCount64[1][b]), where b = bit width of x | 1.
inline constexpr auto kDigitCount64 = [] {
    std::array<std::array<std::uint64_t, 65>, 2> t{};
    for (int b = 1; b <= 64; ++b) {
        const unsigned __int128 low = (unsigned __int128)1 << (b - 1), high = 2 * low - 1;
        std::uint64_t digits = 1;
        unsigned __int128 power = 10;
        while (power <= low) power *= 10, ++digits;
        t[0][b] = digits;
        t[1][b] = power <= high ? std::uint64_t(power - 1) : ~std::uint64_t(0);
    }
    return t;
}();

inline unsigned digit_count(std::uint64_t x) {
    const int b = std::bit_width(x | 1);
    return unsigned(kDigitCount64[0][b] + (x > kDigitCount64[1][b]));
}

// Bytes kShiftWindow[k..k + 16) shuffle a vector down by k bytes.
alignas(32) inline constexpr std::int8_t kShiftWindow[32] = {0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  10,
                                                             11, 12, 13, 14, 15, -1, -1, -1, -1, -1, -1,
                                                             -1, -1, -1, -1, -1, -1, -1, -1, -1, -1};

inline __m128i shift_down(__m128i v, unsigned k) {
    return _mm_shuffle_epi8(v, _mm_loadu_si128(reinterpret_cast<const __m128i*>(kShiftWindow + k)));
}

// Writes x in decimal at p and returns the end. Stores 16 bytes.
inline char* format(char* p, std::uint32_t x) {
    // Twelve digits with leading zeros, as three groups of four, then shifted down past the zeros.
    const std::uint32_t top = x / 100000000, rest = x % 100000000;
    const std::uint32_t high = rest / 10000, low = rest % 10000;
    const __m128i digits = _mm_insert_epi32(
        _mm_cvtsi64_si128(std::int64_t(kQuad[top] | std::uint64_t(kQuad[high]) << 32)), int(kQuad[low]), 2);
    const unsigned n = digit_count(x);
    _mm_storeu_si128(reinterpret_cast<__m128i*>(p), shift_down(digits, 12 - n));
    return p + n;
}

// high, low < 10^8 as 16 digits with leading zeros.
inline __m128i sixteen_digits(std::uint32_t high, std::uint32_t low) {
    return _mm_set_epi64x(std::int64_t(kQuad[low / 10000] | std::uint64_t(kQuad[low % 10000]) << 32),
                          std::int64_t(kQuad[high / 10000] | std::uint64_t(kQuad[high % 10000]) << 32));
}

// Writes x in decimal at p and returns the end. Stores up to 20 bytes. MaxDigits <= 16 promises
// x < 10^16, which saves a division.
template <int MaxDigits>
inline char* format64(char* p, std::uint64_t x) {
    const std::uint64_t q = x / 100000000;  // < 1.9 * 10^11
    const auto low = std::uint32_t(x - q * 100000000);
    const unsigned n = digit_count(x);
    if constexpr (MaxDigits <= 16) {
        _mm_storeu_si128(reinterpret_cast<__m128i*>(p), shift_down(sixteen_digits(std::uint32_t(q), low), 16 - n));
        return p + n;
    } else {
        // Twenty digits with leading zeros: a head of four, then sixteen.
        const auto top = std::uint32_t(q / 100000000);  // < 1845
        const auto middle = std::uint32_t(q - std::uint64_t(top) * 100000000);
        const unsigned head = n > 16 ? n - 16 : 0;
        const auto head_digits = std::uint32_t(std::uint64_t(kQuad[top]) >> (32 - 8 * head));
        std::memcpy(p, &head_digits, 4);
        _mm_storeu_si128(reinterpret_cast<__m128i*>(p + head), shift_down(sixteen_digits(middle, low), 16 - (n - head)));
        return p + n;
    }
}

// floor(x / d) for every dword x, as (x * Magic) >> Shift. The test checks each use exhaustively.
template <std::uint32_t Magic, int Shift>
inline __m256i divide(__m256i x) {
    const __m256i magic = _mm256_set1_epi64x(Magic);
    const __m256i even = _mm256_srli_epi64(_mm256_mul_epu32(x, magic), Shift);
    const __m256i odd = _mm256_srli_epi64(_mm256_mul_epu32(_mm256_srli_epi64(x, 32), magic), Shift);
    return _mm256_blend_epi32(even, _mm256_slli_epi64(odd, 32), 0xAA);
}

// Each dword g < 10^4 -> its 4 ASCII digits, first digit in the lowest byte.
inline __m256i quad_digits(__m256i g) {
    const __m256i high = _mm256_srli_epi16(_mm256_mulhi_epu16(g, _mm256_set1_epi16(5243)), 3);  // g / 100
    const __m256i low = _mm256_sub_epi16(g, _mm256_mullo_epi16(high, _mm256_set1_epi16(100)));
    const __m256i pairs = _mm256_or_si256(high, _mm256_slli_epi32(low, 16));  // 16-bit halves < 100
    const __m256i tens = _mm256_mulhi_epu16(pairs, _mm256_set1_epi16(6554));  // pair / 10
    const __m256i units = _mm256_sub_epi16(pairs, _mm256_mullo_epi16(tens, _mm256_set1_epi16(10)));
    return _mm256_or_si256(_mm256_or_si256(tens, _mm256_slli_epi16(units, 8)), _mm256_set1_epi8('0'));
}

// Digit counts of the eight dwords of v, one per byte in order.
inline std::uint64_t digit_counts(__m256i v) {
    // Unsigned v >= 10^k via a signed compare after flipping the sign bits; summed as a tree.
    const __m256i x = _mm256_xor_si256(v, _mm256_set1_epi32(int(0x80000000)));
    const auto at_least = [&](std::uint32_t power) {
        return _mm256_cmpgt_epi32(x, _mm256_set1_epi32(int((power - 1) ^ 0x80000000)));
    };
    const __m256i a = _mm256_add_epi32(_mm256_add_epi32(at_least(10), at_least(100)),
                                       _mm256_add_epi32(at_least(1000), at_least(10000)));
    const __m256i b = _mm256_add_epi32(_mm256_add_epi32(at_least(100000), at_least(1000000)),
                                       _mm256_add_epi32(at_least(10000000), at_least(100000000)));
    const __m256i n = _mm256_sub_epi32(_mm256_sub_epi32(_mm256_set1_epi32(1), at_least(1000000000)),
                                       _mm256_add_epi32(a, b));
    const __m256i bytes = _mm256_packus_epi16(_mm256_packus_epi32(n, n), n);  // per lane: 4 counts first
    return std::uint64_t(_mm256_extract_epi32(bytes, 0)) | std::uint64_t(_mm256_extract_epi32(bytes, 4)) << 32;
}

// Stores the two 16-byte lanes of w, values of 12 digits with leading zeros and a separator, as
// their last n0 and n1 digits and the separator. Returns the end; stores 16 bytes per lane.
inline char* put_pair(char* p, __m256i w, unsigned n0, unsigned n1) {
    const __m256i shifted = _mm256_shuffle_epi8(w, _mm256_loadu2_m128i(
        reinterpret_cast<const __m128i*>(kShiftWindow + 12 - n1), reinterpret_cast<const __m128i*>(kShiftWindow + 12 - n0)));
    _mm_storeu_si128(reinterpret_cast<__m128i*>(p), _mm256_castsi256_si128(shifted));
    p += n0 + 1;
    _mm_storeu_si128(reinterpret_cast<__m128i*>(p), _mm256_extracti128_si256(shifted, 1));
    return p + n1 + 1;
}

// Writes the eight dwords of v in decimal, each followed by separator, and returns the end.
// Stores up to 15 bytes past the end.
inline char* format8(char* p, __m256i v, char separator) {
    // Digit counts first, from v: the store addresses then do not wait for the digits.
    const std::uint64_t n = digit_counts(v);
    // Lanes [v0 v2 v4 v6 | v1 v3 v5 v7], so the transpose below pairs consecutive values.
    v = _mm256_permutevar8x32_epi32(v, _mm256_setr_epi32(0, 2, 4, 6, 1, 3, 5, 7));
    const __m256i top = divide<1441151881, 57>(v);  // v / 10^8
    const __m256i rest = _mm256_sub_epi32(v, _mm256_mullo_epi32(top, _mm256_set1_epi32(100000000)));
    const __m256i high = divide<3518437209, 45>(rest);  // rest / 10^4
    const __m256i low = _mm256_sub_epi32(rest, _mm256_madd_epi16(high, _mm256_set1_epi32(10000)));
    const __m256i t = quad_digits(top), h = quad_digits(high), l = quad_digits(low);
    const __m256i s = _mm256_set1_epi32(static_cast<unsigned char>(separator));
    // Transpose: each 16-byte lane becomes one value as dwords [top, high, low, separator].
    const __m256i th_low = _mm256_unpacklo_epi32(t, h), th_high = _mm256_unpackhi_epi32(t, h);
    const __m256i ls_low = _mm256_unpacklo_epi32(l, s), ls_high = _mm256_unpackhi_epi32(l, s);
    const auto count = [n](int i) { return unsigned(n >> 8 * i & 0xFF); };
    p = put_pair(p, _mm256_unpacklo_epi64(th_low, ls_low), count(0), count(1));
    p = put_pair(p, _mm256_unpackhi_epi64(th_low, ls_low), count(2), count(3));
    p = put_pair(p, _mm256_unpacklo_epi64(th_high, ls_high), count(4), count(5));
    return put_pair(p, _mm256_unpackhi_epi64(th_high, ls_high), count(6), count(7));
}

// Parses uint32 tokens from the token at p into dst: at most count, from input that is valid up
// to limit. Stops when fewer than kMinTokens tokens or 1 KiB of input remain. Returns where it
// stopped and the tokens parsed. Each chunk of input is cut
// into four streams at token boundaries. The streams advance in lockstep, two tokens per step, so
// four independent pointer chains overlap.
class BulkParser {
public:
    static constexpr std::size_t kMinTokens = 1024;

    struct Result {
        const char* end;
        std::size_t parsed;
    };

    static Result parse(const char* p, const char* limit, std::uint32_t* dst, std::size_t count) {
        std::uint32_t* const first = dst;
        while (count >= kMinTokens && limit - p >= 1024 + 64) {
            // With tokens of at most 16 bytes a chunk spans at most chunk + 33 bytes, so it holds
            // at most chunk / 2 + 17 < count tokens: all of them belong to this array. It ends
            // before limit.
            const std::size_t chunk =
                std::min({kChunk, 2 * (count - 32), std::size_t(limit - p) - 64}) & ~std::size_t(3);
            const std::size_t stream = chunk / 4;
            const char* s[4] = {p, after_separator(p + stream), after_separator(p + 2 * stream),
                                after_separator(p + 3 * stream)};
            const char* const end[4] = {s[1], s[2], s[3], after_separator(p + chunk)};
            std::uint32_t* const out[4] = {dst, scratch_[0], scratch_[1], scratch_[2]};
            __m256i invalid = _mm256_setzero_si256();
            const std::size_t done = lockstep(s, end, out, invalid);
            std::size_t n[4];
            bool overrun = false;
            for (int k = 0; k < 4; ++k) {
                n[k] = done;
                while (s[k] < end[k] && n[k] < kCapacity) out[k][n[k]++] = one_token(s[k], invalid);
                overrun |= s[k] != end[k];
            }
            if (overrun || (std::uint32_t(_mm256_movemask_epi8(invalid)) & 0x80008000)) [[unlikely]] {
                // Irregular whitespace or tokens: this chunk one token at a time.
                const std::size_t tokens = std::min(count_tokens(p, end[3]), count);
                p = parse_slowly(p, dst, tokens);
                dst += tokens;
                count -= tokens;
                continue;
            }
            std::uint32_t* next = dst + n[0];
            for (int k = 1; k < 4; ++k) {
                std::memcpy(next, out[k], n[k] * sizeof(std::uint32_t));
                next += n[k];
            }
            dst = next;
            count -= n[0] + n[1] + n[2] + n[3];
            p = skip_whitespace(end[3]);
        }
        return {p, std::size_t(dst - first)};
    }

private:
    static constexpr std::size_t kChunk = std::size_t(1) << 17;
    // A step advances a stream by 2..33 bytes and yields two values, so a stream of at most
    // kChunk / 4 + 33 bytes yields at most kChunk / 4 + 66 values.
    static constexpr std::size_t kCapacity = kChunk / 4 + 66;
    alignas(64) static inline std::uint32_t scratch_[3][kCapacity];

    // Steps all streams while each has 33 bytes left; returns the values per stream. Works on
    // local copies of the stream state, which stay in registers.
    static std::size_t lockstep(const char* (&streams)[4], const char* const (&end)[4],
                                std::uint32_t* const (&outputs)[4], __m256i& flags) {
        const char* s[4] = {streams[0], streams[1], streams[2], streams[3]};
        std::uint32_t* const out[4] = {outputs[0], outputs[1], outputs[2], outputs[3]};
        __m256i invalid = flags;
        std::size_t done = 0;
        for (;;) {
            std::ptrdiff_t left = end[0] - s[0];
            for (int k = 1; k < 4; ++k) left = std::min(left, end[k] - s[k]);
            if (left < 33) break;
            for (std::ptrdiff_t steps = left / 33; steps; --steps, done += 2) {
                const __m256i g0 = two_tokens(s[0], invalid), g1 = two_tokens(s[1], invalid);
                const __m256i g2 = two_tokens(s[2], invalid), g3 = two_tokens(s[3], invalid);
                const __m256i k = _mm256_set1_epi32(0x00012710);
                // 8-digit halves: [s0 high, s0 low, s1 high, s1 low | second tokens likewise].
                const __m256 h01 = _mm256_castsi256_ps(_mm256_madd_epi16(_mm256_packus_epi32(g0, g1), k));
                const __m256 h23 = _mm256_castsi256_ps(_mm256_madd_epi16(_mm256_packus_epi32(g2, g3), k));
                const __m256i high = _mm256_castps_si256(_mm256_shuffle_ps(h01, h23, 0x88));
                const __m256i low = _mm256_castps_si256(_mm256_shuffle_ps(h01, h23, 0xDD));
                const __m256i v = _mm256_add_epi32(_mm256_mullo_epi32(high, _mm256_set1_epi32(100000000)), low);
                // [s0 a, s0 b, s1 a, s1 b | s2 a, s2 b, s3 a, s3 b]
                const __m256i q = _mm256_permutevar8x32_epi32(v, _mm256_setr_epi32(0, 4, 1, 5, 2, 6, 3, 7));
                const __m128i q01 = _mm256_castsi256_si128(q), q23 = _mm256_extracti128_si256(q, 1);
                _mm_storel_epi64(reinterpret_cast<__m128i*>(out[0] + done), q01);
                _mm_storeh_pd(reinterpret_cast<double*>(out[1] + done), _mm_castsi128_pd(q01));
                _mm_storel_epi64(reinterpret_cast<__m128i*>(out[2] + done), q23);
                _mm_storeh_pd(reinterpret_cast<double*>(out[3] + done), _mm_castsi128_pd(q23));
            }
        }
        for (int k = 0; k < 4; ++k) streams[k] = s[k];
        flags = invalid;
        return done;
    }

    // Two tokens at s, as 4-digit groups [first | second]. Lengths outside 1..16 (repeated
    // whitespace, long tokens) set the sign bit of byte 15 or 31 of invalid.
    [[gnu::always_inline]] static __m256i two_tokens(const char*& s, __m256i& invalid) {
        const __m256i bytes = _mm256_loadu_si256(reinterpret_cast<const __m256i*>(s));
        const std::uint32_t sep = separators(bytes);
        const auto first = std::size_t(std::countr_zero(sep));              // length of the first token
        const auto second = std::size_t(std::countr_zero(sep & (sep - 1)));  // 32 if none
        const __m256i windows =
            _mm256_inserti128_si256(bytes, _mm_loadu_si128(reinterpret_cast<const __m128i*>(s + first + 1)), 1);
        const __m256i rows = _mm256_set_m128i(align_row(second - first), align_row(first + 1));
        invalid = _mm256_or_si256(invalid, rows);
        s += second + 1;
        return digit_groups(_mm256_shuffle_epi8(_mm256_subs_epu8(windows, _mm256_set1_epi8('0')), rows));
    }

    static std::uint32_t one_token(const char*& s, __m256i& invalid) {
        const __m128i window = _mm_loadu_si128(reinterpret_cast<const __m128i*>(s));
        const unsigned n = unsigned(std::countr_zero(separators(window) | 0x10000));
        invalid = _mm256_or_si256(invalid, _mm256_castsi128_si256(align_row(n + 1)));
        s += n + 1;
        return std::uint32_t(parse16(window, n));
    }

    // The byte after the first separator at or after q.
    static const char* after_separator(const char* q) {
        for (;; q += 32)
            if (const std::uint32_t sep = separators(_mm256_loadu_si256(reinterpret_cast<const __m256i*>(q))))
                return q + std::countr_zero(sep) + 1;
    }

    static const char* skip_whitespace(const char* p) {
        while (static_cast<unsigned char>(*p) <= ' ') ++p;
        return p;
    }

    // Tokens in [p, end), where p starts a token.
    static std::size_t count_tokens(const char* p, const char* end) {
        std::size_t tokens = 1;
        for (const char* q = p + 1; q < end; ++q)
            tokens += static_cast<unsigned char>(*q) > ' ' && static_cast<unsigned char>(q[-1]) <= ' ';
        return tokens;
    }

    static const char* parse_slowly(const char* p, std::uint32_t* dst, std::size_t count) {
        for (std::size_t i = 0; i < count; ++i) {
            p = skip_whitespace(p);
            const __m128i window = _mm_loadu_si128(reinterpret_cast<const __m128i*>(p));
            const unsigned n = unsigned(std::countr_zero(separators(window) | 0x10000));
            dst[i] = std::uint32_t(parse16(window, n));
            p += n + 1;
        }
        return p;
    }
};

}  // namespace detail

// Token boundaries come from separator bitmasks of aligned 64-byte blocks: finding the next token
// clears one bit, so consecutive reads do not wait on each other's parsing.
class Reader {
public:
    // Takes everything that remains on fd (stdin by default).
    explicit Reader(int fd = 0) : input_(detail::open_input(fd)) { seek(input_.start); }

    ~Reader() { detail::release(input_); }

    Reader(const Reader&) = delete;
    Reader& operator=(const Reader&) = delete;

    // Next integer token, or the next non-whitespace character for char. MaxDigits, if set, promises
    // at most that many digits; for 64-bit types, 16 or fewer selects a faster parser.
    // Non-negative values parse faster as unsigned types (10-18%, see notes.md).
    template <class T, int MaxDigits = 0>
        requires std::integral<T> && (!std::same_as<T, bool>)
    T read() {
        if constexpr (std::same_as<T, char>) {
            skip_whitespace();
            return *cur_++;
        } else {
            const auto [start, length] = next_token();
            // A leading '-' sits below '0' and parses as a zero digit.
            const auto magnitude = parse<(sizeof(T) > 4), MaxDigits>(start + length, length);
            if constexpr (std::is_unsigned_v<T>) return T(magnitude);
            else return T(*start == '-' ? 0 - magnitude : magnitude);
        }
    }

    // count tokens into dst. uint32_t uses the AVX2 bulk parser; other types read one by one.
    template <int MaxDigits = 0, class T>
    void read(T* dst, std::size_t count) {
        if constexpr (std::same_as<T, std::uint32_t>) {
            skip_whitespace();
            const auto [stop, parsed] = detail::BulkParser::parse(cur_, input_.end, dst, count);
            seek(stop);
            for (std::size_t i = parsed; i < count; ++i) dst[i] = read<T>();
        } else {
            for (std::size_t i = 0; i < count; ++i) dst[i] = read<T, MaxDigits>();
        }
    }

    // Next token; valid while the Reader lives.
    std::string_view word() {
        const auto [start, length] = next_token();
        return {start, length};
    }

    // Tokenizer state, for custom token loops. separators has one bit per whitespace byte of the
    // 64-byte block at block, at or after cur. The lowest bit is the end of the token at cur: clear
    // it to move on. With no bits left, advance block by 64 and take detail::block_separators.
    struct Scan {
        const char* cur;
        const char* block;
        std::uint64_t separators;
    };

    Scan scan() const { return {cur_, block_, separators_}; }

    void resume(const Scan& scan) {
        cur_ = scan.cur;
        block_ = scan.block;
        separators_ = scan.separators;
    }

private:
    struct Token {
        const char* start;
        unsigned length;
    };

    // Continue reading at p.
    void seek(const char* p) {
        cur_ = p;
        block_ = reinterpret_cast<const char*>(reinterpret_cast<std::uintptr_t>(p) & ~std::uintptr_t(63));
        separators_ = detail::block_separators(block_) & ~std::uint64_t(0) << (cur_ - block_);
    }

    // Position of the next separator; at or after cur_.
    const char* next_separator() {
        while (!separators_) [[unlikely]] {
            block_ += 64;
            separators_ = detail::block_separators(block_);
        }
        return block_ + std::countr_zero(separators_);
    }

    void skip_whitespace() {
        while (next_separator() == cur_) {
            separators_ &= separators_ - 1;
            ++cur_;
        }
    }

    Token next_token() {
        for (;;) {
            const char* end = next_separator();
            separators_ &= separators_ - 1;
            const char* start = cur_;
            cur_ = end + 1;
            if (end != start) [[likely]] return {start, unsigned(end - start)};
        }
    }

    // Value of the n characters that end at end.
    template <bool Wide, int MaxDigits>
    static auto parse(const char* end, unsigned n) {
        if constexpr (!Wide) return std::uint32_t(detail::parse_ending16(end, n));
        else if constexpr (MaxDigits > 0 && MaxDigits <= 16) return detail::parse_ending16(end, n);
        else return detail::parse_ending24(end, n);
    }

    detail::Input input_;
    const char* cur_;             // next unread byte
    const char* block_;           // 64-byte block holding the next separator
    std::uint64_t separators_;    // separators in block_ at or after cur_
};

// Buffered output. write() takes any mix of integers, chars and strings:
//   out.write(x, ' ', y, '\n');
// MaxDigits, if set, promises integers of at most that many digits; for 64-bit types, 16 or fewer
// selects a faster formatter: out.write<16>(sum, '\n').
class Writer {
public:
    explicit Writer(int fd = 1) : fd_(fd) {}
    ~Writer() { flush(); }

    Writer(const Writer&) = delete;
    Writer& operator=(const Writer&) = delete;

    template <int MaxDigits = 0, class... Ts>
    void write(const Ts&... values) {
        const std::size_t needed = (std::size_t(0) + ... + max_size(values));
        if (needed > kCapacity) [[unlikely]] {
            (write_alone<MaxDigits>(values), ...);
            return;
        }
        if (std::size_t(buffer_ + kCapacity - cur_) < needed) [[unlikely]] flush();
        char* p = cur_;
        ((p = put<MaxDigits>(p, values)), ...);
        cur_ = p;
    }

    // Custom formatting: fill(p) may store up to max_size <= 64 KiB bytes at p and returns the end
    // of what it wrote.
    template <class Fill>
    void write_with(std::size_t max_size, Fill fill) {
        if (std::size_t(buffer_ + kCapacity - cur_) < max_size) [[unlikely]] flush();
        cur_ = fill(cur_);
    }

    // values[0..count) joined by separator. uint32_t uses the AVX2 formatter.
    template <int MaxDigits = 0, class T>
    void write_array(const T* values, std::size_t count, char separator) {
        if (!count) return;
        std::size_t i = 0;
        if constexpr (std::same_as<T, std::uint32_t>) {
            constexpr std::size_t kBatch = 8 * 11 + 16;  // eight values and separators, plus overhang
            char* p = cur_;
            for (; i + 8 <= count; i += 8) {
                if (std::size_t(buffer_ + kCapacity - p) < kBatch) [[unlikely]] {
                    cur_ = p;
                    flush();
                    p = cur_;
                }
                p = detail::format8(p, _mm256_loadu_si256(reinterpret_cast<const __m256i*>(values + i)), separator);
            }
            cur_ = p;
        }
        for (; i < count; ++i) write<MaxDigits>(values[i], separator);
        --cur_;  // no separator after the last value
    }

    void flush() {
        write_all(fd_, buffer_, std::size_t(cur_ - buffer_));
        cur_ = buffer_;
    }

private:
    static constexpr std::size_t kCapacity = std::size_t(1) << 16;

    template <class T>
    static constexpr bool kInteger = std::integral<T> && !std::same_as<T, char> && !std::same_as<T, bool>;

    // Bytes put() may store, which can exceed what it writes.
    template <class T>
    static std::size_t max_size(const T& value) {
        if constexpr (std::same_as<T, char>) return 1;
        else if constexpr (kInteger<T>) return 1 + 20;  // a sign, then format() stores up to 20 bytes
        else return std::string_view(value).size();
    }

    template <int MaxDigits, class T>
    static char* put(char* p, const T& value) {
        if constexpr (std::same_as<T, char>) {
            *p = value;
            return p + 1;
        } else if constexpr (kInteger<T>) {
            using U = std::conditional_t<sizeof(T) <= 4, std::uint32_t, std::uint64_t>;
            if constexpr (std::is_signed_v<T>) {
                *p = '-';
                p += value < 0;
                return put<MaxDigits>(p, value < 0 ? U(0 - U(value)) : U(value));
            } else if constexpr (sizeof(T) <= 4) {
                return detail::format(p, U(value));
            } else {
                return detail::format64<MaxDigits == 0 ? 20 : MaxDigits>(p, U(value));
            }
        } else {
            const std::string_view s(value);
            std::memcpy(p, s.data(), s.size());
            return p + s.size();
        }
    }

    // A value longer than the buffer: flush, then write it directly.
    template <int MaxDigits, class T>
    void write_alone(const T& value) {
        if constexpr (std::same_as<T, char> || kInteger<T>) {
            write<MaxDigits>(value);
        } else {
            flush();
            const std::string_view s(value);
            write_all(fd_, s.data(), s.size());
        }
    }

    static void write_all(int fd, const char* data, std::size_t size) {
        while (size) {
            const ssize_t put = ::write(fd, data, size);
            if (put > 0) data += put, size -= std::size_t(put);
            else if (put < 0 && errno == EINTR) continue;
            else std::abort();
        }
    }

    int fd_;
    char* cur_ = buffer_;
    alignas(64) char buffer_[kCapacity];
};

}  // namespace io
// lib/run/early.hpp
// Program entry for solutions. RUN_EARLY(solve) runs solve() from the executable's
// pre-initializers (.preinit_array), before the C++ runtime initializes iostreams and locales
// (lib/io uses neither) and before any static constructor, then ends the process with _exit(0):
// no exit handlers, no teardown, no unmapping. Elsewhere it defines main() { solve(); }.
// Measurements: lib/run/notes.md.
//
//   namespace {
//   void solve() { ... }  // flushes its output (io::Writer does on destruction)
//   }  // namespace
//
//   RUN_EARLY(solve)      // at namespace scope, once per program

#include <unistd.h>

#ifdef __ELF__
#define RUN_EARLY(solve)                                                                                  \
    namespace {                                                                                           \
    void run_early(int, char**, char**) {                                                                 \
        solve();                                                                                          \
        ::_exit(0);                                                                                       \
    }                                                                                                     \
    [[gnu::used, gnu::section(".preinit_array")]] void (*const preinit)(int, char**, char**) = run_early; \
    }                                                                                                     \
    int main() { solve(); }  // reached only if the loader skips .preinit_array
#else
#define RUN_EARLY(solve) \
    int main() { solve(); }
#endif
// problems/polynomial/factorization_of_polynomials/factor.hpp
// Factorization of a monic polynomial of degree <= 100 over F_p, p an odd prime < 2^30:
// - square-free decomposition (Yun's algorithm, with p-th roots where f' = 0);
// - per square-free part g: s = x^((p-1)/2) mod g, x^p = x s^2; the linear factors
//   L = gcd(g, x^p - x) by root finding (s mod L gives the first split);
// - the rest by Berlekamp: Q (rows x^(p j) mod g) by a Krylov sequence of the multiplication by
//   x^p, the kernel of Q - I (dimension k = number of factors), then either
//   - large p: the minimal polynomial mu of a random v in the kernel algebra B has k distinct
//     roots c_i (v = c_i mod g_i); g_i is split off by gcd(h, P(v)) for P the product of t - c
//     over half the roots, recursively (powers of v from the Krylov sequence give P(v));
//   - small p: Cantor-Zassenhaus on B, gcd(h, v^((p-1)/2) - 1) for random v until k pieces.

#include <cstdint>
#include <utility>
#include <vector>

// problems/polynomial/factorization_of_polynomials/field.hpp
// Arithmetic modulo an odd prime p < 2^30 in Montgomery form (x stored as x 2^32 mod p), and dense
// kernels on short coefficient arrays: linear combinations of columns, products, a x + b y.
//
// Lazy sums: a u64 accumulator after fold() is at most (2^32 - 1) p and takes `chunk` more
// products of two residues (each at most (p - 1)^2) before it must be folded again; reduce()
// takes any folded value. Vector kernels hold 8 residues per register and work on the even and
// odd 32-bit lanes separately (vpmuludq reads the low half of each 64-bit lane).

#include <immintrin.h>

#include <algorithm>
#include <cstddef>
#include <cstdint>

namespace factor {

using u32 = std::uint32_t;
using u64 = std::uint64_t;

class Field {
public:
    explicit Field(u32 modulus) : p(modulus) {
        u32 inverse = p;  // p^-1 mod 2^32 by Newton; p p = 1 mod 8 gives 3 bits
        for (int i = 0; i < 4; ++i) inverse *= 2 - p * inverse;
        neg_inv = -inverse;
        one = u32((u64(1) << 32) % p);
        r2 = u32(u64(one) * one % p);
        const u64 folded = u64(0xFFFFFFFF) * p, square = u64(p - 1) * (p - 1);
        chunk = int(std::min<u64>((~u64(0) - folded) / square, 1 << 20));
        vp = _mm256_set1_epi64x(p);
        vneg_inv = _mm256_set1_epi64x(neg_inv);
        vone = _mm256_set1_epi64x(one);
    }

    u32 p;
    u32 neg_inv;  // -p^-1 mod 2^32
    u32 one;      // 2^32 mod p: 1 in Montgomery form, and the fold factor
    u32 r2;       // 2^64 mod p
    int chunk;    // products a folded accumulator takes
    __m256i vp, vneg_inv, vone;

    static u64 fold(u64 x, u32 one) { return (x >> 32) * one + u32(x); }
    u64 fold(u64 x) const { return fold(x, one); }

    // x / 2^32 mod p, for x <= (2^32 - 1) p.
    u32 reduce(u64 x) const {
        const u32 m = u32(x) * neg_inv;
        const u32 t = u32((x + u64(m) * p) >> 32);
        return t >= p ? t - p : t;
    }
    u32 reduce_lazy(u64 x) const { return reduce(fold(x)); }

    u32 mul(u32 a, u32 b) const { return reduce(u64(a) * b); }
    u32 add(u32 a, u32 b) const { return a + b >= p ? a + b - p : a + b; }
    u32 sub(u32 a, u32 b) const { return a >= b ? a - b : a + p - b; }
    u32 neg(u32 a) const { return a ? p - a : 0; }
    u32 to(u32 a) const { return mul(a, r2); }  // a < p
    u32 from(u32 a) const { return reduce(a); }
    u32 power(u32 a, u64 e) const {
        u32 r = one;
        for (; e; e >>= 1, a = mul(a, a))
            if (e & 1) r = mul(r, a);
        return r;
    }
    u32 inverse(u32 a) const { return power(a, p - 2); }

    // Vector forms of fold and reduce on 64-bit lanes.
    __m256i fold(__m256i x) const {
        const __m256i high = _mm256_mul_epu32(_mm256_srli_epi64(x, 32), vone);
        return _mm256_add_epi64(high, _mm256_and_si256(x, _mm256_set1_epi64x(0xFFFFFFFF)));
    }
    __m256i reduce(__m256i x) const {
        const __m256i m = _mm256_mul_epu32(x, vneg_inv);
        const __m256i t = _mm256_srli_epi64(_mm256_add_epi64(x, _mm256_mul_epu32(m, vp)), 32);
        return _mm256_min_epu32(t, _mm256_sub_epi32(t, vp));
    }
    // Reduced even and odd lanes back into 8 residues.
    static __m256i pack(__m256i even, __m256i odd) { return _mm256_or_si256(even, _mm256_slli_epi64(odd, 32)); }
};

inline int round8(int n) { return (n + 7) & ~7; }

inline __m256i load(const u32* a) { return _mm256_loadu_si256(reinterpret_cast<const __m256i*>(a)); }
inline void store(u32* a, __m256i x) { _mm256_storeu_si256(reinterpret_cast<__m256i*>(a), x); }

// out[t] = a x[t] + b y[t] for t < 8 ceil(len / 8): Montgomery residues in and out; out may
// alias x or y.
inline void lincomb(const Field& F, u32* out, const u32* x, u32 a, const u32* y, u32 b, int len) {
    const __m256i va = _mm256_set1_epi32(int(a)), vb = _mm256_set1_epi32(int(b));
    for (int t = 0; t < len; t += 8) {
        const __m256i u = load(x + t), v = load(y + t);
        const __m256i even = _mm256_add_epi64(_mm256_mul_epu32(u, va), _mm256_mul_epu32(v, vb));
        const __m256i odd = _mm256_add_epi64(_mm256_mul_epu32(_mm256_srli_epi64(u, 32), va),
                                             _mm256_mul_epu32(_mm256_srli_epi64(v, 32), vb));
        store(out + t, Field::pack(F.reduce(even), F.reduce(odd)));  // sums <= 2 (p - 1)^2
    }
}

namespace detail {

alignas(32) inline constexpr u32 kZeros[32] = {};

// out[t] = scale init[t] + sum_s coef[s] column_s[t], t < 8 V, with column_s = base + s stride.
template <int V>
inline void combine_block(const Field& F, u32* out, const u32* init, u32 scale, const u32* coef, int count,
                          const u32* base, std::ptrdiff_t stride) {
    __m256i even[V], odd[V];
    const __m256i vscale = _mm256_set1_epi32(int(scale));
#pragma GCC unroll 4
    for (int v = 0; v < V; ++v) {
        const __m256i x = load(init + 8 * v);
        even[v] = _mm256_mul_epu32(x, vscale);
        odd[v] = _mm256_mul_epu32(_mm256_srli_epi64(x, 32), vscale);
    }
    const int chunk = F.chunk;
    for (int s0 = 0; s0 < count; s0 += chunk) {
        const int s1 = std::min(count, s0 + chunk);
        for (int s = s0; s < s1; ++s) {
            const __m256i c = _mm256_set1_epi32(int(coef[s]));
            const u32* column = base + s * stride;
#pragma GCC unroll 4
            for (int v = 0; v < V; ++v) {
                const __m256i x = load(column + 8 * v);
                even[v] = _mm256_add_epi64(even[v], _mm256_mul_epu32(c, x));
                odd[v] = _mm256_add_epi64(odd[v], _mm256_mul_epu32(c, _mm256_srli_epi64(x, 32)));
            }
        }
        if (s1 == count) break;
#pragma GCC unroll 4
        for (int v = 0; v < V; ++v) even[v] = F.fold(even[v]), odd[v] = F.fold(odd[v]);
    }
#pragma GCC unroll 4
    for (int v = 0; v < V; ++v) store(out + 8 * v, Field::pack(F.reduce(F.fold(even[v])), F.reduce(F.fold(odd[v]))));
}

}  // namespace detail

// out[t] = scale init[t] + sum_{s < count} coef[s] (base + s stride)[t] for t < 8 ceil(len / 8);
// init may be null (zero). Columns and init are read over the same rounded range; out may be init
// or a column.
inline void combine_scaled(const Field& F, u32* out, int len, const u32* init, u32 scale, const u32* coef, int count,
                           const u32* base, std::ptrdiff_t stride) {
    const int vectors = (len + 7) / 8;
    int v = 0;
    for (; v + 4 <= vectors; v += 4)
        detail::combine_block<4>(F, out + 8 * v, init ? init + 8 * v : detail::kZeros, scale, coef, count, base + 8 * v,
                                 stride);
    const u32* rest = init ? init + 8 * v : detail::kZeros;
    switch (vectors - v) {
        case 3: detail::combine_block<3>(F, out + 8 * v, rest, scale, coef, count, base + 8 * v, stride); break;
        case 2: detail::combine_block<2>(F, out + 8 * v, rest, scale, coef, count, base + 8 * v, stride); break;
        case 1: detail::combine_block<1>(F, out + 8 * v, rest, scale, coef, count, base + 8 * v, stride); break;
        default: break;
    }
}

// out[t] = init[t] + sum_{s < count} coef[s] (base + s stride)[t], as combine_scaled.
inline void combine(const Field& F, u32* out, int len, const u32* init, const u32* coef, int count, const u32* base,
                    std::ptrdiff_t stride) {
    combine_scaled(F, out, len, init, F.one, coef, count, base, stride);
}

inline constexpr int kProductCap = 256;  // coefficients of a product buffer (degree <= 2 * 100)

// out[0, na + nb - 1) = a b, zero up to the next multiple of 8 (32 when na + nb > 25); na, nb in
// [1, 128]. Blocks of 32 outputs, or one block of 8, 16 or 24.
inline void multiply(const Field& F, const u32* a, int na, const u32* b, int nb, u32* out) {
    alignas(32) u32 padded[32 + 128 + 32];  // b at offset 32, zeros around it
    std::fill(padded, padded + 32, 0);
    std::copy(b, b + nb, padded + 32);
    std::fill(padded + 32 + nb, padded + 64 + nb, 0);
    const int len = na + nb - 1;
    // Column s = b shifted by lo + s: (padded + 32 + t0 - lo - s)[t] = b[t0 + t - lo - s].
    switch ((len + 7) / 8) {
        case 1: return detail::combine_block<1>(F, out, detail::kZeros, F.one, a, na, padded + 32, -1);
        case 2: return detail::combine_block<2>(F, out, detail::kZeros, F.one, a, na, padded + 32, -1);
        case 3: return detail::combine_block<3>(F, out, detail::kZeros, F.one, a, na, padded + 32, -1);
        default: break;
    }
    for (int t0 = 0; t0 < len; t0 += 32) {
        const int lo = std::max(0, t0 - nb + 1), hi = std::min(na, t0 + 32);
        detail::combine_block<4>(F, out + t0, detail::kZeros, F.one, a + lo, hi - lo, padded + 32 + t0 - lo, -1);
    }
}

}  // namespace factor
// problems/polynomial/factorization_of_polynomials/kernel.hpp
// Right kernel of a matrix over F_p (odd p < 2^30, Montgomery entries) by fraction-free Gaussian
// elimination in blocks of kBlock columns, without inverses until the back substitution.
//
// In a block, pivot t (row R at column c_t) gives the row P_t = R eliminated by the earlier pivots,
// pi_t = P_t[c_t], and every other row R_i becomes, after t pivots,
//   R_i^(t) = L_t R_i - sum_{s<t} M_s[i] S_(s,t) P_s,  L_t = prod_{s<t} pi_s,
//   S_(s,t) = prod_{s<s'<t} pi_s',  M_s[i] = R_i^(s)[c_s]
// (from R^(t+1) = pi_t R^(t) - R^(t)[c_t] P_t). The panel columns R^(t)[c] of all rows, the pivot
// rows and finally the whole rows are each one lazy linear combination (combine).

#include <immintrin.h>

#include <algorithm>
#include <cstdint>
#include <vector>


namespace factor {

// rows x cols, row-major with stride ld = round8(cols), zero from cols on. The storage may be
// handed in and taken back (release), so its pages are touched once for several matrices.
struct Matrix {
    int rows = 0, cols = 0, ld = 0;
    std::vector<u32> a;

    Matrix(int r, int c, std::vector<u32>&& storage = {}) : rows(r), cols(c), ld(round8(c)), a(std::move(storage)) {
        a.assign(std::size_t(r) * ld, 0);
    }
    u32* row(int i) { return a.data() + std::size_t(i) * ld; }
    std::vector<u32> release() { return std::move(a); }
};

// dst.row(i)[j0 + q] = src[q stride + i] for q < 8, i < dst.rows: 8 x 8 blocks; src has 8 rows of
// round8(dst.rows) readable entries (zero rows for columns past dst.cols).
inline void transpose_columns(Matrix& dst, int j0, const u32* src, std::ptrdiff_t stride) {
    for (int i0 = 0; i0 < dst.rows; i0 += 8) {
        __m256i r[8], t[8];
        for (int q = 0; q < 8; ++q) r[q] = load(src + q * stride + i0);
        for (int q = 0; q < 8; q += 2) {
            t[q] = _mm256_unpacklo_epi32(r[q], r[q + 1]);
            t[q + 1] = _mm256_unpackhi_epi32(r[q], r[q + 1]);
        }
        for (int q = 0; q < 8; q += 4) {
            r[q] = _mm256_unpacklo_epi64(t[q], t[q + 2]);
            r[q + 1] = _mm256_unpackhi_epi64(t[q], t[q + 2]);
            r[q + 2] = _mm256_unpacklo_epi64(t[q + 1], t[q + 3]);
            r[q + 3] = _mm256_unpackhi_epi64(t[q + 1], t[q + 3]);
        }
        for (int q = 0; q < 4; ++q) {
            t[q] = _mm256_permute2x128_si256(r[q], r[q + 4], 0x20);
            t[q + 4] = _mm256_permute2x128_si256(r[q], r[q + 4], 0x31);
        }
        for (int q = 0; q < 8 && i0 + q < dst.rows; ++q) store(dst.row(i0 + q) + j0, t[q]);
    }
}

// Basis of the kernel: vector i is 1 at free[i], 0 at the other free columns.
struct Kernel {
    std::vector<int> free;
    int stride = 0;          // of the vectors: round8(cols)
    std::vector<u32> basis;  // vector i at basis + i stride, entries [0, cols), zero after

    const u32* vector(int i) const { return basis.data() + std::size_t(i) * stride; }
};

// a[i] <- a[i]^-1 for nonzero a[0, n): one inverse and 3 (n - 1) products.
inline void invert_all(const Field& F, u32* a, int n) {
    std::vector<u32> prefix(n);
    u32 acc = F.one;
    for (int i = 0; i < n; ++i) prefix[i] = acc, acc = F.mul(acc, a[i]);
    acc = F.inverse(acc);
    for (int i = n - 1; i >= 0; --i) {
        const u32 inverse = F.mul(acc, prefix[i]);
        acc = F.mul(acc, a[i]);
        a[i] = inverse;
    }
}

inline Kernel kernel(const Field& F, Matrix& A) {
    constexpr int kBlock = 16;
    const int rows = A.rows, cols = A.cols, ld = A.ld;
    std::vector<int> trailing(rows), pivots, pivot_rows;  // pivot t: column, row of A holding P_t
    std::vector<u32> pivot_values;
    for (int i = 0; i < rows; ++i) trailing[i] = i;
    const int pstride = round8(rows);
    std::vector<u32> panel(std::size_t(kBlock + 1) * pstride);  // M_0 .. M_(nb-1), then the work column
    std::vector<u32> block(std::size_t(kBlock + 1) * ld);         // P_0 .. P_(nb-1), then the new row
    std::vector<char> chosen(rows);
    Kernel K;
    for (int c0 = 0; c0 < cols; c0 += kBlock) {
        const int c1 = std::min(cols, c0 + kBlock), n = int(trailing.size()), from = c0 & ~7, len = cols - from;
        u32* P = block.data();
        int nb = 0;
        u32 lambda = F.one, sigma[kBlock], coef[kBlock + 1];  // L_nb and S_(s,nb)
        std::fill(chosen.begin(), chosen.begin() + n, 0);
        for (int c = c0; c < c1; ++c) {
            if (n == 0) {
                K.free.push_back(c);
                continue;
            }
            // Work column: R^(nb)[c] = L_nb R[c] - sum_s M_s S_(s,nb) P_s[c].
            u32* work = &panel[std::size_t(nb) * pstride];
            for (int i = 0; i < n; ++i) work[i] = A.row(trailing[i])[c];
            std::fill(work + n, work + pstride, 0);
            for (int s = 0; s < nb; ++s) coef[s] = F.neg(F.mul(sigma[s], P[s * ld + c]));
            coef[nb] = lambda;
            combine(F, work, n, nullptr, coef, nb + 1, panel.data(), pstride);
            int i = 0;
            while (i < n && (chosen[i] || work[i] == 0)) ++i;
            if (i == n) {
                K.free.push_back(c);
                continue;
            }
            // Pivot row: P_nb = L_nb R - sum_s M_s[i] S_(s,nb) P_s, from a copy of R after P_(nb-1).
            chosen[i] = 1;
            u32* pivot = P + nb * ld;
            std::copy(A.row(trailing[i]), A.row(trailing[i]) + ld, pivot);
            for (int s = 0; s < nb; ++s) coef[s] = F.neg(F.mul(panel[std::size_t(s) * pstride + i], sigma[s]));
            coef[nb] = lambda;
            combine(F, pivot + from, len, nullptr, coef, nb + 1, P + from, ld);
            std::copy(pivot, pivot + ld, A.row(trailing[i]));
            const u32 pi = work[i];
            pivots.push_back(c), pivot_rows.push_back(trailing[i]), pivot_values.push_back(pi);
            for (int s = 0; s < nb; ++s) sigma[s] = F.mul(sigma[s], pi);
            sigma[nb] = F.one, lambda = F.mul(lambda, pi), ++nb;
        }
        if (nb == 0) continue;
        // Other rows: R^(nb) = L_nb R - sum_s M_s S_(s,nb) P_s.
        int kept = 0;
        for (int i = 0; i < n; ++i) {
            if (chosen[i]) continue;
            for (int s = 0; s < nb; ++s) coef[s] = F.neg(F.mul(panel[std::size_t(s) * pstride + i], sigma[s]));
            u32* r = A.row(trailing[i]) + from;
            combine_scaled(F, r, len, r, lambda, coef, nb, P + from, ld);
            trailing[kept++] = trailing[i];
        }
        trailing.resize(kept);
    }
    // Back substitution for all kernel vectors at once: row j of X holds entry j of each vector;
    // x[c_t] = -sum_{j > c_t} P_t[j] x[j] / pi_t, pivots in increasing column order.
    const int k = int(K.free.size()), width = round8(k), rank = int(pivots.size());
    invert_all(F, pivot_values.data(), rank);
    std::vector<u32> X(std::size_t(cols) * width, 0);
    for (int i = 0; i < k; ++i) X[std::size_t(K.free[i]) * width + i] = F.one;
    for (int t = rank - 1; t >= 0; --t) {
        const int c = pivots[t];
        u32* x = X.data() + std::size_t(c) * width;
        if (c + 1 < cols) combine(F, x, k, nullptr, A.row(pivot_rows[t]) + c + 1, cols - c - 1, x + width, width);
        const u32 scale = F.neg(pivot_values[t]);
        for (int i = 0; i < k; ++i) x[i] = F.mul(x[i], scale);
    }
    K.stride = round8(cols);
    K.basis.assign(std::size_t(k) * K.stride, 0);
    for (int j = 0; j < cols; ++j)
        for (int i = 0; i < k; ++i) K.basis[std::size_t(i) * K.stride + j] = X[std::size_t(j) * width + i];
    return K;
}

}  // namespace factor
// problems/polynomial/factorization_of_polynomials/poly.hpp
// Polynomials of degree < 128 over F_p (odd p < 2^30) with Montgomery coefficients: gcd, division,
// products modulo a monic g by a table of x^(m + j) mod g, powers modulo g.

#include <algorithm>
#include <cstdint>
#include <vector>


namespace factor {

inline constexpr int kCap = 128;  // coefficients of a Poly; inputs have degree <= 100

// c[0, n) with c[n - 1] != 0 (n = 0: the zero polynomial); c is zero from n on, so kernels may
// read and write whole vectors past n.
struct Poly {
    int n = 0;
    alignas(32) u32 c[kCap] = {};

    int degree() const { return n - 1; }
    u32 lead() const { return c[n - 1]; }
    void trim() {
        while (n > 0 && c[n - 1] == 0) --n;
    }
};

// A monic g of degree m >= 1 with T_j = x^(m + j) mod g, j < m - 1, at table + j stride.
struct Modulus {
    Poly g;
    int m = 0;
    int stride = 0;
    std::vector<u32> table;
};

class Ring {
public:
    explicit Ring(const Field& field) : F(field) {}

    const Field& F;

    Poly constant(u32 a) const {
        Poly r;
        r.c[0] = a;
        r.n = a != 0;
        return r;
    }
    // x - z.
    Poly linear(u32 z) const {
        Poly r;
        r.c[0] = F.neg(z), r.c[1] = F.one, r.n = 2;
        return r;
    }

    void make_monic(Poly& a) const {
        const u32 s = F.inverse(a.lead());
        for (int i = 0; i < a.n; ++i) a.c[i] = F.mul(a.c[i], s);
    }

    // Monic gcd (zero if both are zero). Fraction-free Euclid: a <- lc(b) a - lc(a) x^s b kills
    // the leading term without inverses; remainders are right up to constant factors.
    Poly gcd(const Poly& a0, const Poly& b0) const {
        alignas(32) u32 buffer[2][2 * kCap + 8];  // kCap zeros, then the coefficients
        int na = a0.n, nb = b0.n;
        const int lead = std::max(na, nb), span = round8(lead) + 8;  // reads reach a - lead, a + span
        u32* a = buffer[0] + kCap;
        u32* b = buffer[1] + kCap;
        for (u32* x : {a, b}) std::fill(x - lead, x + span, 0);
        std::copy(a0.c, a0.c + na, a);
        std::copy(b0.c, b0.c + nb, b);
        if (na < nb) std::swap(a, b), std::swap(na, nb);
        while (nb > 0) {
            while (na >= nb) {
                lincomb(F, a, a, b[nb - 1], b - (na - nb), F.neg(a[na - 1]), na - 1);
                a[--na] = 0;
                while (na > 0 && a[na - 1] == 0) --na;
            }
            std::swap(a, b), std::swap(na, nb);
        }
        Poly g;
        g.n = na;
        std::copy(a, a + na, g.c);
        if (na > 0) make_monic(g);
        return g;
    }

    // h = q d + r with deg r < deg d, d monic. q or r may be null.
    void divide(const Poly& h, const Poly& d, Poly* q, Poly* r) const {
        alignas(32) u32 a[kCap + 8] = {};
        std::copy(h.c, h.c + h.n, a);
        const int dd = d.n - 1;
        if (q) *q = Poly{}, q->n = std::max(0, h.n - dd);
        for (int i = h.n - 1; i >= dd; --i) {
            const u32 c = a[i];
            if (q) q->c[i - dd] = c;
            if (c != 0) lincomb(F, a + i - dd, a + i - dd, F.one, d.c, F.neg(c), dd + 1);  // a[i] -> 0
        }
        if (r) {
            *r = Poly{};
            r->n = std::min(h.n, dd);
            std::copy(a, a + r->n, r->c);
            r->trim();
        }
    }
    Poly quotient(const Poly& h, const Poly& d) const {
        Poly q;
        divide(h, d, &q, nullptr);
        return q;
    }
    Poly remainder(const Poly& h, const Poly& d) const {
        if (h.n < d.n) return h;
        Poly r;
        divide(h, d, nullptr, &r);
        return r;
    }

    // y = x a mod g for a of degree < m = deg g (y may be a).
    void times_x(const u32* a, u32* y, const Poly& g) const {
        const int m = g.n - 1;
        alignas(32) u32 shifted[kCap + 8];
        shifted[0] = 0;
        std::copy(a, a + m, shifted + 1);
        std::fill(shifted + m + 1, shifted + round8(m) + 8, 0);
        lincomb(F, y, shifted, F.one, g.c, F.neg(a[m - 1]), m);  // y[m] = a[m-1] - a[m-1] = 0
    }

    // The table goes into storage (its capacity is reused).
    Modulus modulus(const Poly& g, std::vector<u32>&& storage = {}) const {
        Modulus M;
        M.g = g;
        M.m = g.n - 1;
        M.stride = round8(M.m);
        M.table = std::move(storage);
        M.table.assign(std::size_t(std::max(M.m - 1, 0)) * M.stride, 0);
        if (M.m >= 2) {
            u32* t = M.table.data();
            for (int i = 0; i < M.m; ++i) t[i] = F.neg(g.c[i]);
            for (int j = 1; j < M.m - 1; ++j) times_x(t + (j - 1) * M.stride, t + j * M.stride, g);
        }
        return M;
    }

    // a b mod g; a and b of degree < m.
    Poly multiply_mod(const Poly& a, const Poly& b, const Modulus& M) const {
        Poly r;
        if (a.n == 0 || b.n == 0) return r;
        if (M.m <= 8) return to_poly(multiply_small(load(a.c), load(b.c), M), M.m);
        alignas(32) u32 product[kProductCap];
        multiply(F, a.c, a.n, b.c, b.n, product);
        const int len = a.n + b.n - 1;
        r.n = std::min(len, M.m);
        std::copy(product, product + r.n, r.c);
        if (len > M.m) combine(F, r.c, M.m, r.c, product + M.m, len - M.m, M.table.data(), M.stride);
        r.trim();
        return r;
    }

    // a b mod h without a table; deg a + deg b < kCap.
    Poly multiply_remainder(const Poly& a, const Poly& b, const Poly& h) const {
        Poly c;
        if (a.n == 0 || b.n == 0) return c;
        alignas(32) u32 product[kProductCap];
        multiply(F, a.c, a.n, b.c, b.n, product);
        c.n = a.n + b.n - 1;
        std::copy(product, product + c.n, c.c);
        return remainder(c, h);
    }

    Poly times_x(const Poly& a, const Modulus& M) const {
        Poly r;
        if (a.n == 0) return r;
        times_x(a.c, r.c, M.g);
        r.n = M.m;
        r.trim();
        return r;
    }

    // Polynomials modulo g of degree m <= 8 in one vector (lanes from m on zero): chains of 30
    // squarings at tiny degrees (root finding, splitting) are latency-bound, so no memory trips.
    // a b mod g: product in two vectors (b shifted in registers), then c[0, m) + sum c[m + j] T_j.
    __m256i multiply_small(__m256i a, __m256i b, const Modulus& M) const {
        const int m = M.m;
        const __m256i lanes = _mm256_setr_epi32(0, 1, 2, 3, 4, 5, 6, 7), zero = _mm256_setzero_si256();
        __m256i lo_even = zero, lo_odd = zero, hi_even = zero, hi_odd = zero;
        for (int i = 0; i < m; ++i) {  // at most 8 products per sum: below 2^63
            const __m256i x = _mm256_permutevar8x32_epi32(a, _mm256_set1_epi32(i));
            const __m256i index = _mm256_sub_epi32(lanes, _mm256_set1_epi32(i));  // lane t: b[t - i]
            const __m256i rotated = _mm256_permutevar8x32_epi32(b, index);
            const __m256i below = _mm256_cmpgt_epi32(_mm256_set1_epi32(i), lanes);  // t < i: high half
            const __m256i low = _mm256_andnot_si256(below, rotated), high = _mm256_and_si256(below, rotated);
            lo_even = _mm256_add_epi64(lo_even, _mm256_mul_epu32(x, low));
            lo_odd = _mm256_add_epi64(lo_odd, _mm256_mul_epu32(x, _mm256_srli_epi64(low, 32)));
            hi_even = _mm256_add_epi64(hi_even, _mm256_mul_epu32(x, high));
            hi_odd = _mm256_add_epi64(hi_odd, _mm256_mul_epu32(x, _mm256_srli_epi64(high, 32)));
        }
        const __m256i lo = Field::pack(F.reduce(F.fold(lo_even)), F.reduce(F.fold(lo_odd)));
        const __m256i hi = Field::pack(F.reduce(F.fold(hi_even)), F.reduce(F.fold(hi_odd)));
        // c[m + j] is lane m + j of lo, or lane m + j - 8 of hi.
        const __m256i in_low = _mm256_cmpgt_epi32(_mm256_set1_epi32(m), lanes);
        const __m256i c = _mm256_and_si256(lo, in_low);
        __m256i even = _mm256_slli_epi64(c, 32), odd = _mm256_and_si256(c, _mm256_set1_epi64x(~0xFFFFFFFFll));
        for (int j = 0; j < m - 1; ++j) {
            const int t = m + j;
            const __m256i x = _mm256_permutevar8x32_epi32(t < 8 ? lo : hi, _mm256_set1_epi32(t & 7));
            const __m256i row = load(M.table.data() + j * M.stride);
            even = _mm256_add_epi64(even, _mm256_mul_epu32(x, row));
            odd = _mm256_add_epi64(odd, _mm256_mul_epu32(x, _mm256_srli_epi64(row, 32)));
        }
        return Field::pack(F.reduce(F.fold(even)), F.reduce(F.fold(odd)));
    }

    // (x + a) u mod g = shifted u + a u - u[m - 1] g.
    __m256i times_linear_small(__m256i u, u32 a, const Modulus& M) const {
        const int m = M.m;
        const __m256i lanes = _mm256_setr_epi32(0, 1, 2, 3, 4, 5, 6, 7);
        const __m256i shifted = _mm256_and_si256(_mm256_permutevar8x32_epi32(u, _mm256_sub_epi32(lanes, _mm256_set1_epi32(1))),
                                                 _mm256_cmpgt_epi32(lanes, _mm256_setzero_si256()));
        const __m256i top = _mm256_permutevar8x32_epi32(u, _mm256_set1_epi32(m - 1));
        const __m256i g = load(M.g.c), scale = _mm256_set1_epi32(int(a));
        const __m256i minus_top = _mm256_sub_epi32(_mm256_set1_epi32(int(F.p)), top);  // p - top, top < p
        const __m256i one = _mm256_set1_epi32(int(F.one));
        auto part = [&](__m256i s, __m256i v, __m256i h) {  // s one + v a + h (p - top): below 3 p^2
            return _mm256_add_epi64(_mm256_add_epi64(_mm256_mul_epu32(s, one), _mm256_mul_epu32(v, scale)),
                                    _mm256_mul_epu32(h, minus_top));
        };
        const __m256i even = part(shifted, u, g);
        const __m256i odd = part(_mm256_srli_epi64(shifted, 32), _mm256_srli_epi64(u, 32), _mm256_srli_epi64(g, 32));
        const __m256i r = Field::pack(F.reduce(F.fold(even)), F.reduce(F.fold(odd)));
        return _mm256_and_si256(r, _mm256_cmpgt_epi32(_mm256_set1_epi32(m), lanes));  // lane m: top - top g_m
    }

    Poly to_poly(__m256i x, int m) const {
        Poly r;
        store(r.c, x);
        r.n = m;
        r.trim();
        return r;
    }

    // x^e mod g, e >= 1, deg g >= 2.
    Poly power_of_x(u64 e, const Modulus& M) const {
        Poly r = linear(0);
        for (int bit = 62 - __builtin_clzll(e); bit >= 0; --bit) {
            r = multiply_mod(r, r, M);
            if (e >> bit & 1) r = times_x(r, M);
        }
        return r;
    }

    // (x + a)^e mod g, e >= 1, deg g >= 2.
    Poly power_of_linear(u32 a, u64 e, const Modulus& M) const {
        const Poly base = linear(F.neg(a));
        if (M.m <= 8) {
            __m256i r = load(base.c);
            for (int bit = 62 - __builtin_clzll(e); bit >= 0; --bit) {
                r = multiply_small(r, r, M);
                if (e >> bit & 1) r = times_linear_small(r, a, M);
            }
            return to_poly(r, M.m);
        }
        Poly r = base;
        for (int bit = 62 - __builtin_clzll(e); bit >= 0; --bit) {
            r = multiply_mod(r, r, M);
            if (e >> bit & 1) {
                Poly s = times_x(r, M);
                lincomb(F, s.c, s.c, F.one, r.c, a, M.m);
                s.n = M.m;
                s.trim();
                r = s;
            }
        }
        return r;
    }

    // u^e mod g, e >= 1, deg u < deg g.
    Poly power(const Poly& u, u64 e, const Modulus& M) const {
        if (M.m <= 8) {
            const __m256i base = load(u.c);
            __m256i r = base;
            for (int bit = 62 - __builtin_clzll(e); bit >= 0; --bit) {
                r = multiply_small(r, r, M);
                if (e >> bit & 1) r = multiply_small(r, base, M);
            }
            return to_poly(r, M.m);
        }
        Poly r = u;
        for (int bit = 62 - __builtin_clzll(e); bit >= 0; --bit) {
            r = multiply_mod(r, r, M);
            if (e >> bit & 1) r = multiply_mod(r, u, M);
        }
        return r;
    }

    Poly derivative(const Poly& f) const {
        Poly d;
        for (int i = 1; i < f.n; ++i) d.c[i - 1] = F.mul(f.c[i], F.to(u32(i % F.p)));
        d.n = std::max(f.n - 1, 0);
        d.trim();
        return d;
    }

    // g with g(x^p) = f, for f' = 0 (then f = g^p, as a^p = a in F_p).
    Poly pth_root(const Poly& f) const {
        Poly g;
        g.n = (f.n - 1) / int(F.p) + 1;
        for (int i = 0; i < g.n; ++i) g.c[i] = f.c[i * F.p];
        return g;
    }

    // A square root of a square a (Montgomery) by Cipolla: for t with w = t^2 - a a non-square,
    // (t + y)^((p + 1) / 2) in F_p[y] / (y^2 - w). About 2 log p products in F_p^2, whatever the
    // power of 2 in p - 1 (Tonelli-Shanks takes up to log^2 p for p = 998244353).
    u32 sqrt(u32 a) const {
        const u32 minus_one = F.neg(F.one);
        u32 t = 0, w = F.neg(a);
        while (w != 0 && F.power(w, (F.p - 1) / 2) != minus_one) t = F.add(t, F.one), w = F.sub(F.mul(t, t), a);
        if (w == 0) return t;
        u32 x0 = F.one, x1 = 0, b0 = t, b1 = F.one;  // x = x0 + x1 y, b = b0 + b1 y
        for (u64 e = (F.p + 1) / 2; e; e >>= 1) {
            if (e & 1) {
                const u32 y0 = F.add(F.mul(x0, b0), F.mul(F.mul(x1, b1), w));
                x1 = F.add(F.mul(x0, b1), F.mul(x1, b0)), x0 = y0;
            }
            const u32 c0 = F.add(F.mul(b0, b0), F.mul(F.mul(b1, b1), w));
            b1 = F.mul(F.add(b0, b0), b1), b0 = c0;
        }
        return x0;
    }
};

}  // namespace factor

namespace factor {

struct Factor {
    u64 multiplicity;
    std::vector<u32> coefficients;  // b_0 .. b_d in [0, p), b_d = 1
};

class OddFactorizer {
public:
    explicit OddFactorizer(u32 p) : F_(p), R_(F_) {
        columns_.reserve(kCap * kCap);
        matrix_.reserve(kCap * kCap);
    }

    // f: coefficients a_0 .. a_N in [0, p), a_N = 1, N >= 1.
    std::vector<Factor> run(const std::vector<u32>& f) {
        Poly g;
        g.n = int(f.size());
        for (int i = 0; i < g.n; ++i) g.c[i] = F_.to(f[i]);
        square_free(g, 1);
        return std::move(factors_);
    }

private:
    static constexpr u32 kExhaustiveRoots = 256;  // p up to this: roots by evaluation at every point

    Field F_;
    Ring R_;
    u64 state_ = 0x9E3779B97F4A7C15ull;
    u64 multiplicity_ = 1;
    std::vector<Factor> factors_;
    // Storage for the m x m arrays, reused so their pages fault in once (1.6 us per 4 KiB page,
    // lib/mem/notes.md): the reduction table, then the multiplications by x^p and by v (columns_);
    // (Q - I)^T, then the powers of v (matrix_).
    std::vector<u32> columns_, matrix_;

    u32 random_residue() {  // splitmix64
        u64 z = (state_ += 0x9E3779B97F4A7C15ull);
        z = (z ^ (z >> 30)) * 0xBF58476D1CE4E5B9ull;
        z = (z ^ (z >> 27)) * 0x94D049BB133111EBull;
        return u32((z ^ (z >> 31)) % F_.p);
    }

    void emit(const Poly& g) {
        Factor f{multiplicity_, std::vector<u32>(g.n)};
        for (int i = 0; i < g.n; ++i) f.coefficients[i] = F_.from(g.c[i]);
        factors_.push_back(std::move(f));
    }

    void square_free(const Poly& f, u64 multiplicity) {
        const Poly df = R_.derivative(f);
        if (df.n == 0) return square_free(R_.pth_root(f), multiplicity * F_.p);
        Poly c = R_.gcd(f, df), w = R_.quotient(f, c);
        for (u64 i = 1; w.n > 1; ++i) {
            const Poly y = R_.gcd(w, c), z = R_.quotient(w, y);
            if (z.n > 1) {
                multiplicity_ = multiplicity * i;
                factor_square_free(z);
            }
            w = y;
            c = R_.quotient(c, y);
        }
        if (c.n > 1) square_free(R_.pth_root(c), multiplicity * F_.p);
    }

    void factor_square_free(const Poly& g) {
        if (g.n == 2) return emit(g);
        Modulus M = R_.modulus(g, std::move(columns_));
        split_square_free(M);
        columns_ = std::move(M.table);
    }

    // M.table is scratch afterwards.
    void split_square_free(Modulus& M) {
        Poly g = M.g;
        const Poly s = R_.power_of_x((F_.p - 1) / 2, M);
        Poly r = R_.times_x(R_.multiply_mod(s, s, M), M);  // x^p mod g
        Poly u = r;
        u.c[1] = F_.sub(u.c[1], F_.one);
        u.n = std::max(u.n, 2);
        u.trim();
        const Poly linear = R_.gcd(g, u);
        if (linear.n > 1) {
            const Poly hint = R_.remainder(s, linear);
            std::vector<u32> roots;
            find_roots(linear, &hint, roots);
            for (const u32 z : roots) emit(R_.linear(z));
            if (linear.n == g.n) return;
            g = R_.quotient(g, linear);
            r = R_.remainder(r, g);
            M = R_.modulus(g, std::move(M.table));
        }
        if (g.n <= 4) return emit(g);  // degree <= 3 without roots
        berlekamp(M, r);
    }

    // Roots of a monic P that splits into distinct linear factors; hint: x^((p-1)/2) mod P or null.
    void find_roots(const Poly& P, const Poly* hint, std::vector<u32>& roots) {
        const int d = P.n - 1;
        if (d == 1) return roots.push_back(F_.neg(P.c[0]));
        if (d == 2) {
            const u32 b = P.c[1], c = P.c[0];
            const u32 disc = F_.sub(F_.mul(b, b), F_.mul(F_.to(4), c));
            const u32 root = R_.sqrt(disc), half = F_.inverse(F_.to(2));
            roots.push_back(F_.mul(F_.sub(root, b), half));
            roots.push_back(F_.mul(F_.sub(F_.neg(b), root), half));
            return;
        }
        if (F_.p <= kExhaustiveRoots) {
            for (u32 z = 0; z < F_.p && int(roots.size()) < d; ++z) {
                const u32 x = F_.to(z);
                u32 value = P.c[d];
                for (int i = d - 1; i >= 0; --i) value = F_.add(F_.mul(value, x), P.c[i]);
                if (value == 0) roots.push_back(x);
            }
            return;
        }
        const Modulus M = R_.modulus(P);
        Poly w = hint ? *hint : R_.power_of_linear(random_residue(), (F_.p - 1) / 2, M);
        for (;;) {
            w.c[0] = F_.sub(w.c[0], F_.one);
            w.n = std::max(w.n, 1);
            w.trim();
            const Poly G = R_.gcd(P, w);
            if (G.n > 1 && G.n < P.n) {
                find_roots(G, nullptr, roots);
                find_roots(R_.quotient(P, G), nullptr, roots);
                return;
            }
            w = R_.power_of_linear(random_residue(), (F_.p - 1) / 2, M);
        }
    }

    // Columns x^s u mod g, s < m, of the multiplication by u, into M.table.
    void multiplication_matrix(Modulus& M, const Poly& u) {
        const int m = M.m, stride = M.stride;
        std::vector<u32>& columns = M.table;
        columns.assign(std::size_t(m) * stride, 0);
        std::copy(u.c, u.c + u.n, columns.begin());
        for (int s = 1; s < m; ++s)
            R_.times_x(&columns[std::size_t(s - 1) * stride], &columns[std::size_t(s) * stride], M.g);
    }

    void berlekamp(Modulus& M, const Poly& r) {
        const int m = M.m, stride = M.stride;
        multiplication_matrix(M, r);
        // A = (Q - I)^T for the rows q_j = x^(p j) mod g, 8 rows at a time: the kernel of A is
        // {v : v^p = v mod g}.
        Matrix A(m, m, std::move(matrix_));
        alignas(32) u32 rows[8 * kCap];
        for (int j0 = 0; j0 < m; j0 += 8) {
            for (int q = 0; q < 8; ++q) {
                u32* row = rows + q * stride;
                const int j = j0 + q;
                if (j == 0) {
                    std::fill(row, row + stride, 0);
                    row[0] = F_.one;
                } else if (j < m) {
                    const u32* previous = q ? row - stride : rows + 7 * stride;
                    combine(F_, row, m, nullptr, previous, m, M.table.data(), stride);
                } else {
                    std::fill(row, row + stride, 0);
                }
            }
            transpose_columns(A, j0, rows, stride);
        }
        for (int i = 0; i < m; ++i) A.row(i)[i] = F_.sub(A.row(i)[i], F_.one);
        const Kernel B = kernel(F_, A);
        matrix_ = A.release();
        const int k = int(B.free.size());
        if (k == 1) return emit(M.g);
        if (u64(k) * k * 32 < F_.p)
            split_by_minimal_polynomial(M, B);
        else
            split_by_powers(M, B);
    }

    // Random element of the kernel algebra. The constant term matters for split_by_powers: without
    // it, the values on two factors keep a fixed ratio when k = 2.
    Poly random_element(const Modulus& M, const Kernel& B) {
        const int k = int(B.free.size());
        std::vector<u32> coef(k);
        for (auto& c : coef) c = random_residue();
        Poly v;
        combine(F_, v.c, M.m, nullptr, coef.data(), k, B.basis.data(), B.stride);
        v.n = M.m;
        v.trim();
        return v;
    }

    void split_by_minimal_polynomial(Modulus& M, const Kernel& B) {
        const int m = M.m, stride = M.stride, k = int(B.free.size());
        std::vector<u32>& powers = matrix_;
        for (;;) {
            const Poly v = random_element(M, B);
            multiplication_matrix(M, v);
            // powers j = v^j mod g; their coordinates in B are the entries at the free columns.
            powers.assign(std::size_t(k + 1) * stride, 0);
            powers[0] = F_.one;
            for (int j = 0; j < k; ++j)
                combine(F_, &powers[std::size_t(j + 1) * stride], m, nullptr, &powers[std::size_t(j) * stride], m,
                        M.table.data(), stride);
            Matrix C(k, k + 1);
            for (int t = 0; t < k; ++t)
                for (int j = 0; j <= k; ++j) C.row(t)[j] = powers[std::size_t(j) * stride + B.free[t]];
            const Kernel mu = kernel(F_, C);
            if (mu.free.size() != 1) continue;  // two factors share a value of v: deg mu < k
            Poly minimal;
            minimal.n = k + 1;
            std::copy(mu.vector(0), mu.vector(0) + k + 1, minimal.c);
            std::vector<u32> roots;
            find_roots(minimal, nullptr, roots);
            extract(M.g, v, roots, 0, k, powers, stride, m);
            return;
        }
    }

    // h is the product of the g_i whose value c_i of v is in roots[lo, hi); vh = v mod h. The left
    // part is gcd(h, P(v)) for P = prod over roots[lo, mid) of (t - c): from the powers of v mod g
    // near the top, by Horner on v mod h once that is cheaper (small h, few roots).
    void extract(const Poly& h, const Poly& vh, const std::vector<u32>& roots, int lo, int hi,
                 const std::vector<u32>& powers, int stride, int m) {
        if (hi - lo == 1) return emit(h);
        const int mid = (lo + hi) / 2;
        Poly u;
        if ((mid - lo) * (h.n - 1) <= m) {
            u = shifted(vh, roots[lo]);
            for (int i = lo + 1; i < mid; ++i) u = R_.multiply_remainder(u, shifted(vh, roots[i]), h);
        } else {
            alignas(32) u32 product[kCap] = {};
            product[0] = F_.one;
            for (int i = lo; i < mid; ++i) {
                const u32 c = F_.neg(roots[i]);
                for (int j = i - lo + 1; j > 0; --j) product[j] = F_.add(product[j - 1], F_.mul(product[j], c));
                product[0] = F_.mul(product[0], c);
            }
            combine(F_, u.c, m, nullptr, product, mid - lo + 1, powers.data(), stride);
            u.n = m;
            u.trim();
            u = R_.remainder(u, h);
        }
        const Poly left = R_.gcd(h, u), right = R_.quotient(h, left);
        extract(left, R_.remainder(vh, left), roots, lo, mid, powers, stride, m);
        extract(right, R_.remainder(vh, right), roots, mid, hi, powers, stride, m);
    }

    // u - c.
    Poly shifted(Poly u, u32 c) const {
        u.c[0] = F_.sub(u.c[0], c);
        u.n = std::max(u.n, 1);
        u.trim();
        return u;
    }

    void split_by_powers(const Modulus& M, const Kernel& B) {
        const int k = int(B.free.size());
        std::vector<Poly> pieces{M.g};
        while (int(pieces.size()) < k) {
            const Poly v = random_element(M, B);
            for (std::size_t i = 0, count = pieces.size(); i < count; ++i) {
                const Poly h = pieces[i];
                if (h.n <= 4) continue;  // degree <= 3 without roots: irreducible
                const Poly u = R_.remainder(v, h);
                if (u.n <= 1) continue;
                Poly w = R_.power(u, (F_.p - 1) / 2, R_.modulus(h));
                w.c[0] = F_.sub(w.c[0], F_.one);
                w.n = std::max(w.n, 1);
                w.trim();
                const Poly d = R_.gcd(h, w);
                if (d.n > 1 && d.n < h.n) pieces[i] = d, pieces.push_back(R_.quotient(h, d));
            }
        }
        for (const Poly& h : pieces) emit(h);
    }
};

}  // namespace factor
// problems/polynomial/factorization_of_polynomials/gf2.hpp
// Factorization over F_2 for degree <= 100: polynomials are bit masks (bit i = coefficient of
// x^i) in 128 bits. Square-free decomposition as for odd p, then Berlekamp: Q rows x^(2 j) mod g,
// the kernel of Q - I by elimination on bit rows, and refinement of the pieces by gcd(h, b) for
// every kernel vector b (the kernel separates every pair of factors).

#include <immintrin.h>

#include <cstdint>
#include <utility>
#include <vector>


namespace factor::gf2 {

using u128 = unsigned __int128;

inline int degree(u128 a) {
    const u64 high = u64(a >> 64), low = u64(a);
    return high ? 127 - __builtin_clzll(high) : low ? 63 - __builtin_clzll(low) : -1;
}
inline bool bit(u128 a, int i) { return (a >> i) & 1; }

inline u128 remainder(u128 a, u128 b) {
    const int db = degree(b);
    for (int da = degree(a); da >= db; da = degree(a)) a ^= b << (da - db);
    return a;
}
inline u128 quotient(u128 a, u128 b) {
    const int db = degree(b);
    u128 q = 0;
    for (int da = degree(a); da >= db; da = degree(a)) a ^= b << (da - db), q |= u128(1) << (da - db);
    return q;
}
inline u128 gcd(u128 a, u128 b) {
    while (b) a = remainder(a, b), std::swap(a, b);
    return a;
}

inline constexpr u64 kEven = 0x5555555555555555ull;

inline u128 derivative(u128 f) { return (f >> 1) & ((u128(kEven) << 64) | kEven); }

// g with g(x^2) = f (f has only even exponents): g = sqrt(f).
inline u128 square_root(u128 f) {
#ifdef __BMI2__
    return u128(_pext_u64(u64(f), kEven)) | u128(_pext_u64(u64(f >> 64), kEven)) << 32;
#else
    u128 g = 0;
    for (int i = 0; 2 * i < 128; ++i) g |= u128(bit(f, 2 * i)) << i;
    return g;
#endif
}

class Factorizer {
public:
    std::vector<Factor> run(const std::vector<u32>& f) {
        u128 g = 0;
        for (std::size_t i = 0; i < f.size(); ++i) g |= u128(f[i]) << i;
        square_free(g, 1);
        return std::move(factors_);
    }

private:
    std::vector<Factor> factors_;

    void emit(u128 g, u64 multiplicity) {
        Factor f{multiplicity, std::vector<u32>(degree(g) + 1)};
        for (std::size_t i = 0; i < f.coefficients.size(); ++i) f.coefficients[i] = bit(g, int(i));
        factors_.push_back(std::move(f));
    }

    void square_free(u128 f, u64 multiplicity) {
        const u128 df = derivative(f);
        if (df == 0) return square_free(square_root(f), 2 * multiplicity);
        u128 c = gcd(f, df), w = quotient(f, c);
        for (u64 i = 1; degree(w) > 0; ++i) {
            const u128 y = gcd(w, c), z = quotient(w, y);
            if (degree(z) > 0) factor_square_free(z, multiplicity * i);
            w = y;
            c = quotient(c, y);
        }
        if (degree(c) > 0) square_free(square_root(c), 2 * multiplicity);
    }

    void factor_square_free(u128 g, u64 multiplicity) {
        const int m = degree(g);
        if (m == 1) return emit(g, multiplicity);
        // Row i of A = (Q - I)^T: bit j is coefficient i of x^(2 j) mod g, minus [i = j].
        std::vector<u128> A(m, 0);
        u128 q = 1;
        for (int j = 0; j < m; ++j) {
            for (int i = 0; i < m; ++i) A[i] |= u128(bit(q, i) ^ (i == j)) << j;
            q <<= 2;
            if (bit(q, m + 1)) q ^= g << 1;
            if (bit(q, m)) q ^= g;
        }
        // Reduced row echelon form.
        std::vector<int> pivots, free;
        for (int col = 0; col < m; ++col) {
            const int rank = int(pivots.size());
            int found = rank;
            while (found < m && !bit(A[found], col)) ++found;
            if (found == m) {
                free.push_back(col);
                continue;
            }
            std::swap(A[rank], A[found]);
            for (int i = 0; i < m; ++i)
                if (i != rank && bit(A[i], col)) A[i] ^= A[rank];
            pivots.push_back(col);
        }
        const int k = int(free.size());
        if (k == 1) return emit(g, multiplicity);
        std::vector<u128> pieces{g};
        for (int f = 1; f < k && int(pieces.size()) < k; ++f) {
            u128 b = u128(1) << free[f];
            for (std::size_t t = 0; t < pivots.size(); ++t)
                if (bit(A[t], free[f])) b |= u128(1) << pivots[t];
            for (std::size_t i = 0, count = pieces.size(); i < count; ++i) {
                const u128 h = pieces[i];
                if (degree(h) <= 1) continue;
                const u128 d = gcd(h, remainder(b, h));
                if (degree(d) > 0 && degree(d) < degree(h)) pieces[i] = d, pieces.push_back(quotient(h, d));
            }
        }
        for (const u128 h : pieces) emit(h, multiplicity);
    }
};

}  // namespace factor::gf2

namespace {

void solve() {
    io::Reader in;
    io::Writer out;
    const auto n = in.read<std::uint32_t>();
    const auto p = in.read<std::uint32_t>();
    std::vector<std::uint32_t> f(n + 1);
    for (auto& a : f) a = in.read<std::uint32_t>();
    std::vector<factor::Factor> factors;
    if (n > 0) factors = p == 2 ? factor::gf2::Factorizer().run(f) : factor::OddFactorizer(p).run(f);
    out.write(factors.size(), '\n');
    for (const auto& g : factors) {
        out.write(g.multiplicity, ' ', g.coefficients.size() - 1);
        for (const auto b : g.coefficients) out.write(' ', b);
        out.write('\n');
    }
}

}  // namespace

RUN_EARLY(solve)
