// The roots in F_p of f, deg f = N <= 4000, p = 998244353 = 119 2^23 + 1, by tangent Graeffe
// transforms (Grenet, van der Hoeven and Lecerf) in one round:
// - g = f(x + t) for a random t with g(0) != 0, and k Graeffe steps on (g, g') (graeffe.hpp): a
//   root r of g becomes r^N, N = 2^k, so the roots in F_p land in the subgroup H of order
//   (p - 1) / N = 119 2^l.
// - A_k on H: a simple zero z gives its root z A'(z) / B(z) (B scaled by 1 / N). A multiple zero
//   (colliding or repeated roots) climbs: its preimages under x -> x^(2^e) are the candidates at
//   a finer saved level, and at level 0 the candidates that are zeros of g are roots.
// Design and log: notes.md.
#include <algorithm>
#include <bit>
#include <cstddef>
#include <cstdint>
#include <span>
#include <vector>

#include "lib/io/io.hpp"
#include "lib/run/early.hpp"
#include "problems/polynomial/polynomial_root_finding/graeffe.hpp"

namespace {

using u32 = std::uint32_t;
using u64 = std::uint64_t;
using poly::Arena;
using poly::Transform;
using roots::detail::Vec;

constexpr u32 kP = poly::kModulus;
constexpr u32 kOrder = kP - 1;  // of F_p^*, generated by 3; points are kept as exponents of 3
constexpr int kTwoAdic = 23;     // kOrder = 119 2^23
constexpr int kClimb = 8;        // levels per climb: 2^8 candidates per multiple zero

u32 mul(u32 a, u32 b) { return u32(u64(a) * b % kP); }
u32 add(u32 a, u32 b) { return a + b >= kP ? a + b - kP : a + b; }
u32 inverse(u32 a) { return ntt::detail::power(a, kP - 2); }
u32 montgomery_form(u32 a) { return u32((u64(a) << 32) % kP); }

// a b / 2^32 mod P.
u32 mont(u32 a, u32 b) {
    const u64 t = u64(a) * b, m = u32(t) * u64(ntt::kernels::kNI) % (u64(1) << 32);
    const u32 r = u32((t + m * kP) >> 32);
    return r >= kP ? r - kP : r;
}

// l for degree d: d + 1 <= 8 2^l, so about 8 points of H per root and few collisions.
int subgroup_log(std::size_t d) { return std::max(0, int(std::bit_width(d)) - 3); }

class RootFinder {
public:
    explicit RootFinder(std::size_t d_max)
        : arena_(words(d_max)),
          t_(arena_, log_max(d_max)),
          graeffe_(t_, arena_, d_max),
          cosets_(t_, arena_, d_max, zeros_log(d_max)) {
        const std::size_t n = d_max + 1, m = shift_length(d_max);
        f_ = arena_.take(n), g_ = arena_.take(n), b_ = arena_.take(n), x_ = arena_.take(n), g0_ = arena_.take(n);
        for (auto& level : levels_) level = {arena_.take(n), arena_.take(n)};
        const std::size_t count = (n + 7) / 8 * 8;
        fact_ = arena_.take(count), inv_fact_ = arena_.take(count);
        work_ = arena_.take(m), work2_ = arena_.take(m);
        tracked_ = arena_.take(n), next_ = arena_.take(n);
        found_x_ = arena_.take(n), found_b_ = arena_.take(n), prefix_ = arena_.take(n);
        const std::size_t z = 8 << zeros_log(d_max);
        zero_q_ = arena_.take(z), zero_mask_ = arena_.take(z);
        factorials(count);
        const u32 u = ntt::detail::power(3, 1u << kTwoAdic);  // order 119
        for (u32 c = 0, x = montgomery_form(1); c < 120; ++c, x = mul(x, u)) coset_[c] = x;
        power3_[0] = montgomery_form(3);
        for (int i = 1; i < 30; ++i) power3_[i] = mont(power3_[i - 1], power3_[i - 1]);
    }

    // Appends the distinct roots of f: d + 1 coefficients, f[0] != 0, f[d] != 0, d >= 2.
    void solve(std::span<const u32> f, std::vector<u32>& roots) {
        d_ = f.size() - 1;
        std::copy(f.begin(), f.end(), f_.begin());
        u32 shift = next_shift();
        while (!shift_by(shift)) {  // f(shift) = 0
            roots.push_back(shift);
            while (d_ > 0 && horner(shift) == 0) divide_linear(shift);
            if (d_ < 2) {
                if (d_ == 1) roots.push_back(mul(kP - f_[0], inverse(f_[1])));
                return;
            }
            shift = next_shift();
        }
        shift_ = shift, found_ = 0;
        const std::size_t d = d_;
        const int l = subgroup_log(d), k = kTwoAdic - l;
        std::copy_n(g_.data(), d + 1, g0_.data());
        poly::derivative(g_.first(d + 1), b_.first(d));
        // Climbs of at most kClimb levels, the longer ones first: k, ..., 0.
        roots::Save saves[2];
        const int stages = (k + kClimb - 1) / kClimb, count = stages + 1;
        int levels[4] = {k};
        for (int s = 1; s <= stages; ++s) {
            levels[s] = levels[s - 1] - (levels[s - 1] + stages - s) / (stages - s + 1);
            if (s < stages) saves[s - 1] = {levels[s], levels_[s - 1].a.data(), levels_[s - 1].b.data()};
        }
        const int saved = stages - 1;
        graeffe_.run(g_.first(d + 1), b_.first(d), k, std::span<const roots::Save>(saves, std::size_t(saved)));
        tracked_count_ = 0;
        on_subgroup(l);
        for (int i = 1; i < count && tracked_count_ > 0; ++i) {
            const int level = levels[i], climb = levels[i - 1] - level;
            if (level > 0) {
                const Iterate& it = levels_[i - 1];
                climb_to(it.a.first(d + 1), it.b.first(d), climb, roots);
            } else {
                climb_to(g0_.first(d + 1), {}, climb, roots);
            }
        }
        extract(roots);
    }

private:
    struct Iterate {
        std::span<u32> a, b;
    };

    static int zeros_log(std::size_t d_max) { return std::max(kClimb, subgroup_log(d_max)); }
    static std::size_t shift_length(std::size_t d) { return std::max<std::size_t>(64, std::bit_ceil(2 * d + 1)); }
    static int log_max(std::size_t d_max) {
        return std::max({std::countr_zero(2 * roots::graeffe_length(d_max)), std::countr_zero(shift_length(d_max)),
                         zeros_log(d_max) + 3});
    }

    static std::size_t words(std::size_t d_max) {
        const std::size_t len = roots::graeffe_length(d_max), n = d_max + 1, z = std::size_t(1) << zeros_log(d_max);
        std::size_t w = Transform::words(log_max(d_max));
        w += 2 * Arena::footprint(2 * len) + 2 * Arena::footprint(len);  // Graeffe
        w += 3 * Arena::footprint(n + z) + 3 * Arena::footprint(std::max<std::size_t>(64, 8 * z)) +
             Arena::footprint(16 * (n + 1)) + Arena::footprint(48 * z) + 2 * Arena::footprint(z);  // CosetZeros
        w += 16 * Arena::footprint(n) + 2 * Arena::footprint(shift_length(d_max)) + 2 * Arena::footprint(8 * z);
        return w + 4096;
    }

    u32 next_shift() {
        state_ += 0x9E3779B97F4A7C15ull;
        u64 z = state_;
        z = (z ^ (z >> 30)) * 0xBF58476D1CE4E5B9ull;
        z = (z ^ (z >> 27)) * 0x94D049BB133111EBull;
        return u32((z ^ (z >> 31)) % (kP - 1)) + 1;
    }

    u32 horner(u32 x) const {
        u32 r = 0;
        for (std::size_t i = d_ + 1; i-- > 0;) r = add(mul(r, x), f_[i]);
        return r;
    }

    // f = f / (x - a) for a root a.
    void divide_linear(u32 a) {
        for (std::size_t i = d_; i > 0; --i) f_[i - 1] = add(f_[i - 1], mul(a, f_[i]));
        std::copy(f_.begin() + 1, f_.begin() + std::ptrdiff_t(d_) + 1, f_.begin());
        --d_;
    }

    // g = f(x + s) by one product: g_k k! = sum_i f_i i! s^(i-k) / (i-k)!. False if g(0) = 0.
    bool shift_by(u32 s) {
        using namespace roots::detail;
        using poly::detail::load_unaligned, poly::detail::store_unaligned;
        const std::size_t d = d_, m = shift_length(d), full = (d + 1) / 8 * 8;
        const u32 *const f = f_.data(), *const fact = fact_.data(), *const inv = inv_fact_.data();
        u32 *const x = work_.data(), *const y = work2_.data(), *const g = g_.data();
        const auto times = [](Vec a, const u32* b) { return reduce(montgomery(a, load(b)), kP); };
        for (std::size_t i = 0; i < full; i += 8) store_unaligned(x + i, times(load_unaligned(f + i), fact + i));
        for (std::size_t i = full; i <= d; ++i) x[i] = mont(f[i], fact[i]);
        // y[d - j] = s^j / j!, eight powers at a time.
        alignas(32) u32 powers[8];
        powers[0] = 1;
        for (int i = 1; i < 8; ++i) powers[i] = mul(powers[i - 1], s);
        const Vec step = broadcast(montgomery_form(mul(powers[7], s)));
        const Vec reverse = _mm256_setr_epi32(7, 6, 5, 4, 3, 2, 1, 0);
        Vec p = load(powers);
        for (std::size_t j = 0; j < full; j += 8, p = reduce(montgomery(p, step), kP))
            store_unaligned(y + d - j - 7, _mm256_permutevar8x32_epi32(times(p, inv + j), reverse));
        store(powers, p);
        for (std::size_t j = full; j <= d; ++j) y[d - j] = mont(powers[j - full], inv[j]);
        t_.forward(std::span<const u32>(x, d + 1), 0, work_.first(m));
        t_.cyclic_product(std::span<const u32>(y, d + 1), 0, work2_.first(m), work_.first(m));
        for (std::size_t k = 0; k < full; k += 8) store_unaligned(g + k, times(load_unaligned(y + d + k), inv + k));
        for (std::size_t k = full; k <= d; ++k) g[k] = mont(y[d + k], inv[k]);
        return g[0] != 0;
    }

    // fact_[i] = i! 2^32 and inv_fact_[i] = 2^32 / i! for i < count (a multiple of 8): blocks of 8
    // lanes from in-vector prefix (suffix) products and a scalar chain over the blocks.
    void factorials(std::size_t count) {
        using namespace roots::detail;
        const Vec one = broadcast(kR), all = broadcast(~0u), none = _mm256_setzero_si256();
        // x times x with its lanes moved by index, the lanes in mask taken as 1.
        const auto times_moved = [one](Vec x, Vec index, Vec mask) {
            return reduce(montgomery(x, _mm256_blendv_epi8(_mm256_permutevar8x32_epi32(x, index), one, mask)), kP);
        };
        const auto prefix = [&](Vec x) {
            x = times_moved(x, _mm256_setr_epi32(0, 0, 1, 2, 3, 4, 5, 6), _mm256_setr_epi32(~0, 0, 0, 0, 0, 0, 0, 0));
            x = times_moved(x, _mm256_setr_epi32(0, 0, 0, 1, 2, 3, 4, 5), _mm256_blend_epi32(none, all, 0x03));
            return times_moved(x, _mm256_setr_epi32(0, 0, 0, 0, 0, 1, 2, 3), _mm256_blend_epi32(none, all, 0x0F));
        };
        const auto suffix = [&](Vec x) {
            x = times_moved(x, _mm256_setr_epi32(1, 2, 3, 4, 5, 6, 7, 7), _mm256_blend_epi32(none, all, 0x80));
            x = times_moved(x, _mm256_setr_epi32(2, 3, 4, 5, 6, 7, 7, 7), _mm256_blend_epi32(none, all, 0xC0));
            return times_moved(x, _mm256_setr_epi32(4, 5, 6, 7, 7, 7, 7, 7), _mm256_blend_epi32(none, all, 0xF0));
        };
        // fact[8i + l] = (8i)! (8i + 1) ... (8i + l).
        u32 carry = kR;  // (8i)! 2^32
        poly::detail::Indices index(0);
        for (std::size_t i = 0; i < count; i += 8, index.next()) {
            const Vec block = prefix(_mm256_blend_epi32(index.value(), one, 0x01));
            store(fact_.data() + i, reduce(montgomery(block, broadcast(carry)), kP));
            carry = mont(fact_[i + 7], montgomery_form(u32(i + 8)));
        }
        // inv_fact[8i + l] = inv_fact[8i + 7] (8i + l + 1) ... (8i + 7).
        u32 top = montgomery_form(inverse(mont(fact_[count - 1], 1)));
        Vec up = poly::detail::Indices(count - 7).value();  // (i + 1, ..., i + 8) 2^32
        const Vec down = broadcast(kP - montgomery_form(8));
        for (std::size_t i = count - 8;; i -= 8, up = reduce(roots::detail::add(up, down), kP)) {
            const Vec block = suffix(_mm256_blend_epi32(up, one, 0x80));
            store(inv_fact_.data() + i, reduce(montgomery(block, broadcast(top)), kP));
            if (i == 0) break;
            top = mont(inv_fact_[i], montgomery_form(u32(i)));
        }
    }

    // Zeros of A_k (in g_, B in b_) on H, in 15 groups of 8 of its 119 cosets u^c W.
    void on_subgroup(int l) {
        using namespace roots::detail;
        const std::size_t d = d_;
        for (std::size_t i = 0; i <= d; ++i) x_[i] = mul(g_[i], u32(i));
        const std::span<const u32> polys[3] = {g_.first(d + 1), x_.first(d + 1), b_.first(d)};
        cosets_.prepare(polys, 3, d + 1, l);
        const u32 step = kOrder >> l;  // exponent of w
        for (int group = 0; group < 15; ++group) {
            cosets_.evaluate(7, load(coset_ + 8 * group));
            const unsigned valid = group == 14 ? 0x7F : 0xFF;
            for (std::size_t q = 0; q < cosets_.points(); ++q) {
                unsigned mask = zero_mask(cosets_.value(0, q)) & valid;
                if (!mask) continue;
                alignas(32) u32 x[8], b[8];
                store(x, cosets_.value(1, q)), store(b, cosets_.value(2, q));
                for (; mask; mask &= mask - 1) {
                    const int lane = std::countr_zero(mask);
                    if (x[lane] != 0) {
                        record(x[lane], b[lane]);
                        continue;
                    }
                    const u32 e = (u32(8 * group + lane) << kTwoAdic) + u32(cosets_.reverse(q)) * step;
                    tracked_[tracked_count_++] = e >= kOrder ? e - kOrder : e;
                }
            }
        }
    }

    // The tracked points (exponents, multiples of 2^climb) to their 2^climb-th roots: a, b the
    // iterate there, or b empty for level 0, where every zero of a = g is a root. A tracked
    // point whose candidates hold one zero sends all its roots there: a multiple zero again.
    void climb_to(std::span<const u32> a, std::span<const u32> b, int climb, std::vector<u32>& roots) {
        using namespace roots::detail;
        const std::size_t d = d_, count = tracked_count_;
        const bool last = b.empty();
        if (last) {
            const std::span<const u32> polys[1] = {a};
            cosets_.prepare(polys, 1, d + 1, climb);
        } else {
            for (std::size_t i = 0; i <= d; ++i) x_[i] = mul(a[i], u32(i));
            const std::span<const u32> polys[3] = {a, x_.first(d + 1), b};
            cosets_.prepare(polys, 3, d + 1, climb);
        }
        std::copy_n(tracked_.data(), count, next_.data());
        tracked_count_ = 0;
        const u32 step = kOrder >> climb;
        for (std::size_t first = 0; first < count; first += 8) {
            alignas(32) u32 base[8] = {}, value[8];
            const std::size_t lanes = std::min<std::size_t>(8, count - first);
            for (std::size_t i = 0; i < lanes; ++i) base[i] = next_[first + i] >> climb;
            const Vec v = power3(load(base));
            cosets_.evaluate(1, v);
            const unsigned valid = (1u << lanes) - 1;
            std::size_t zeros = 0;
            int per_lane[8] = {};
            for (std::size_t q = 0; q < cosets_.points(); ++q) {
                const unsigned mask = zero_mask(cosets_.value(0, q)) & valid;
                if (!mask) continue;
                zero_q_[zeros] = u32(q), zero_mask_[zeros++] = mask;
                for (unsigned m = mask; m; m &= m - 1) ++per_lane[std::countr_zero(m)];
            }
            if (last) {
                store(value, reduce(montgomery(v, broadcast(1)), kP));
                for (std::size_t z = 0; z < zeros; ++z)
                    for (unsigned m = zero_mask_[z]; m; m &= m - 1)
                        roots.push_back(add(mul(value[std::countr_zero(m)], cosets_.root(zero_q_[z])), shift_));
                continue;
            }
            const bool split = std::any_of(per_lane, per_lane + 8, [](int c) { return c > 1; });
            if (split) cosets_.evaluate(6, v);
            for (std::size_t z = 0; z < zeros; ++z) {
                const std::size_t q = zero_q_[z];
                alignas(32) u32 x[8] = {}, y[8] = {};
                if (split) store(x, cosets_.value(1, q)), store(y, cosets_.value(2, q));
                for (unsigned m = zero_mask_[z]; m; m &= m - 1) {
                    const int lane = std::countr_zero(m);
                    if (per_lane[lane] > 1 && x[lane] != 0) {
                        record(x[lane], y[lane]);
                        continue;
                    }
                    tracked_[tracked_count_++] = base[lane] + u32(cosets_.reverse(q)) * step;
                }
            }
        }
    }

    // Lanes of x that are zero.
    static unsigned zero_mask(Vec x) {
        return unsigned(_mm256_movemask_ps(_mm256_castsi256_ps(_mm256_cmpeq_epi32(x, _mm256_setzero_si256()))));
    }

    // 3^e in Montgomery form, lane by lane, e < 2^30.
    Vec power3(Vec e) const {
        using namespace roots::detail;
        Vec r = broadcast(kR);
        const Vec one = broadcast(1);
        for (int i = 0; i < 30; ++i) {
            const Vec bit = _mm256_cmpeq_epi32(_mm256_and_si256(_mm256_srli_epi32(e, i), one), one);
            const Vec product = reduce(montgomery(r, broadcast(power3_[i])), kP);
            r = _mm256_blendv_epi8(r, product, bit);
        }
        return r;
    }

    void record(u32 x, u32 b) { found_x_[found_] = x, found_b_[found_] = b, ++found_; }

    // root = x / b + shift for the recorded simple zeros, the b inverted together.
    void extract(std::vector<u32>& roots) {
        u32 product = 1;
        for (std::size_t i = 0; i < found_; ++i) prefix_[i] = product, product = mul(product, found_b_[i]);
        u32 inv = inverse(product);  // 1 / (b_0 ... b_i) in the loop
        for (std::size_t i = found_; i-- > 0;) {
            roots.push_back(add(mul(found_x_[i], mul(inv, prefix_[i])), shift_));
            inv = mul(inv, found_b_[i]);
        }
    }

    Arena arena_;
    Transform t_;
    roots::Graeffe graeffe_;
    roots::CosetZeros cosets_;
    std::span<u32> f_, g_, b_, x_, g0_, fact_, inv_fact_, work_, work2_, tracked_, next_, found_x_, found_b_, prefix_;
    std::span<u32> zero_q_, zero_mask_;  // a group's zeros: output and lanes
    Iterate levels_[2];
    std::size_t d_ = 0, tracked_count_ = 0, found_ = 0;
    u32 shift_ = 0;
    u64 state_ = 0x2545F4914F6CDD1Dull;
    alignas(32) u32 coset_[120];  // u^c 2^32, u = 3^(2^23) of order 119
    u32 power3_[30];              // 3^(2^i) 2^32
};

void solve() {
    io::Reader in;
    const std::size_t n = in.read<u32>();
    std::vector<u32> f(n + 1);
    in.read(f.data(), n + 1);
    std::vector<u32> roots;
    roots.reserve(n + 1);
    std::size_t zeros = 0;
    while (f[zeros] == 0) ++zeros;
    if (zeros) roots.push_back(0);
    const std::span<const u32> rest = std::span<const u32>(f).subspan(zeros);
    const std::size_t d = rest.size() - 1;
    if (d == 1) roots.push_back(mul(kP - rest[0], inverse(rest[1])));
    if (d >= 2) {
        RootFinder finder(d);
        finder.solve(rest, roots);
    }
    io::Writer out;
    out.write(u32(roots.size()), '\n');
    out.write_array(roots.data(), roots.size(), ' ');
    out.write('\n');
}

}  // namespace

RUN_EARLY(solve)
