#!/usr/bin/env python3
"""Generate kernels.hpp: lib/ntt's AVX2 kernels with the modulus read at run time.

The kernels of lib/ntt/gen_kernels.py load P, 2P and -1/P mod 2^32 from memory. Here those are
variables, set before each prime's transforms, instead of constants. The instructions are the same.

Usage: gen_kernels.py [--check]   (--check: exit 1 if kernels.hpp differs from the output)
"""
import argparse
import importlib.util
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
OUT = HERE / 'kernels.hpp'

REPLACEMENTS = [
    ('// Generated by lib/ntt/gen_kernels.py. Do not edit.',
     f'// Generated by {HERE.relative_to(ROOT)}/gen_kernels.py from lib/ntt/gen_kernels.py. Do not edit.'),
    ('Arithmetic and ranges: notes.md.', 'Arithmetic and ranges: lib/ntt/notes.md.'),
    ('// Vectors hold 8 residues mod P = 998244353.',
     '// Vectors hold 8 residues mod P, a prime <= 998244353 set at run time.'),
    ('(block table layout, see ntt.hpp)', '(block table layout, see transform.hpp)'),
    ('namespace ntt::kernels', 'namespace multimod::kernels'),
    ('inline constexpr std::uint32_t kP = 998244353, k2P = 2 * kP, kNI = 998244351;  // kNI = -1 / P mod 2^32',
     '// P, 2P and -1 / P mod 2^32: set before each use. The kernels load them from memory.\n'
     'inline std::uint32_t kP, k2P, kNI;'),
]


def generate() -> str:
    spec = importlib.util.spec_from_file_location('lib_ntt_gen_kernels', ROOT / 'lib/ntt/gen_kernels.py')
    lib = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(lib)
    text = lib.generate()
    for old, new in REPLACEMENTS:
        if old not in text:
            sys.exit(f'lib/ntt/gen_kernels.py output changed: missing {old!r}')
        text = text.replace(old, new)
    return text


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    text = generate()
    if args.check:
        if OUT.read_text() != text:
            print(f'{OUT} is stale: run {Path(__file__).name}')
            return 1
        return 0
    OUT.write_text(text)
    return 0


if __name__ == '__main__':
    sys.exit(main())
