#!/usr/bin/env python3
"""Generate bottom.hpp: ntt::Product's bottom stage (lib/ntt/gen_product_kernels.py) in two
variants for two products that share the factor b.

- keep: as product_kernels' bottom_first and bottom_both, and each batch's leaves B_t (the
  forward butterfly's outputs, canonical) also overwrite the batch in b.
- reuse: b already holds the leaves; the forward half copies them to the leaf buffer instead
  of running b's butterfly.
bottom_last is product_kernels' own. Same graphs and scheduler as gen_product_kernels.py; its
knobs for 'first', and for 'both' the nearest ones that schedule (its window of 20 deadlocks).

Usage: gen_bottom.py [--check]   (--check: exit 1 if bottom.hpp differs)
"""
import argparse
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parents[2] / 'lib' / 'ntt'))
import gen_kernels as gk  # noqa: E402
import gen_product_kernels as gpk  # noqa: E402

OUT = HERE / 'bottom.hpp'


def a_half(g):
    """a's butterfly and leaf windows [w_t A_t, A_t], as gen_product_kernels.first."""
    for t, v in enumerate(gk.forward_h1(g, 'a', 'x', 'y')):
        a = g.canonical(v)
        g.store(a, 'buf', None, 64 * t + 32)
        w, q = (0, 32) if t < 2 else (4, 36)
        wa = g.shoup(a, g.scalar('y', w), g.scalar('y', q))
        wa = g.op('vpminud', wa, g.op('vpsubd', wa, g.c['P']))
        if t % 2:
            wa = g.op('vpsubd', g.c['P'], wa)
        g.store(wa, 'buf', None, 64 * t)


def first_keep(g):
    a_half(g)
    for t, v in enumerate(gk.forward_h1(g, 'b', 'x', 'y')):
        b = g.canonical(v)
        g.store(b, 'buf', None, 256 + 32 * t)
        g.store(b, 'b', None, 32 * t)


def first_reuse(g):
    a_half(g)
    for t in range(4):
        g.store(g.at('b', 32 * t, fold=False), 'buf', None, 256 + 32 * t)


FIRST = {'keep': first_keep, 'reuse': first_reuse}
KNOBS = {('first', 'keep'): gpk.KNOBS['first'], ('first', 'reuse'): gpk.KNOBS['first'],
         ('both', 'keep'): gk.Knobs(window=20, margin=1), ('both', 'reuse'): gk.Knobs(window=12)}


def body(part, variant):
    g = gpk.Batch({'P': gk.Value('creg', reg=15), '2P': gk.Value('creg', reg=14), 'NI': gk.Value('creg', reg=13)})
    if part == 'both':
        for m in range(gpk.BATCHES):
            g.offset = {'cur': gpk.LEAVES * m, 'out': 128 * m, 'ix': 4 * m, 'iy': 8 * m}
            gpk.last(g)
    split = len(g.ops)
    for m in range(gpk.BATCHES):
        g.offset = {'a': 128 * m, 'b': 128 * m, 'buf': gpk.LEAVES * m, 'x': 4 * m, 'y': 8 * m}
        FIRST[variant](g)
    ops = g.ops
    if part == 'both':
        older, newer = ops[:split], ops[split:]
        keyed = [(i / len(older), 0, i, o) for i, o in enumerate(older)]
        keyed += [(j / len(newer) + gpk.SHIFT, 1, j, o) for j, o in enumerate(newer)]
        ops = [o for *_, o in sorted(keyed, key=lambda t: t[:3])]
    seq = gk.schedule(ops, 13, KNOBS[part, variant])
    reg = gk.allocate(seq, {13, 14, 15})
    head = ['vpbroadcastd %[P], %%ymm15', 'vpbroadcastd %[P2], %%ymm14', 'vpbroadcastd %[NI], %%ymm13']
    return head + [gk.emit(o, reg) for o in seq]


DOC = {
    ('first', 'keep'): 'product_kernels::bottom_first; also writes the leaves B_t over the batches in b.',
    ('both', 'keep'): 'product_kernels::bottom_both; also writes the next batches\' leaves B_t over them in b.',
    ('first', 'reuse'): 'product_kernels::bottom_first for b holding its leaves B_t: copies them to buf.',
    ('both', 'reuse'): 'product_kernels::bottom_both for b holding its leaves B_t: copies them to buf.',
}


def function(part, variant):
    args = gpk.ARGS[part]
    writable = ('buf', 'out', 'b') if variant == 'keep' else ('buf', 'out')
    params = ', '.join(f'{"void*" if a in writable else "const void*"} {a}' for a in args)
    lines = [f'// {DOC[part, variant]}', f'[[gnu::always_inline]] inline void {part}_{variant}({params}) {{',
             '    asm volatile(']
    lines += gk.asm_lines(body(part, variant))
    lines += ['        :', '        : ' + ', '.join(f'[{a}] "r"({a})' for a in args) + ',',
              '          [P] "m"(kP), [P2] "m"(k2P), [NI] "m"(kNI)',
              '        : ' + gk.CLOBBERS + ');', '}']
    return lines


HEADER = '''\
// Generated by gen_bottom.py. Do not edit.
// ntt::Product's bottom stage (lib/ntt/product_kernels.hpp) for two products with the same
// factor b: the first keeps b's leaves in b (keep), the second reads them there (reuse).
#pragma once

#include "lib/ntt/product_kernels.hpp"

namespace bottom {

using ntt::kernels::k2P;
using ntt::kernels::kNI;
using ntt::kernels::kP;
'''


def generate():
    lines = HEADER.split('\n')
    for variant in ('keep', 'reuse'):
        for part in ('first', 'both'):
            lines += function(part, variant) + ['']
    lines += ['}  // namespace bottom']
    return '\n'.join(lines) + '\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    text = generate()
    if args.check:
        if not OUT.exists() or OUT.read_text() != text:
            print(f'{OUT.name} stale: run {Path(__file__).name}')
            return 1
        return 0
    OUT.write_text(text)
    return 0


if __name__ == '__main__':
    sys.exit(main())
