#!/usr/bin/env python3
"""Writes factorials.hpp next to this script: (1024 k)! mod 998244353 for k <= 512, the starting
points of the factorial scans in solution.cpp (positions up to 2^19 + 1023).

Usage: factorials.py
"""
from pathlib import Path

P = 998244353
STEP = 1024
COUNT = 513


def main() -> None:
    values, f = [], 1
    for k in range(COUNT):
        values.append(f)
        for i in range(STEP * k + 1, STEP * (k + 1) + 1):
            f = f * i % P
    rows = [', '.join(str(v) for v in values[i:i + 8]) for i in range(0, COUNT, 8)]
    body = ',\n    '.join(rows)
    text = f'''// Generated by factorials.py. Do not edit.
// (1024 k)! mod 998244353 for k <= 512.
#pragma once

#include <cstdint>

namespace factorials {{

inline constexpr std::uint32_t kStep = {STEP};
inline constexpr std::uint32_t kTable[{COUNT}] = {{
    {body}}};

}}  // namespace factorials
'''
    (Path(__file__).resolve().parent / 'factorials.hpp').write_text(text)


if __name__ == '__main__':
    main()
