// Generated by tools/bundle.py from problems/convolution/gcd_convolution/solution.cpp. Edit that file instead.
// c_k = sum over gcd(i, j) = k of a_i b_j mod 998244353, 1 <= k <= N <= 10^6.
// Sums over multiples (zeta) of a and b, pointwise product, then the inverse (Moebius). Both are
// products of commuting per-prime passes. Primes 2..13: one pass each (zeta: x_i += x_ip, i
// descending; Moebius: x_i -= x_ip, i ascending). Primes >= 17 together: one sweep over the
// multipliers m coprime to 30030 ("rough"), segment by segment so the sources stay in L2.
// a and b are interleaved as pairs, so one load fetches both.
#include <immintrin.h>
#include <sys/mman.h>

#include <algorithm>
#include <array>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <cstring>

// lib/io/io.hpp
// Fast integer and text I/O on file descriptors (stdin and stdout by default).
// Linux, x86-64 with AVX2. Design and measurements: lib/io/notes.md.
//
//   io::Reader in;                            // takes all of stdin
//   io::Writer out;                           // flushes in its destructor
//   const auto n = in.read<std::uint32_t>();
//   std::vector<std::uint32_t> a(n);
//   in.read(a.data(), n);                     // bulk; AVX2 for uint32_t
//   const auto s = in.read<std::uint64_t, 16>();  // promise: at most 16 digits (faster)
//   out.write("n = ", n, '\n');               // any mix of integers, chars, strings
//   out.write<16>(s, '\n');                   // promise: integers of at most 16 digits
//   out.write_array(a.data(), n, ' ');        // bulk; AVX2 for uint32_t
//   out.write('\n');
//
// Input: tokens separated by whitespace (any bytes <= ' '). Integer tokens are an optional '-'
// (signed types only) followed by decimal digits, and fit the requested type. Reading past the
// last token is undefined. The 64 bytes before the input and after its end are readable zeros, so
// custom parsers may load up to 64 bytes around any token from word().

#include <fcntl.h>
#include <immintrin.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <unistd.h>

#include <algorithm>
#include <array>
#include <bit>
#include <cerrno>
#include <concepts>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <string_view>
#include <type_traits>

namespace io {
namespace detail {

// Zero bytes before and after the input. Loads reach at most 63 bytes past either end.
inline constexpr std::size_t kPadding = 64;
inline constexpr std::size_t kPage = 4096;

// Input as mapped or read: data [start, end), kPadding zero bytes before and after it.
struct Input {
    char* base;           // allocation or mapping to release
    std::size_t mapped;   // bytes mapped, or 0 for a heap buffer
    const char* start;
    const char* end;
};

inline Input map_input(int fd, std::size_t size) {
    const off_t offset = ::lseek(fd, 0, SEEK_CUR);
    if (offset < 0 || std::size_t(offset) >= size) return {};
    // One anonymous zero page before the file. After it, the rest of the last file page reads as
    // zero; if fewer than kPadding bytes remain, one more anonymous page follows.
    const std::size_t file_bytes = (size + kPage - 1) & ~(kPage - 1);
    const std::size_t mapped = kPage + file_bytes + (file_bytes - size < kPadding ? kPage : 0);
    void* base = ::mmap(nullptr, mapped, PROT_READ, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
    if (base == MAP_FAILED) return {};
    char* const file = static_cast<char*>(base) + kPage;
    if (::mmap(file, file_bytes, PROT_READ, MAP_PRIVATE | MAP_FIXED, fd, 0) == MAP_FAILED) {
        ::munmap(base, mapped);
        return {};
    }
    return {static_cast<char*>(base), mapped, file + offset, file + size};
}

// Capacity bytes for data, with kPadding bytes before and after; returns the data start.
inline char* allocate(std::size_t capacity) {
    auto* p = static_cast<char*>(std::aligned_alloc(64, capacity + 2 * kPadding));
    if (!p) std::abort();
    std::memset(p, 0, kPadding);
    return p + kPadding;
}

// Reads fd until end of file, or until size bytes for a regular file of that size.
inline Input read_input(int fd, std::size_t size = std::size_t(-1)) {
    std::size_t done = 0, capacity = std::size_t(1) << 16;
    char* data = allocate(capacity);
    while (done < size) {
        if (done == capacity) {
            char* bigger = allocate(capacity *= 2);
            std::memcpy(bigger, data, done);
            std::free(data - kPadding);
            data = bigger;
        }
        const ssize_t got = ::read(fd, data + done, capacity - done);
        if (got > 0) done += std::size_t(got);
        else if (got == 0) break;
        else if (errno != EINTR) std::abort();
    }
    std::memset(data + done, 0, kPadding);
    return {data - kPadding, 0, data, data + done};
}

// Files over kMapAbove bytes are mapped; smaller ones and other inputs are read, which takes
// fewer system calls.
inline constexpr std::size_t kMapAbove = std::size_t(1) << 16;

inline Input open_input(int fd) {
    struct stat st;
    if (::fstat(fd, &st) == 0 && S_ISREG(st.st_mode)) {
        const auto size = std::size_t(st.st_size);
        if (size <= kMapAbove) return read_input(fd, size);
        if (const Input input = map_input(fd, size); input.base) return input;
    }
    return read_input(fd);
}

inline void release(const Input& input) {
    if (input.mapped) ::munmap(input.base, input.mapped);
    else std::free(input.base);
}

// Bit i set iff byte i is whitespace (<= ' ').
inline unsigned separators(__m128i bytes) {
    return unsigned(_mm_movemask_epi8(_mm_cmpgt_epi8(_mm_set1_epi8(' ' + 1), bytes)));
}

inline std::uint32_t separators(__m256i bytes) {
    return std::uint32_t(_mm256_movemask_epi8(_mm256_cmpgt_epi8(_mm256_set1_epi8(' ' + 1), bytes)));
}

// Separators in the 64-byte aligned block.
inline std::uint64_t block_separators(const char* block) {
    const std::uint64_t low = separators(_mm256_load_si256(reinterpret_cast<const __m256i*>(block)));
    const std::uint64_t high = separators(_mm256_load_si256(reinterpret_cast<const __m256i*>(block + 32)));
    return low | high << 32;
}

// The 16 bytes at kRightAlign[n + 1] move the first n bytes (1 <= n <= 16) of a 16-byte window
// to its end and zero the rest: byte k + 1 is k - 16 for 16 <= k < 32, else -128. For the other
// lengths (-1, 0, 17..32) byte 15 of the window is negative, which marks the token as invalid.
alignas(64) inline constexpr auto kRightAlign = [] {
    std::array<std::int8_t, 64> t{};
    for (int k = -1; k < 63; ++k) t[k + 1] = k >= 16 && k < 32 ? std::int8_t(k - 16) : std::int8_t(-128);
    return t;
}();

// Shuffle control for a token of length index - 1.
inline __m128i align_row(std::size_t index) {
    return _mm_loadu_si128(reinterpret_cast<const __m128i*>(kRightAlign.data() + index));
}

// Right-aligned digits (byte values 0..9) -> 4-digit groups, one per dword.
inline __m128i digit_groups(__m128i digits) {
    return _mm_madd_epi16(_mm_maddubs_epi16(digits, _mm_set1_epi16(0x010A)), _mm_set1_epi32(0x00010064));
}

inline __m256i digit_groups(__m256i digits) {
    return _mm256_madd_epi16(_mm256_maddubs_epi16(digits, _mm256_set1_epi16(0x010A)), _mm256_set1_epi32(0x00010064));
}

// Value of the first n digits (0 <= n <= 16) of the window. Result < 10^16.
inline std::uint64_t parse16(__m128i window, unsigned n) {
    const __m128i digits = _mm_shuffle_epi8(_mm_subs_epu8(window, _mm_set1_epi8('0')), align_row(n + 1));
    const __m128i groups = digit_groups(digits);
    const __m128i halves = _mm_madd_epi16(_mm_packus_epi32(groups, groups), _mm_set1_epi32(0x00012710));
    const auto both = std::uint64_t(_mm_cvtsi128_si64(halves));  // 8-digit halves, high one first
    return (both & 0xFFFFFFFF) * 100000000 + (both >> 32);
}

// kKeep[32 - k..64 - k) keeps the last k bytes of 32.
alignas(64) inline constexpr auto kKeep = [] {
    std::array<std::uint8_t, 64> t{};
    for (std::size_t i = 32; i < 64; ++i) t[i] = 0xFF;
    return t;
}();

// Value of the n <= 16 digits that end at end. Bytes below '0' before them (a sign) count as 0.
inline std::uint64_t parse_ending16(const char* end, unsigned n) {
    const __m128i bytes = _mm_loadu_si128(reinterpret_cast<const __m128i*>(end - 16));
    const __m128i keep = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kKeep.data() + 16 + n));
    const __m128i groups = digit_groups(_mm_and_si128(_mm_subs_epu8(bytes, _mm_set1_epi8('0')), keep));
    const __m128i halves = _mm_madd_epi16(_mm_packus_epi32(groups, groups), _mm_set1_epi32(0x00012710));
    const auto both = std::uint64_t(_mm_cvtsi128_si64(halves));  // 8-digit halves, high one first
    return (both & 0xFFFFFFFF) * 100000000 + (both >> 32);
}

// Value of the n <= 24 digits that end at end; at most 20 for a result below 2^64.
inline std::uint64_t parse_ending24(const char* end, unsigned n) {
    const __m256i bytes = _mm256_loadu_si256(reinterpret_cast<const __m256i*>(end - 32));
    const __m256i keep = _mm256_loadu_si256(reinterpret_cast<const __m256i*>(kKeep.data() + n));
    const __m256i groups = digit_groups(_mm256_and_si256(_mm256_subs_epu8(bytes, _mm256_set1_epi8('0')), keep));
    // 8-digit quarters; the first is 0. Dword 1 of the low lane, dwords 0 and 1 of the high lane.
    const __m256i quarters = _mm256_madd_epi16(_mm256_packus_epi32(groups, groups), _mm256_set1_epi32(0x00012710));
    const std::uint64_t high = std::uint64_t(_mm256_extract_epi64(quarters, 0)) >> 32;
    const auto low = std::uint64_t(_mm256_extract_epi64(quarters, 2));
    return (high * 100000000 + (low & 0xFFFFFFFF)) * 100000000 + (low >> 32);
}

// kQuad[x] for x < 10^4: its 4 digits with leading zeros, first digit in the lowest byte.
alignas(64) inline constexpr auto kQuad = [] {
    std::array<std::uint32_t, 10000> t{};
    for (std::uint32_t x = 0; x < t.size(); ++x)
        t[x] = ('0' + x / 1000) | ('0' + x / 100 % 10) << 8 | ('0' + x / 10 % 10) << 16 | ('0' + x % 10) << 24;
    return t;
}();

// Digits of x (x >= 1) = (x + kDigitCount32[floor(log2(x))]) >> 32: the low word of an entry
// carries into the high word exactly when x reaches the next power of ten.
inline constexpr auto kDigitCount32 = [] {
    std::array<std::uint64_t, 32> t{};
    for (int i = 0; i < 32; ++i) {
        const std::uint64_t low = std::uint64_t(1) << i, high = 2 * low - 1;
        std::uint64_t digits = 0, power = 1;
        while (power <= low) power *= 10, ++digits;
        t[i] = (digits << 32) + (power <= high ? (std::uint64_t(1) << 32) - power : 0);
    }
    return t;
}();

inline unsigned digit_count(std::uint32_t x) {
    return unsigned((x + kDigitCount32[31 - std::countl_zero(x | 1)]) >> 32);
}

// Digits of x = kDigitCount64[0][b] + (x > kDigitCount64[1][b]), where b = bit width of x | 1.
inline constexpr auto kDigitCount64 = [] {
    std::array<std::array<std::uint64_t, 65>, 2> t{};
    for (int b = 1; b <= 64; ++b) {
        const unsigned __int128 low = (unsigned __int128)1 << (b - 1), high = 2 * low - 1;
        std::uint64_t digits = 1;
        unsigned __int128 power = 10;
        while (power <= low) power *= 10, ++digits;
        t[0][b] = digits;
        t[1][b] = power <= high ? std::uint64_t(power - 1) : ~std::uint64_t(0);
    }
    return t;
}();

inline unsigned digit_count(std::uint64_t x) {
    const int b = std::bit_width(x | 1);
    return unsigned(kDigitCount64[0][b] + (x > kDigitCount64[1][b]));
}

// Bytes kShiftWindow[k..k + 16) shuffle a vector down by k bytes.
alignas(32) inline constexpr std::int8_t kShiftWindow[32] = {0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  10,
                                                             11, 12, 13, 14, 15, -1, -1, -1, -1, -1, -1,
                                                             -1, -1, -1, -1, -1, -1, -1, -1, -1, -1};

inline __m128i shift_down(__m128i v, unsigned k) {
    return _mm_shuffle_epi8(v, _mm_loadu_si128(reinterpret_cast<const __m128i*>(kShiftWindow + k)));
}

// Writes x in decimal at p and returns the end. Stores 16 bytes.
inline char* format(char* p, std::uint32_t x) {
    // Twelve digits with leading zeros, as three groups of four, then shifted down past the zeros.
    const std::uint32_t top = x / 100000000, rest = x % 100000000;
    const std::uint32_t high = rest / 10000, low = rest % 10000;
    const __m128i digits = _mm_insert_epi32(
        _mm_cvtsi64_si128(std::int64_t(kQuad[top] | std::uint64_t(kQuad[high]) << 32)), int(kQuad[low]), 2);
    const unsigned n = digit_count(x);
    _mm_storeu_si128(reinterpret_cast<__m128i*>(p), shift_down(digits, 12 - n));
    return p + n;
}

// high, low < 10^8 as 16 digits with leading zeros.
inline __m128i sixteen_digits(std::uint32_t high, std::uint32_t low) {
    return _mm_set_epi64x(std::int64_t(kQuad[low / 10000] | std::uint64_t(kQuad[low % 10000]) << 32),
                          std::int64_t(kQuad[high / 10000] | std::uint64_t(kQuad[high % 10000]) << 32));
}

// Writes x in decimal at p and returns the end. Stores up to 20 bytes. MaxDigits <= 16 promises
// x < 10^16, which saves a division.
template <int MaxDigits>
inline char* format64(char* p, std::uint64_t x) {
    const std::uint64_t q = x / 100000000;  // < 1.9 * 10^11
    const auto low = std::uint32_t(x - q * 100000000);
    const unsigned n = digit_count(x);
    if constexpr (MaxDigits <= 16) {
        _mm_storeu_si128(reinterpret_cast<__m128i*>(p), shift_down(sixteen_digits(std::uint32_t(q), low), 16 - n));
        return p + n;
    } else {
        // Twenty digits with leading zeros: a head of four, then sixteen.
        const auto top = std::uint32_t(q / 100000000);  // < 1845
        const auto middle = std::uint32_t(q - std::uint64_t(top) * 100000000);
        const unsigned head = n > 16 ? n - 16 : 0;
        const auto head_digits = std::uint32_t(std::uint64_t(kQuad[top]) >> (32 - 8 * head));
        std::memcpy(p, &head_digits, 4);
        _mm_storeu_si128(reinterpret_cast<__m128i*>(p + head), shift_down(sixteen_digits(middle, low), 16 - (n - head)));
        return p + n;
    }
}

// floor(x / d) for every dword x, as (x * Magic) >> Shift. The test checks each use exhaustively.
template <std::uint32_t Magic, int Shift>
inline __m256i divide(__m256i x) {
    const __m256i magic = _mm256_set1_epi64x(Magic);
    const __m256i even = _mm256_srli_epi64(_mm256_mul_epu32(x, magic), Shift);
    const __m256i odd = _mm256_srli_epi64(_mm256_mul_epu32(_mm256_srli_epi64(x, 32), magic), Shift);
    return _mm256_blend_epi32(even, _mm256_slli_epi64(odd, 32), 0xAA);
}

// Each dword g < 10^4 -> its 4 ASCII digits, first digit in the lowest byte.
inline __m256i quad_digits(__m256i g) {
    const __m256i high = _mm256_srli_epi16(_mm256_mulhi_epu16(g, _mm256_set1_epi16(5243)), 3);  // g / 100
    const __m256i low = _mm256_sub_epi16(g, _mm256_mullo_epi16(high, _mm256_set1_epi16(100)));
    const __m256i pairs = _mm256_or_si256(high, _mm256_slli_epi32(low, 16));  // 16-bit halves < 100
    const __m256i tens = _mm256_mulhi_epu16(pairs, _mm256_set1_epi16(6554));  // pair / 10
    const __m256i units = _mm256_sub_epi16(pairs, _mm256_mullo_epi16(tens, _mm256_set1_epi16(10)));
    return _mm256_or_si256(_mm256_or_si256(tens, _mm256_slli_epi16(units, 8)), _mm256_set1_epi8('0'));
}

// Digit counts of the eight dwords of v, one per byte in order.
inline std::uint64_t digit_counts(__m256i v) {
    // Unsigned v >= 10^k via a signed compare after flipping the sign bits; summed as a tree.
    const __m256i x = _mm256_xor_si256(v, _mm256_set1_epi32(int(0x80000000)));
    const auto at_least = [&](std::uint32_t power) {
        return _mm256_cmpgt_epi32(x, _mm256_set1_epi32(int((power - 1) ^ 0x80000000)));
    };
    const __m256i a = _mm256_add_epi32(_mm256_add_epi32(at_least(10), at_least(100)),
                                       _mm256_add_epi32(at_least(1000), at_least(10000)));
    const __m256i b = _mm256_add_epi32(_mm256_add_epi32(at_least(100000), at_least(1000000)),
                                       _mm256_add_epi32(at_least(10000000), at_least(100000000)));
    const __m256i n = _mm256_sub_epi32(_mm256_sub_epi32(_mm256_set1_epi32(1), at_least(1000000000)),
                                       _mm256_add_epi32(a, b));
    const __m256i bytes = _mm256_packus_epi16(_mm256_packus_epi32(n, n), n);  // per lane: 4 counts first
    return std::uint64_t(_mm256_extract_epi32(bytes, 0)) | std::uint64_t(_mm256_extract_epi32(bytes, 4)) << 32;
}

// Stores the two 16-byte lanes of w, values of 12 digits with leading zeros and a separator, as
// their last n0 and n1 digits and the separator. Returns the end; stores 16 bytes per lane.
inline char* put_pair(char* p, __m256i w, unsigned n0, unsigned n1) {
    const __m256i shifted = _mm256_shuffle_epi8(w, _mm256_loadu2_m128i(
        reinterpret_cast<const __m128i*>(kShiftWindow + 12 - n1), reinterpret_cast<const __m128i*>(kShiftWindow + 12 - n0)));
    _mm_storeu_si128(reinterpret_cast<__m128i*>(p), _mm256_castsi256_si128(shifted));
    p += n0 + 1;
    _mm_storeu_si128(reinterpret_cast<__m128i*>(p), _mm256_extracti128_si256(shifted, 1));
    return p + n1 + 1;
}

// Writes the eight dwords of v in decimal, each followed by separator, and returns the end.
// Stores up to 15 bytes past the end.
inline char* format8(char* p, __m256i v, char separator) {
    // Digit counts first, from v: the store addresses then do not wait for the digits.
    const std::uint64_t n = digit_counts(v);
    // Lanes [v0 v2 v4 v6 | v1 v3 v5 v7], so the transpose below pairs consecutive values.
    v = _mm256_permutevar8x32_epi32(v, _mm256_setr_epi32(0, 2, 4, 6, 1, 3, 5, 7));
    const __m256i top = divide<1441151881, 57>(v);  // v / 10^8
    const __m256i rest = _mm256_sub_epi32(v, _mm256_mullo_epi32(top, _mm256_set1_epi32(100000000)));
    const __m256i high = divide<3518437209, 45>(rest);  // rest / 10^4
    const __m256i low = _mm256_sub_epi32(rest, _mm256_madd_epi16(high, _mm256_set1_epi32(10000)));
    const __m256i t = quad_digits(top), h = quad_digits(high), l = quad_digits(low);
    const __m256i s = _mm256_set1_epi32(static_cast<unsigned char>(separator));
    // Transpose: each 16-byte lane becomes one value as dwords [top, high, low, separator].
    const __m256i th_low = _mm256_unpacklo_epi32(t, h), th_high = _mm256_unpackhi_epi32(t, h);
    const __m256i ls_low = _mm256_unpacklo_epi32(l, s), ls_high = _mm256_unpackhi_epi32(l, s);
    const auto count = [n](int i) { return unsigned(n >> 8 * i & 0xFF); };
    p = put_pair(p, _mm256_unpacklo_epi64(th_low, ls_low), count(0), count(1));
    p = put_pair(p, _mm256_unpackhi_epi64(th_low, ls_low), count(2), count(3));
    p = put_pair(p, _mm256_unpacklo_epi64(th_high, ls_high), count(4), count(5));
    return put_pair(p, _mm256_unpackhi_epi64(th_high, ls_high), count(6), count(7));
}

// Parses uint32 tokens from the token at p into dst: at most count, from input that is valid up
// to limit. Stops when fewer than kMinTokens tokens or 1 KiB of input remain. Returns where it
// stopped and the tokens parsed. Each chunk of input is cut
// into four streams at token boundaries. The streams advance in lockstep, two tokens per step, so
// four independent pointer chains overlap.
class BulkParser {
public:
    static constexpr std::size_t kMinTokens = 1024;

    struct Result {
        const char* end;
        std::size_t parsed;
    };

    static Result parse(const char* p, const char* limit, std::uint32_t* dst, std::size_t count) {
        std::uint32_t* const first = dst;
        while (count >= kMinTokens && limit - p >= 1024 + 64) {
            // With tokens of at most 16 bytes a chunk spans at most chunk + 33 bytes, so it holds
            // at most chunk / 2 + 17 < count tokens: all of them belong to this array. It ends
            // before limit.
            const std::size_t chunk =
                std::min({kChunk, 2 * (count - 32), std::size_t(limit - p) - 64}) & ~std::size_t(3);
            const std::size_t stream = chunk / 4;
            const char* s[4] = {p, after_separator(p + stream), after_separator(p + 2 * stream),
                                after_separator(p + 3 * stream)};
            const char* const end[4] = {s[1], s[2], s[3], after_separator(p + chunk)};
            std::uint32_t* const out[4] = {dst, scratch_[0], scratch_[1], scratch_[2]};
            __m256i invalid = _mm256_setzero_si256();
            const std::size_t done = lockstep(s, end, out, invalid);
            std::size_t n[4];
            bool overrun = false;
            for (int k = 0; k < 4; ++k) {
                n[k] = done;
                while (s[k] < end[k] && n[k] < kCapacity) out[k][n[k]++] = one_token(s[k], invalid);
                overrun |= s[k] != end[k];
            }
            if (overrun || (std::uint32_t(_mm256_movemask_epi8(invalid)) & 0x80008000)) [[unlikely]] {
                // Irregular whitespace or tokens: this chunk one token at a time.
                const std::size_t tokens = std::min(count_tokens(p, end[3]), count);
                p = parse_slowly(p, dst, tokens);
                dst += tokens;
                count -= tokens;
                continue;
            }
            std::uint32_t* next = dst + n[0];
            for (int k = 1; k < 4; ++k) {
                std::memcpy(next, out[k], n[k] * sizeof(std::uint32_t));
                next += n[k];
            }
            dst = next;
            count -= n[0] + n[1] + n[2] + n[3];
            p = skip_whitespace(end[3]);
        }
        return {p, std::size_t(dst - first)};
    }

private:
    static constexpr std::size_t kChunk = std::size_t(1) << 17;
    // A step advances a stream by 2..33 bytes and yields two values, so a stream of at most
    // kChunk / 4 + 33 bytes yields at most kChunk / 4 + 66 values.
    static constexpr std::size_t kCapacity = kChunk / 4 + 66;
    alignas(64) static inline std::uint32_t scratch_[3][kCapacity];

    // Steps all streams while each has 33 bytes left; returns the values per stream. Works on
    // local copies of the stream state, which stay in registers.
    static std::size_t lockstep(const char* (&streams)[4], const char* const (&end)[4],
                                std::uint32_t* const (&outputs)[4], __m256i& flags) {
        const char* s[4] = {streams[0], streams[1], streams[2], streams[3]};
        std::uint32_t* const out[4] = {outputs[0], outputs[1], outputs[2], outputs[3]};
        __m256i invalid = flags;
        std::size_t done = 0;
        for (;;) {
            std::ptrdiff_t left = end[0] - s[0];
            for (int k = 1; k < 4; ++k) left = std::min(left, end[k] - s[k]);
            if (left < 33) break;
            for (std::ptrdiff_t steps = left / 33; steps; --steps, done += 2) {
                const __m256i g0 = two_tokens(s[0], invalid), g1 = two_tokens(s[1], invalid);
                const __m256i g2 = two_tokens(s[2], invalid), g3 = two_tokens(s[3], invalid);
                const __m256i k = _mm256_set1_epi32(0x00012710);
                // 8-digit halves: [s0 high, s0 low, s1 high, s1 low | second tokens likewise].
                const __m256 h01 = _mm256_castsi256_ps(_mm256_madd_epi16(_mm256_packus_epi32(g0, g1), k));
                const __m256 h23 = _mm256_castsi256_ps(_mm256_madd_epi16(_mm256_packus_epi32(g2, g3), k));
                const __m256i high = _mm256_castps_si256(_mm256_shuffle_ps(h01, h23, 0x88));
                const __m256i low = _mm256_castps_si256(_mm256_shuffle_ps(h01, h23, 0xDD));
                const __m256i v = _mm256_add_epi32(_mm256_mullo_epi32(high, _mm256_set1_epi32(100000000)), low);
                // [s0 a, s0 b, s1 a, s1 b | s2 a, s2 b, s3 a, s3 b]
                const __m256i q = _mm256_permutevar8x32_epi32(v, _mm256_setr_epi32(0, 4, 1, 5, 2, 6, 3, 7));
                const __m128i q01 = _mm256_castsi256_si128(q), q23 = _mm256_extracti128_si256(q, 1);
                _mm_storel_epi64(reinterpret_cast<__m128i*>(out[0] + done), q01);
                _mm_storeh_pd(reinterpret_cast<double*>(out[1] + done), _mm_castsi128_pd(q01));
                _mm_storel_epi64(reinterpret_cast<__m128i*>(out[2] + done), q23);
                _mm_storeh_pd(reinterpret_cast<double*>(out[3] + done), _mm_castsi128_pd(q23));
            }
        }
        for (int k = 0; k < 4; ++k) streams[k] = s[k];
        flags = invalid;
        return done;
    }

    // Two tokens at s, as 4-digit groups [first | second]. Lengths outside 1..16 (repeated
    // whitespace, long tokens) set the sign bit of byte 15 or 31 of invalid.
    [[gnu::always_inline]] static __m256i two_tokens(const char*& s, __m256i& invalid) {
        const __m256i bytes = _mm256_loadu_si256(reinterpret_cast<const __m256i*>(s));
        const std::uint32_t sep = separators(bytes);
        const auto first = std::size_t(std::countr_zero(sep));              // length of the first token
        const auto second = std::size_t(std::countr_zero(sep & (sep - 1)));  // 32 if none
        const __m256i windows =
            _mm256_inserti128_si256(bytes, _mm_loadu_si128(reinterpret_cast<const __m128i*>(s + first + 1)), 1);
        const __m256i rows = _mm256_set_m128i(align_row(second - first), align_row(first + 1));
        invalid = _mm256_or_si256(invalid, rows);
        s += second + 1;
        return digit_groups(_mm256_shuffle_epi8(_mm256_subs_epu8(windows, _mm256_set1_epi8('0')), rows));
    }

    static std::uint32_t one_token(const char*& s, __m256i& invalid) {
        const __m128i window = _mm_loadu_si128(reinterpret_cast<const __m128i*>(s));
        const unsigned n = unsigned(std::countr_zero(separators(window) | 0x10000));
        invalid = _mm256_or_si256(invalid, _mm256_castsi128_si256(align_row(n + 1)));
        s += n + 1;
        return std::uint32_t(parse16(window, n));
    }

    // The byte after the first separator at or after q.
    static const char* after_separator(const char* q) {
        for (;; q += 32)
            if (const std::uint32_t sep = separators(_mm256_loadu_si256(reinterpret_cast<const __m256i*>(q))))
                return q + std::countr_zero(sep) + 1;
    }

    static const char* skip_whitespace(const char* p) {
        while (static_cast<unsigned char>(*p) <= ' ') ++p;
        return p;
    }

    // Tokens in [p, end), where p starts a token.
    static std::size_t count_tokens(const char* p, const char* end) {
        std::size_t tokens = 1;
        for (const char* q = p + 1; q < end; ++q)
            tokens += static_cast<unsigned char>(*q) > ' ' && static_cast<unsigned char>(q[-1]) <= ' ';
        return tokens;
    }

    static const char* parse_slowly(const char* p, std::uint32_t* dst, std::size_t count) {
        for (std::size_t i = 0; i < count; ++i) {
            p = skip_whitespace(p);
            const __m128i window = _mm_loadu_si128(reinterpret_cast<const __m128i*>(p));
            const unsigned n = unsigned(std::countr_zero(separators(window) | 0x10000));
            dst[i] = std::uint32_t(parse16(window, n));
            p += n + 1;
        }
        return p;
    }
};

}  // namespace detail

// Token boundaries come from separator bitmasks of aligned 64-byte blocks: finding the next token
// clears one bit, so consecutive reads do not wait on each other's parsing.
class Reader {
public:
    // Takes everything that remains on fd (stdin by default).
    explicit Reader(int fd = 0) : input_(detail::open_input(fd)) { seek(input_.start); }

    ~Reader() { detail::release(input_); }

    Reader(const Reader&) = delete;
    Reader& operator=(const Reader&) = delete;

    // Next integer token, or the next non-whitespace character for char. MaxDigits, if set, promises
    // at most that many digits; for 64-bit types, 16 or fewer selects a faster parser.
    // Non-negative values parse faster as unsigned types (10-18%, see notes.md).
    template <class T, int MaxDigits = 0>
        requires std::integral<T> && (!std::same_as<T, bool>)
    T read() {
        if constexpr (std::same_as<T, char>) {
            skip_whitespace();
            return *cur_++;
        } else {
            const auto [start, length] = next_token();
            // A leading '-' sits below '0' and parses as a zero digit.
            const auto magnitude = parse<(sizeof(T) > 4), MaxDigits>(start + length, length);
            if constexpr (std::is_unsigned_v<T>) return T(magnitude);
            else return T(*start == '-' ? 0 - magnitude : magnitude);
        }
    }

    // count tokens into dst. uint32_t uses the AVX2 bulk parser; other types read one by one.
    template <int MaxDigits = 0, class T>
    void read(T* dst, std::size_t count) {
        if constexpr (std::same_as<T, std::uint32_t>) {
            skip_whitespace();
            const auto [stop, parsed] = detail::BulkParser::parse(cur_, input_.end, dst, count);
            seek(stop);
            for (std::size_t i = parsed; i < count; ++i) dst[i] = read<T>();
        } else {
            for (std::size_t i = 0; i < count; ++i) dst[i] = read<T, MaxDigits>();
        }
    }

    // Next token; valid while the Reader lives.
    std::string_view word() {
        const auto [start, length] = next_token();
        return {start, length};
    }

    // Tokenizer state, for custom token loops. separators has one bit per whitespace byte of the
    // 64-byte block at block, at or after cur. The lowest bit is the end of the token at cur: clear
    // it to move on. With no bits left, advance block by 64 and take detail::block_separators.
    struct Scan {
        const char* cur;
        const char* block;
        std::uint64_t separators;
    };

    Scan scan() const { return {cur_, block_, separators_}; }

    void resume(const Scan& scan) {
        cur_ = scan.cur;
        block_ = scan.block;
        separators_ = scan.separators;
    }

private:
    struct Token {
        const char* start;
        unsigned length;
    };

    // Continue reading at p.
    void seek(const char* p) {
        cur_ = p;
        block_ = reinterpret_cast<const char*>(reinterpret_cast<std::uintptr_t>(p) & ~std::uintptr_t(63));
        separators_ = detail::block_separators(block_) & ~std::uint64_t(0) << (cur_ - block_);
    }

    // Position of the next separator; at or after cur_.
    const char* next_separator() {
        while (!separators_) [[unlikely]] {
            block_ += 64;
            separators_ = detail::block_separators(block_);
        }
        return block_ + std::countr_zero(separators_);
    }

    void skip_whitespace() {
        while (next_separator() == cur_) {
            separators_ &= separators_ - 1;
            ++cur_;
        }
    }

    Token next_token() {
        for (;;) {
            const char* end = next_separator();
            separators_ &= separators_ - 1;
            const char* start = cur_;
            cur_ = end + 1;
            if (end != start) [[likely]] return {start, unsigned(end - start)};
        }
    }

    // Value of the n characters that end at end.
    template <bool Wide, int MaxDigits>
    static auto parse(const char* end, unsigned n) {
        if constexpr (!Wide) return std::uint32_t(detail::parse_ending16(end, n));
        else if constexpr (MaxDigits > 0 && MaxDigits <= 16) return detail::parse_ending16(end, n);
        else return detail::parse_ending24(end, n);
    }

    detail::Input input_;
    const char* cur_;             // next unread byte
    const char* block_;           // 64-byte block holding the next separator
    std::uint64_t separators_;    // separators in block_ at or after cur_
};

// Buffered output. write() takes any mix of integers, chars and strings:
//   out.write(x, ' ', y, '\n');
// MaxDigits, if set, promises integers of at most that many digits; for 64-bit types, 16 or fewer
// selects a faster formatter: out.write<16>(sum, '\n').
class Writer {
public:
    explicit Writer(int fd = 1) : fd_(fd) {}
    ~Writer() { flush(); }

    Writer(const Writer&) = delete;
    Writer& operator=(const Writer&) = delete;

    template <int MaxDigits = 0, class... Ts>
    void write(const Ts&... values) {
        const std::size_t needed = (std::size_t(0) + ... + max_size(values));
        if (needed > kCapacity) [[unlikely]] {
            (write_alone<MaxDigits>(values), ...);
            return;
        }
        if (std::size_t(buffer_ + kCapacity - cur_) < needed) [[unlikely]] flush();
        char* p = cur_;
        ((p = put<MaxDigits>(p, values)), ...);
        cur_ = p;
    }

    // Custom formatting: fill(p) may store up to max_size <= 64 KiB bytes at p and returns the end
    // of what it wrote.
    template <class Fill>
    void write_with(std::size_t max_size, Fill fill) {
        if (std::size_t(buffer_ + kCapacity - cur_) < max_size) [[unlikely]] flush();
        cur_ = fill(cur_);
    }

    // values[0..count) joined by separator. uint32_t uses the AVX2 formatter.
    template <int MaxDigits = 0, class T>
    void write_array(const T* values, std::size_t count, char separator) {
        if (!count) return;
        std::size_t i = 0;
        if constexpr (std::same_as<T, std::uint32_t>) {
            constexpr std::size_t kBatch = 8 * 11 + 16;  // eight values and separators, plus overhang
            char* p = cur_;
            for (; i + 8 <= count; i += 8) {
                if (std::size_t(buffer_ + kCapacity - p) < kBatch) [[unlikely]] {
                    cur_ = p;
                    flush();
                    p = cur_;
                }
                p = detail::format8(p, _mm256_loadu_si256(reinterpret_cast<const __m256i*>(values + i)), separator);
            }
            cur_ = p;
        }
        for (; i < count; ++i) write<MaxDigits>(values[i], separator);
        --cur_;  // no separator after the last value
    }

    void flush() {
        write_all(fd_, buffer_, std::size_t(cur_ - buffer_));
        cur_ = buffer_;
    }

private:
    static constexpr std::size_t kCapacity = std::size_t(1) << 16;

    template <class T>
    static constexpr bool kInteger = std::integral<T> && !std::same_as<T, char> && !std::same_as<T, bool>;

    // Bytes put() may store, which can exceed what it writes.
    template <class T>
    static std::size_t max_size(const T& value) {
        if constexpr (std::same_as<T, char>) return 1;
        else if constexpr (kInteger<T>) return 1 + 20;  // a sign, then format() stores up to 20 bytes
        else return std::string_view(value).size();
    }

    template <int MaxDigits, class T>
    static char* put(char* p, const T& value) {
        if constexpr (std::same_as<T, char>) {
            *p = value;
            return p + 1;
        } else if constexpr (kInteger<T>) {
            using U = std::conditional_t<sizeof(T) <= 4, std::uint32_t, std::uint64_t>;
            if constexpr (std::is_signed_v<T>) {
                *p = '-';
                p += value < 0;
                return put<MaxDigits>(p, value < 0 ? U(0 - U(value)) : U(value));
            } else if constexpr (sizeof(T) <= 4) {
                return detail::format(p, U(value));
            } else {
                return detail::format64<MaxDigits == 0 ? 20 : MaxDigits>(p, U(value));
            }
        } else {
            const std::string_view s(value);
            std::memcpy(p, s.data(), s.size());
            return p + s.size();
        }
    }

    // A value longer than the buffer: flush, then write it directly.
    template <int MaxDigits, class T>
    void write_alone(const T& value) {
        if constexpr (std::same_as<T, char> || kInteger<T>) {
            write<MaxDigits>(value);
        } else {
            flush();
            const std::string_view s(value);
            write_all(fd_, s.data(), s.size());
        }
    }

    static void write_all(int fd, const char* data, std::size_t size) {
        while (size) {
            const ssize_t put = ::write(fd, data, size);
            if (put > 0) data += put, size -= std::size_t(put);
            else if (put < 0 && errno == EINTR) continue;
            else std::abort();
        }
    }

    int fd_;
    char* cur_ = buffer_;
    alignas(64) char buffer_[kCapacity];
};

}  // namespace io
// problems/convolution/fixed_width.hpp
// Fixed-width output of residues < 10^9: each value right-aligned in 9 characters, then a space;
// the last separator is a newline. Judge-specific: the checker compares tokens, so the padding is
// accepted. No branches on value size, and four 32-byte stores per eight values.


namespace fixed_width {

namespace detail {

struct alignas(32) Lanes {
    std::uint32_t lane[8];
};

constexpr Lanes all(std::uint32_t x) { return {{x, x, x, x, x, x, x, x}}; }

constexpr Lanes bytes(const int (&b)[32]) {
    Lanes t{};
    for (int i = 0; i < 32; ++i) t.lane[i / 4] |= std::uint32_t(b[i] & 0xFF) << 8 * (i % 4);
    return t;
}

constexpr int x = 0x80;  // shuffle control: zero byte

struct Constants {
    Lanes div4 = all(3518437209), div8 = all(720575941);  // ceil(2^45 / 10^4), ceil(2^56 / 10^8)
    Lanes ten4 = all(10000);
    Lanes by100 = all(0x147B147B), hundreds_up = all(65436);  // 5243 in each 16-bit half
    Lanes by10 = all(0x199A199A), tens_up = all(0x00F600F6);  // 6554 and 246 in each half
    Lanes zero = all(0x30303030), lead = all(0x20000020), lead_shown = all(0x10);
    // max_below[e] = 10^e - 1; blank masks for the low and high digit dwords, and the shift
    // offset of the high one (its digits come 4 after the low ones: 8 * 3 bits).
    Lanes max_below[9] = {all(0),     all(9),      all(99),      all(999),     all(9999),
                          all(99999), all(999999), all(9999999), all(99999999)};
    Lanes blank_low = all(0x10101000), blank_high = all(0x10101010), high_offset = all(24);
    // Two fields from one lane's [high_i, low_i, high_i+1, low_i+1] digit dwords, copied to both
    // lanes; the 9th digits (bytes 0, 10) and separators (9, 19) come from lead dwords j, j + 1.
    Lanes order = bytes({x, 3, 2, 1, 0, 7, 6, 5, 4, x, x, 11, 10, 9, 8, 15,  //
                         14, 13, 12, x, x, x, x, x, x, x, x, x, x, x, x, x});
    Lanes ends[2] = {bytes({0, x, x, x, x, x, x, x, x, 3, 4, x, x, x, x, x,  //
                            x, x, x, 7, x, x, x, x, x, x, x, x, x, x, x, x}),
                     bytes({8, x, x, x, x, x, x, x, x, 11, 12, x, x, x, x, x,  //
                            x, x, x, 15, x, x, x, x, x, x, x, x, x, x, x, x})};
};

inline constexpr Constants kConstants{};

// kConstants through a pointer the compiler cannot see through: the output stores might change
// the table, so each use stays a memory operand instead of a constant rebuilt in a register.
inline const Constants& constants() {
    const Constants* k = &kConstants;
    asm("" : "+r"(k));
    return *k;
}

[[gnu::always_inline]] inline __m256i load(const Lanes& l) {
    return _mm256_load_si256(reinterpret_cast<const __m256i*>(&l));
}

// floor(v / d) for each dword v < 10^9 as (v * magic) >> Shift; odd: v >> 32 per qword. The odd
// lanes shift 32 bits less, which leaves the quotient in the high dword.
template <int Shift>
[[gnu::always_inline]] inline __m256i divide(__m256i v, __m256i odd, const Lanes& magic) {
    return _mm256_blend_epi32(_mm256_srli_epi64(_mm256_mul_epu32(v, load(magic)), Shift),
                              _mm256_srli_epi64(_mm256_mul_epu32(odd, load(magic)), Shift - 32), 0xAA);
}

// Each dword y < 10^4 -> its 4 decimal digits as byte values, least significant first.
[[gnu::always_inline]] inline __m256i digits4(__m256i y, const Constants& k) {
    const __m256i hundreds = _mm256_srli_epi16(_mm256_mulhi_epu16(y, load(k.by100)), 3);
    const __m256i halves = _mm256_add_epi32(y, _mm256_mullo_epi32(hundreds, load(k.hundreds_up)));  // [y % 100, y / 100]
    const __m256i tens = _mm256_mulhi_epu16(halves, load(k.by10));  // each 16-bit half / 10
    return _mm256_add_epi16(halves, _mm256_mullo_epi16(tens, load(k.tens_up)));  // [x % 10, x / 10] bytes
}

// Eight values < 10^9 as 80 bytes at p. Stores 12 bytes past the end.
[[gnu::always_inline]] inline void format8(char* p, __m256i v, const Constants& k) {
    const __m256i odd = _mm256_srli_epi64(v, 32);
    const __m256i q4 = divide<45>(v, odd, k.div4);  // v / 10^4
    const __m256i q8 = divide<56>(v, odd, k.div8);  // v / 10^8
    const __m256i high = _mm256_sub_epi32(q4, _mm256_mullo_epi32(q8, load(k.ten4)));
    const __m256i low = _mm256_sub_epi32(v, _mm256_mullo_epi32(q4, load(k.ten4)));
    // v has n digits: the 9 - n leading positions are blank, '0' - 0x10 = ' '. Blank masks (0x10
    // per byte, the most significant digit in the top byte) shift left by 8 (n - 1) bits for the
    // low dword, 8 (n - 4) for the high one. c = 1 - n from the compares v >= 10^e, e = 1..8.
    const auto at_least = [&](int e) { return _mm256_cmpgt_epi32(v, load(k.max_below[e])); };
    const auto sum = [](__m256i a, __m256i b) { return _mm256_add_epi32(a, b); };
    const __m256i at_least8 = at_least(8);
    const __m256i c = sum(sum(sum(at_least(1), at_least(2)), sum(at_least(3), at_least(4))),
                          sum(sum(at_least(5), at_least(6)), sum(at_least(7), at_least8)));
    const __m256i shift = _mm256_slli_epi32(_mm256_abs_epi32(c), 3);
    const __m256i blank_low = _mm256_sllv_epi32(load(k.blank_low), shift);  // the units always shown
    const __m256i high_shift = _mm256_subs_epu16(shift, load(k.high_offset));  // 0 if n < 4
    const __m256i blank_high = _mm256_sllv_epi32(load(k.blank_high), high_shift);
    const __m256i h = _mm256_sub_epi8(_mm256_add_epi8(digits4(high, k), load(k.zero)), blank_high);
    const __m256i l = _mm256_sub_epi8(_mm256_add_epi8(digits4(low, k), load(k.zero)), blank_low);
    // Lead dwords: the digit of 10^8 (or a space) in byte 0, the separator in byte 3.
    const __m256i lead_digit = _mm256_and_si256(at_least8, load(k.lead_shown));  // ' ' + 0x10 = '0'
    const __m256i lead = _mm256_add_epi32(_mm256_add_epi32(q8, load(k.lead)), lead_digit);
    const __m256i hl01 = _mm256_unpacklo_epi32(h, l);  // [h0 l0 h1 l1 | h4 l4 h5 l5]
    const __m256i hl23 = _mm256_unpackhi_epi32(h, l);  // [h2 l2 h3 l3 | h6 l6 h7 l7]
    // Each lane copied to both lanes.
    const auto low_lane = [](__m256i a) { return _mm256_inserti128_si256(a, _mm256_castsi256_si128(a), 1); };
    const auto high_lane = [](__m256i a) { return _mm256_permute2x128_si256(a, a, 0x11); };
    const __m256i lead_low = low_lane(lead), lead_high = high_lane(lead);
    const auto two_fields = [&](__m256i digits, __m256i leads, int j) {
        return _mm256_or_si256(_mm256_shuffle_epi8(digits, load(k.order)),
                               _mm256_shuffle_epi8(leads, load(k.ends[j])));
    };
    const auto store = [](char* q, __m256i f) { _mm256_storeu_si256(reinterpret_cast<__m256i*>(q), f); };
    store(p, two_fields(low_lane(hl01), lead_low, 0));
    store(p + 20, two_fields(low_lane(hl23), lead_low, 1));
    store(p + 40, two_fields(high_lane(hl01), lead_high, 0));
    store(p + 60, two_fields(high_lane(hl23), lead_high, 1));
}

}  // namespace detail

// values[0, count), count >= 1, as fixed-width fields. They are formatted in blocks of 250 KB,
// longer than the Writer's buffer, so the Writer hands each block to write(2) directly: on a
// 331 MB output 3% faster than 64 KiB writes.
inline void write(io::Writer& out, const std::uint32_t* values, std::size_t count) {
    constexpr std::size_t kBlock = 25600;  // values
    alignas(64) static char text[10 * kBlock + 96];
    const detail::Constants& k = detail::constants();
    for (std::size_t i = 0; i < count; i += kBlock) {
        const std::size_t n = std::min(kBlock, count - i);
        char* p = text;
        std::size_t j = 0;
        for (; j + 8 <= n; j += 8, p += 80)
            detail::format8(p, _mm256_loadu_si256(reinterpret_cast<const __m256i*>(values + i + j)), k);
        if (j < n) {
            alignas(32) std::uint32_t tail[8] = {};
            std::memcpy(tail, values + i + j, (n - j) * sizeof(std::uint32_t));
            detail::format8(p, _mm256_load_si256(reinterpret_cast<const __m256i*>(tail)), k);
            p += 10 * (n - j);
        }
        if (i + n == count) p[-1] = '\n';
        out.write(std::string_view(text, std::size_t(p - text)));
    }
}

}  // namespace fixed_width

namespace {

constexpr std::uint32_t kP = 998244353;
constexpr std::uint32_t kNegInverse = [] {  // -1/P mod 2^32
    std::uint32_t x = kP;                     // P^-1 mod 2^3; each step doubles the bits
    for (int i = 0; i < 4; ++i) x *= 2 - kP * x;
    return 0 - x;
}();
constexpr std::uint32_t kR2 = std::uint32_t((std::uint64_t(1) << 32) % kP * ((std::uint64_t(1) << 32) % kP) % kP);

using Vec = __m256i;
using Half = __m128i;
using AliasWord [[gnu::may_alias]] = std::uint32_t;

Vec broadcast(std::uint32_t x) { return _mm256_set1_epi32(int(x)); }
Vec load(const void* p) { return _mm256_loadu_si256(static_cast<const Vec*>(p)); }
void store(void* p, Vec x) { _mm256_storeu_si256(static_cast<Vec*>(p), x); }
Half load_pair(const std::uint64_t* p) { return _mm_loadl_epi64(reinterpret_cast<const Half*>(p)); }
void store_pair(std::uint64_t* p, Half x) { _mm_storel_epi64(reinterpret_cast<Half*>(p), x); }

// Per dword, for x, y < P.
Vec add(Vec x, Vec y) {
    const Vec s = _mm256_add_epi32(x, y);
    return _mm256_min_epu32(s, _mm256_sub_epi32(s, broadcast(kP)));
}
Vec sub(Vec x, Vec y) {
    const Vec d = _mm256_sub_epi32(x, y);
    return _mm256_min_epu32(d, _mm256_add_epi32(d, broadcast(kP)));
}
Half add(Half x, Half y) {
    const Half s = _mm_add_epi32(x, y);
    return _mm_min_epu32(s, _mm_sub_epi32(s, _mm_set1_epi32(int(kP))));
}
std::uint32_t add(std::uint32_t x, std::uint32_t y) {
    const std::uint32_t s = x + y;
    return std::min(s, s - kP);
}
std::uint32_t sub(std::uint32_t x, std::uint32_t y) {
    const std::uint32_t d = x - y;
    return std::min(d, d + kP);
}

// Montgomery: for 64-bit lanes t < 2^62, (t + m P) / 2^32 = t / 2^32 mod P in the high dword,
// below t / 2^32 + P.
Vec redc(Vec t) {
    const Vec m = _mm256_mul_epu32(t, broadcast(kNegInverse));
    return _mm256_add_epi64(t, _mm256_mul_epu32(m, broadcast(kP)));
}

// Pairs [a | b R] (R = 2^32) -> a b mod P in the high dword of each 64-bit lane, below 1.25 P.
Vec product4(Vec pairs) { return redc(_mm256_mul_epu32(pairs, _mm256_srli_epi64(pairs, 32))); }

// The high dwords of x and y: [x0 x1 x2 x3 y0 y1 y2 y3], reduced from below 2P.
Vec high_dwords(Vec x, Vec y) {
    const Vec v = _mm256_castps_si256(_mm256_shuffle_ps(_mm256_castsi256_ps(x), _mm256_castsi256_ps(y), 0xDD));
    const Vec ordered = _mm256_permute4x64_epi64(v, 0xD8);
    return _mm256_min_epu32(ordered, _mm256_sub_epi32(ordered, broadcast(kP)));
}

// Pairs 0, 2, 4, 6 of the 8 at p.
Vec even_pairs(const std::uint64_t* p) {
    return _mm256_permute4x64_epi64(_mm256_unpacklo_epi64(load(p), load(p + 4)), 0xD8);
}

// Pairs 0, s, 2s, 3s at p.
Vec gather_pairs(const std::uint64_t* p, std::size_t s) {
    return _mm256_set_epi64x(std::int64_t(p[3 * s]), std::int64_t(p[2 * s]), std::int64_t(p[s]), std::int64_t(p[0]));
}

// Dwords 0, s, ..., 7s at p; index holds 0, s, ..., 7s.
Vec gather_dwords(const std::uint32_t* p, Vec index) {
    return _mm256_i32gather_epi32(reinterpret_cast<const int*>(p), index, 4);
}

void add_pair(std::uint64_t* dst, const std::uint64_t* src) { store_pair(dst, add(load_pair(dst), load_pair(src))); }

// Adds 64-bit lane sums [a, b] to the pair at dst.
void add_sums(std::uint64_t* dst, Half sums) {
    const auto a = std::uint32_t(std::uint64_t(_mm_cvtsi128_si64(sums)) % kP);
    const auto b = std::uint32_t(std::uint64_t(_mm_extract_epi64(sums, 1)) % kP);
    store_pair(dst, add(load_pair(dst), _mm_setr_epi32(int(a), int(b), 0, 0)));
}

// The pair at p as two 64-bit lanes.
Half widen_pair(const std::uint64_t* p) { return _mm_cvtepu32_epi64(load_pair(p)); }

// Zeroed memory in 2 MiB pages where the kernel allows. Never freed.
template <class T>
T* allocate(std::size_t count) {
    constexpr std::size_t kHuge = std::size_t(1) << 21;
    const std::size_t bytes = (count * sizeof(T) + kHuge - 1) / kHuge * kHuge;
    void* p = ::mmap(nullptr, bytes + kHuge, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
    if (p == MAP_FAILED) std::abort();
    const std::uintptr_t aligned = (reinterpret_cast<std::uintptr_t>(p) + kHuge - 1) & ~(kHuge - 1);
#ifdef MADV_HUGEPAGE
    ::madvise(reinterpret_cast<void*>(aligned), bytes, MADV_HUGEPAGE);
#endif
    return reinterpret_cast<T*>(aligned);
}

// The rough numbers (coprime to 30030 = 2 3 5 7 11 13) as a wheel: the one with index t is
// (t / kSpokes) kWheel + spoke[t % kSpokes]. Index 0 is 1, index 1 is 17.
constexpr std::uint32_t kWheel = 30030, kSpokes = 5760;

struct Wheel {
    std::uint16_t spoke[kSpokes];
    std::uint16_t rank[kWheel];  // spokes below r

    constexpr Wheel() : spoke(), rank() {
        bool shared[kWheel] = {};
        for (const std::uint32_t p : {2, 3, 5, 7, 11, 13})
            for (std::uint32_t r = 0; r < kWheel; r += p) shared[r] = true;
        std::uint16_t count = 0;
        for (std::uint32_t r = 0; r < kWheel; ++r) {
            rank[r] = count;
            if (!shared[r]) spoke[count++] = std::uint16_t(r);
        }
    }

    // Index of the first rough number >= x.
    constexpr std::uint32_t index(std::uint32_t x) const { return x / kWheel * kSpokes + rank[x % kWheel]; }
};

constexpr Wheel kRough;

// Sum over the rough m with index in [t0, t1) of term(i m), in two interleaved chains. i m < 2^32.
template <class T, class Term>
[[gnu::always_inline]] inline T sum_multiples(std::uint32_t i, std::uint32_t t0, std::uint32_t t1, T sum, Term term) {
    T other{};
    std::uint32_t k = t0 % kSpokes, base = t0 / kSpokes * kWheel * i;
    for (std::uint32_t left = t1 - t0; left; k = 0, base += kWheel * i) {
        const std::uint32_t end = std::min(kSpokes, k + left);
        left -= end - k;
        for (; k + 2 <= end; k += 2) {
            sum += term(base + i * kRough.spoke[k]);
            other += term(base + i * kRough.spoke[k + 1]);
        }
        if (k < end) sum += term(base + i * kRough.spoke[k]);
    }
    return sum + other;
}

// floor(x / d) = (x r) >> 42 with r = reciprocal(d), for x, d < 2^20.
constexpr std::uint64_t reciprocal(std::uint32_t d) { return (std::uint64_t(1) << 42) / d + 1; }
inline std::uint32_t divide(std::uint32_t x, std::uint64_t r) { return std::uint32_t(x * r >> 42); }

// Rough multipliers 17 <= m <= kSplit go by m, each over a run of targets i; larger ones by
// target i <= n / (kSplit + 1), into 64-bit sums. Sources come in segments that fit in L2.
constexpr std::uint32_t kSplit = 2048;
constexpr std::uint32_t kSmall = kRough.index(kSplit + 1);  // small m: spoke[1..kSmall)
constexpr std::uint32_t kMaxN = 1 << 20;
constexpr std::uint32_t kMaxTargets = kMaxN / (kSplit + 1) + 1;

constexpr auto kSmallReciprocal = [] {
    std::array<std::uint64_t, kSmall> r{};
    for (std::uint32_t k = 1; k < kSmall; ++k) r[k] = reciprocal(kRough.spoke[k]);
    return r;
}();
constexpr auto kTargetReciprocal = [] {
    std::array<std::uint64_t, kMaxTargets> r{};
    for (std::uint32_t i = 1; i < kMaxTargets; ++i) r[i] = reciprocal(i);
    return r;
}();

// pairs[i] = (a_i, b_i R mod P) for 1 <= i <= n, then the zeta pass of p = 3. a may be the first
// half of pairs: i descends, so pairs[i] only overwrites a_2i and a_2i+1, which are read already.
void interleave_zeta3(const AliasWord* a, const std::uint32_t* b, std::uint64_t* pairs, std::uint32_t n) {
    const Vec r2 = broadcast(kR2);
    // b_i R as Montgomery products of b_i and R^2: dwords [b R] in the high halves.
    auto scaled_pairs = [&](std::uint32_t i, Vec& low, Vec& high) {
        const Vec va = load(a + i), vb = load(b + i);
        const Vec even = redc(_mm256_mul_epu32(vb, r2));
        const Vec odd = redc(_mm256_mul_epu32(_mm256_srli_epi64(vb, 32), r2));
        // even/odd: [_ bR] per qword (below 1.25 P). Reduce, then place below a.
        const Vec bs = _mm256_blend_epi32(_mm256_srli_epi64(even, 32), odd, 0xAA);
        const Vec br = _mm256_min_epu32(bs, _mm256_sub_epi32(bs, broadcast(kP)));
        const Vec lo = _mm256_unpacklo_epi32(va, br), hi = _mm256_unpackhi_epi32(va, br);
        low = _mm256_permute2x128_si256(lo, hi, 0x20);
        high = _mm256_permute2x128_si256(lo, hi, 0x31);
    };
    const std::uint32_t third = n / 3;
    std::uint32_t i = n + 1;
    // Targets i > n / 3 only take their own values. Eight at a time, from the top.
    while (i >= third + 9) {
        i -= 8;
        Vec low, high;
        scaled_pairs(i, low, high);
        store(pairs + i, low);
        store(pairs + i + 4, high);
    }
    auto one = [&](std::uint32_t k) {
        const std::uint32_t br = std::uint32_t((std::uint64_t(b[k]) << 32) % kP);
        const std::uint64_t pair = a[k] | std::uint64_t(br) << 32;
        std::memcpy(pairs + k, &pair, sizeof pair);
        if (k <= third) add_pair(pairs + k, pairs + 3 * k);
    };
    while (i > third + 1) one(--i);
    while (i >= 8 + 4) {  // sources 3i > i + 7
        i -= 8;
        Vec low, high;
        scaled_pairs(i, low, high);
        store(pairs + i, add(low, gather_pairs(pairs + 3 * i, 3)));
        store(pairs + i + 4, add(high, gather_pairs(pairs + 3 * (i + 4), 3)));
    }
    while (i > 1) one(--i);
}

// Zeta pass of p >= 5 on the pairs: four targets at a time from the top, then one at a time.
void zeta_pass(std::uint64_t* pairs, std::uint32_t n, std::uint32_t p) {
    std::uint32_t i = n / p + 1;
    while (i >= 5) {
        i -= 4;
        store(pairs + i, add(load(pairs + i), gather_pairs(pairs + p * i, p)));
    }
    while (i > 1) {
        --i;
        add_pair(pairs + i, pairs + p * i);
    }
}

// pairs[i] += sum of pairs[i m] over rough m > 1, im <= n: the zeta passes of all primes >= 17.
// Sources go segment by segment, ascending, so each is read before it changes: the targets of a
// segment's sources lie in earlier segments. Segment 0 goes by target, ascending.
void zeta_rough(std::uint64_t* pairs, std::uint32_t n) {
    constexpr std::uint32_t kSegment = 1 << 15;  // 256 KiB of pairs
    auto widened = [&](std::uint32_t j) { return widen_pair(pairs + j); };
    const std::uint32_t end0 = std::min(n + 1, kSegment);
    for (std::uint32_t i = 1; 17 * i < end0; ++i)  // below 2^15 terms of 2^30 per lane
        add_sums(pairs + i, sum_multiples(i, 1, kRough.index((end0 - 1) / i + 1), Half{}, widened));
    if (n < kSegment) return;
    // Per small m: the next target. Per large target: the next multiplier index, and the sums
    // (below 2^18 terms of 2^30 per lane).
    static std::uint32_t next_target[kSmall], next_index[kMaxTargets];
    static Half sums[kMaxTargets];
    for (std::uint32_t k = 1; k < kSmall; ++k) next_target[k] = (kSegment - 1) / kRough.spoke[k] + 1;
    const std::uint32_t targets = n / (kSplit + 1);
    for (std::uint32_t i = 1; i <= targets; ++i)
        next_index[i] = std::max(kSmall, kRough.index((kSegment - 1) / i + 1));
    for (std::uint32_t start = kSegment; start <= n; start += kSegment) {
        const std::uint32_t last_source = std::min(n, start + kSegment - 1);
        for (std::uint32_t k = 1; k < kSmall; ++k) {
            const std::uint32_t m = kRough.spoke[k], last = divide(last_source, kSmallReciprocal[k]);
            std::uint32_t i = next_target[k];
            for (; i + 3 <= last; i += 4) store(pairs + i, add(load(pairs + i), gather_pairs(pairs + i * m, m)));
            for (; i <= last; ++i) add_pair(pairs + i, pairs + i * m);
            next_target[k] = i;
        }
        for (std::uint32_t i = 1; i * (kSplit + 1) <= last_source; ++i) {
            const std::uint32_t end = kRough.index(divide(last_source, kTargetReciprocal[i]) + 1);
            sums[i] = sum_multiples(i, next_index[i], end, sums[i], widened);
            next_index[i] = end;
        }
    }
    for (std::uint32_t i = 1; i <= targets; ++i) add_sums(pairs + i, sums[i]);
}

// Zeta pass of p = 2 fused with the product and the Moebius pass of 2:
// c_i = A_i B_i - A_2i B_2i (the second term for i <= n / 2).
void zeta2_product_moebius2(std::uint64_t* pairs, std::uint32_t* c, std::uint32_t n) {
    const std::uint32_t half = n / 2;
    std::uint32_t i = n + 1;
    while (i >= half + 9) {
        i -= 8;
        store(c + i, high_dwords(product4(load(pairs + i)), product4(load(pairs + i + 4))));
    }
    auto one = [&](std::uint32_t k) {
        std::uint32_t ai = std::uint32_t(pairs[k]), bi = std::uint32_t(pairs[k] >> 32);
        auto product = [](std::uint32_t x, std::uint32_t yr) {
            const std::uint64_t t = std::uint64_t(x) * yr;
            const std::uint32_t m = std::uint32_t(t) * kNegInverse;
            const std::uint32_t r = std::uint32_t((t + std::uint64_t(m) * kP) >> 32);
            return std::min(r, r - kP);
        };
        if (k <= half) {
            const std::uint64_t s = pairs[2 * k];
            ai = add(ai, std::uint32_t(s));
            bi = add(bi, std::uint32_t(s >> 32));
            pairs[k] = ai | std::uint64_t(bi) << 32;
            c[k] = sub(product(ai, bi), product(std::uint32_t(s), std::uint32_t(s >> 32)));
        } else {
            c[k] = product(ai, bi);
        }
    };
    while (i > half + 1) one(--i);
    while (i >= 8 + 8) {  // sources 2i > i + 7
        i -= 8;
        const Vec s0 = even_pairs(pairs + 2 * i), s1 = even_pairs(pairs + 2 * i + 8);
        const Vec t0 = add(load(pairs + i), s0), t1 = add(load(pairs + i + 4), s1);
        store(pairs + i, t0);
        store(pairs + i + 4, t1);
        store(c + i, sub(high_dwords(product4(t0), product4(t1)), high_dwords(product4(s0), product4(s1))));
    }
    while (i > 1) one(--i);
}

// Moebius pass of p on c: eight targets at a time from i = 4 up (sources ip > i + 7 are unchanged).
void moebius_pass(std::uint32_t* c, std::uint32_t n, std::uint32_t p) {
    const std::uint32_t last = n / p;
    std::uint32_t i = 1;
    for (; i < 4 && i <= last; ++i) c[i] = sub(c[i], c[i * p]);
    const Vec index = _mm256_mullo_epi32(_mm256_setr_epi32(0, 1, 2, 3, 4, 5, 6, 7), broadcast(p));
    for (; i + 7 <= last; i += 8) store(c + i, sub(load(c + i), gather_dwords(c + i * p, index)));
    for (; i <= last; ++i) c[i] = sub(c[i], c[i * p]);
}

// c_i -= sum of c_im over rough m > 1, im <= n, with final values c_im: the Moebius passes of all
// primes >= 17 (inverting zeta_rough: x_i = y_i - sum over m > 1 of x_im). Segments descend, so a
// segment is final when read; segment 0 goes by target, descending.
void moebius_rough(std::uint32_t* c, std::uint32_t n) {
    constexpr std::uint32_t kSegment = 1 << 16;  // 256 KiB
    auto value = [&](std::uint32_t j) { return std::uint64_t(c[j]); };
    if (n >= kSegment) {
        // Per small m: the last target. Per large target: the end of its multiplier indices,
        // and the sums (below 2^18 terms of 2^30).
        static std::uint32_t last_target[kSmall], end_index[kMaxTargets];
        static std::uint64_t sums[kMaxTargets];
        for (std::uint32_t k = 1; k < kSmall; ++k) last_target[k] = n / kRough.spoke[k];
        const std::uint32_t targets = n / (kSplit + 1);
        for (std::uint32_t i = 1; i <= targets; ++i) end_index[i] = kRough.index(n / i + 1);
        for (std::uint32_t start = n / kSegment * kSegment; start >= kSegment; start -= kSegment) {
            for (std::uint32_t k = 1; k < kSmall; ++k) {
                const std::uint32_t m = kRough.spoke[k], last = last_target[k];
                const Vec index = _mm256_mullo_epi32(_mm256_setr_epi32(0, 1, 2, 3, 4, 5, 6, 7), broadcast(m));
                std::uint32_t i = divide(start - 1, kSmallReciprocal[k]) + 1;
                last_target[k] = i - 1;
                for (; i + 7 <= last; i += 8) store(c + i, sub(load(c + i), gather_dwords(c + i * m, index)));
                for (; i <= last; ++i) c[i] = sub(c[i], c[i * m]);
            }
            const std::uint32_t last_source = std::min(n, start + kSegment - 1);
            for (std::uint32_t i = 1; i * (kSplit + 1) <= last_source; ++i) {
                const std::uint32_t begin =
                    std::max(kSmall, kRough.index(divide(start - 1, kTargetReciprocal[i]) + 1));
                if (begin < end_index[i]) sums[i] = sum_multiples(i, begin, end_index[i], sums[i], value);
                end_index[i] = begin;
            }
        }
        for (std::uint32_t i = 1; i <= targets; ++i) c[i] = sub(c[i], std::uint32_t(sums[i] % kP));
    }
    const std::uint32_t end0 = std::min(n + 1, kSegment);
    for (std::uint32_t i = (end0 - 1) / 17; i >= 1; --i)
        c[i] = sub(c[i], std::uint32_t(sum_multiples(i, 1, kRough.index((end0 - 1) / i + 1), std::uint64_t{}, value) % kP));
}

}  // namespace

int main() {
    io::Reader in;
    const auto n = in.read<std::uint32_t>();
    // One region: the pairs, with a parsed into their first half; then b, later c.
    constexpr std::size_t kPad = 64;
    const std::size_t words = n + kPad;
    auto* region = allocate<std::uint32_t>(3 * words);
    auto* pairs = reinterpret_cast<std::uint64_t*>(region);
    std::uint32_t* const b = region + 2 * words;
    in.read(region + 1, n);
    in.read(b + 1, n);

    interleave_zeta3(region, b, pairs, n);
    for (const std::uint32_t p : {5, 7, 11, 13}) zeta_pass(pairs, n, p);
    zeta_rough(pairs, n);
    std::uint32_t* const c = b;
    zeta2_product_moebius2(pairs, c, n);
    for (const std::uint32_t p : {3, 5, 7, 11, 13}) moebius_pass(c, n, p);
    moebius_rough(c, n);

    io::Writer out;
    fixed_width::write(out, c + 1, n);
}
