// Factorials modulo 998244353, and product chains in 32 lanes whose multipliers are arithmetic
// progressions: the bulk factorials, inverse factorials and similar products of Taylor shifts and
// Lagrange interpolation. x86-64 with AVX2. Log: lib/poly/notes.md (Factorials).
//
//   poly::factorial(n)                    // n! mod P for n < poly::kFactorialLimit
//   poly::Lanes f = poly::factorials(n);  // f[s] = n[s]! for 32 values n[s] < kFactorialLimit
//   poly::invert(f);                      // f[s] = 1 / f[s], nonzero values, one exponentiation
//
//   // Lane s multiplies by base[s] + j step at its step j (montgomery(): x m / 2^32):
//   poly::detail::Chain<> up(x, base, step);           // terms in step order
//   poly::detail::Chain<true> down(x, base, step);     // each block of 8 terms reversed
//   poly::detail::scan(steps, put, up, down);          // put(j, s, terms...), 8 steps, lane s
//
// Values in [0, P) unless stated. The table of (1024 k)! is factorial_table.hpp, generated by
// gen_factorials.py (run it after a change; CI checks that the table matches).
#pragma once

#include <immintrin.h>

#include <algorithm>
#include <array>
#include <cstddef>
#include <cstdint>
#include <span>
#include <utility>
#include <vector>

#include "lib/poly/calculus.hpp"
#include "lib/poly/factorial_table.hpp"

namespace poly {

// 32 values, one per lane of a scan.
using Lanes = std::array<std::uint32_t, 32>;

inline constexpr std::uint32_t kFactorialLimit = sizeof(detail::kFactorialTable) / sizeof(std::uint32_t) * 1024;

namespace detail {

inline constexpr int kChainVectors = 4;  // 32 lanes: lane 8 v + l is lane l of vector v

// [v][t]: step t of lanes 8 v .. 8 v + 7.
using ChainBlock = Vec[kChainVectors][8];

// Lanes 1, 3, 5, 7 of x in lanes 0, 2, 4, 6: the operands of _mm256_mul_epu32.
[[gnu::always_inline]] inline Vec odd_lanes(Vec x) { return _mm256_srli_epi64(x, 32); }

// montgomery(a, b) with the odd lanes of a and b in the even lanes of a_odd and b_odd.
[[gnu::always_inline]] inline Vec montgomery(Vec a, Vec a_odd, Vec b, Vec b_odd) {
    const Vec ni = broadcast(ntt::kernels::kNI), p = broadcast(kP);
    Vec even = _mm256_mul_epu32(a, b), odd = _mm256_mul_epu32(a_odd, b_odd);
    even = _mm256_add_epi64(even, _mm256_mul_epu32(_mm256_mul_epu32(even, ni), p));
    odd = _mm256_add_epi64(odd, _mm256_mul_epu32(_mm256_mul_epu32(odd, ni), p));
    return _mm256_blend_epi32(_mm256_srli_epi64(even, 32), odd, 0xAA);
}

// Rows become columns: lane l of r[t] moves to lane t of r[l], t, l < 8.
[[gnu::always_inline]] inline void transpose_steps(Vec (&r)[8]) {
    Vec t[8], u[8];
#pragma GCC unroll 4
    for (int i = 0; i < 8; i += 2) {
        t[i] = _mm256_unpacklo_epi32(r[i], r[i + 1]);
        t[i + 1] = _mm256_unpackhi_epi32(r[i], r[i + 1]);
    }
#pragma GCC unroll 2
    for (int i = 0; i < 8; i += 4) {
        u[i] = _mm256_unpacklo_epi64(t[i], t[i + 2]);
        u[i + 1] = _mm256_unpackhi_epi64(t[i], t[i + 2]);
        u[i + 2] = _mm256_unpacklo_epi64(t[i + 1], t[i + 3]);
        u[i + 3] = _mm256_unpackhi_epi64(t[i + 1], t[i + 3]);
    }
#pragma GCC unroll 4
    for (int i = 0; i < 4; ++i) {
        r[i] = _mm256_permute2x128_si256(u[i], u[i + 4], 0x20);
        r[i + 4] = _mm256_permute2x128_si256(u[i], u[i + 4], 0x31);
    }
}

inline void load_lanes(Vec (&x)[kChainVectors], const Lanes& values) {
    for (int v = 0; v < kChainVectors; ++v) x[v] = load_unaligned(values.data() + 8 * v);
}

// A product chain in 32 lanes: at its step j, lane s multiplies x by m = base[s] + j step mod P,
// x <- x m / 2^32 in [0, 2P), after recording x. x starts below 2P; base and step below P. A step
// is one montgomery() and one addition per vector; the odd lanes of base are kept apart.
template <bool kReversed = false>
class Chain {
public:
    Chain(const Lanes& x, const Lanes& base, std::uint32_t step) : u_(_mm256_setzero_si256()), step_(broadcast(step)) {
        load_lanes(x_, x);
        load_lanes(base_, base);
        for (int v = 0; v < kChainVectors; ++v) base_odd_[v] = odd_lanes(base_[v]);
    }

    // Records the terms as step t of block (7 - t if kReversed), then advances.
    [[gnu::always_inline]] void advance(ChainBlock& block, int t) {
#pragma GCC unroll 4
        for (int v = 0; v < kChainVectors; ++v) {
            block[v][kReversed ? 7 - t : t] = x_[v];
            x_[v] = montgomery(x_[v], odd_lanes(x_[v]), add(base_[v], u_), add(base_odd_[v], u_));
        }
        u_ = reduce(add(u_, step_), kP);
    }

private:
    Vec x_[kChainVectors], base_[kChainVectors], base_odd_[kChainVectors], u_, step_;
};

// Runs the chains for steps [0, steps), steps a multiple of 8. For each 8 steps j .. j + 7 it
// calls put(j, s, terms...) for every lane s < 32, with one vector per chain: lane t holds the
// term of step j + t (j + 7 - t for a reversed chain). The chains run 8 steps ahead of put (8
// steps past the end), so a block's transposes and stores overlap the next block's products.
template <class Put, class... Chains>
[[gnu::always_inline]] inline void scan(std::size_t steps, Put put, Chains&... chains) {
    constexpr auto kAll = std::index_sequence_for<Chains...>{};
    ChainBlock block[2][sizeof...(Chains)];
    const auto advance = [&]<std::size_t... I>(std::index_sequence<I...>, std::size_t b, int t) {
        (chains.advance(block[b][I], t), ...);
    };
    const auto emit = [&]<std::size_t... I>(std::index_sequence<I...>, std::size_t j, std::size_t b, int v, int l) {
        put(j, 8 * v + l, block[b][I][v][l]...);
    };
#pragma GCC unroll 8
    for (int t = 0; t < 8; ++t) advance(kAll, 0, t);
    for (std::size_t j = 0, cur = 0; j < steps; j += 8, cur ^= 1) {
#pragma GCC unroll 8
        for (int t = 0; t < 8; ++t) {
            advance(kAll, cur ^ 1, t);
            const int v = t / 2, first = 4 * (t % 2);
            if (first == 0)
                for (auto& b : block[cur]) transpose_steps(b[v]);
#pragma GCC unroll 4
            for (int l = first; l < first + 4; ++l) emit(kAll, j, cur, v, l);
        }
    }
}

// The lane length C of a scan over n >= 1 positions: the least C >= n / 32 that is a multiple of
// 16 with C / 16 odd, so that the 32 streams of a pass fall into different cache sets.
// 32 C <= n + 1023.
inline std::size_t scan_chunk(std::size_t n) {
    std::size_t chunk = ((n + 31) / 32 + 15) / 16 * 16;
    return chunk / 16 % 2 ? chunk : chunk + 16;
}

}  // namespace detail

// n! for n < kFactorialLimit: a table entry and at most 1023 products.
inline std::uint32_t factorial(std::uint32_t n) {
    using namespace detail;
    std::uint32_t f = kFactorialTable[n / kFactorialStep];
    for (std::uint32_t i = n / kFactorialStep * kFactorialStep + 1; i <= n; ++i) f = ntt::detail::multiply_mod(f, i);
    return f;
}

// n[s]! for n[s] < kFactorialLimit, all lanes at once: from the table entry below n[s], at most
// 1023 masked chain steps (0.007 ms on lc-amd for 32 lanes; lib/poly/notes.md).
inline Lanes factorials(const Lanes& n) {
    using namespace detail;
    Lanes start, first, count;
    std::uint32_t steps = 0;
    for (int s = 0; s < 32; ++s) {
        const std::uint32_t below = n[s] / kFactorialStep * kFactorialStep;
        start[s] = kFactorialTable[n[s] / kFactorialStep];
        first[s] = ntt::detail::multiply_mod(below + 1, kR);  // (below + 1) 2^32
        count[s] = n[s] - below;
        steps = std::max(steps, count[s]);
    }
    Vec x[kChainVectors], m[kChainVectors], left[kChainVectors];
    load_lanes(x, start), load_lanes(m, first), load_lanes(left, count);
    const Vec unit = broadcast(kR);
    for (std::uint32_t j = 0; j < steps; ++j) {
        const Vec step = broadcast(j);
#pragma GCC unroll 4
        for (int v = 0; v < kChainVectors; ++v) {
            const Vec factor = _mm256_blendv_epi8(unit, m[v], _mm256_cmpgt_epi32(left[v], step));
            x[v] = montgomery(x[v], odd_lanes(x[v]), factor, odd_lanes(factor));
            m[v] = reduce(add(m[v], unit), kP);
        }
    }
    Lanes f;
    for (int v = 0; v < kChainVectors; ++v) store_unaligned(f.data() + 8 * v, reduce(x[v], kP));
    return f;
}

// x[i] = 1 / x[i] for nonzero x[i] (Montgomery's batch inversion: 3 products each, one
// exponentiation).
inline void invert(std::span<std::uint32_t> x) {
    using ntt::detail::multiply_mod;
    if (x.empty()) return;
    std::uint32_t prefix = 1;
    std::vector<std::uint32_t> before(x.size());
    for (std::size_t i = 0; i < x.size(); ++i) before[i] = prefix, prefix = multiply_mod(prefix, x[i]);
    std::uint32_t inverse = detail::scalar_inverse(prefix);  // 1 / (x[0] ... x[i]) below
    for (std::size_t i = x.size(); i-- > 0;) {
        const std::uint32_t xi = x[i];
        x[i] = multiply_mod(inverse, before[i]);
        inverse = multiply_mod(inverse, xi);
    }
}

}  // namespace poly
