#!/usr/bin/env python3
"""Bundle a showcase solution into one file that also builds on Windows judges (Codeforces).

  showcase/bundle.py SOURCE [OUT]   as tools/bundle.py, default OUT: main.cpp next to SOURCE
  showcase/bundle.py --check        every showcase/*/*/solution.cpp must bundle to its main.cpp
  showcase/bundle.py --all          regenerate them all

Same as tools/bundle.py, except that '#include <sys/mman.h>' in a bundled header becomes
lib/easy/mman.hpp (VirtualAlloc on Windows, <sys/mman.h> elsewhere).
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / 'tools'))
import bundle as base  # noqa: E402

MMAN = ROOT / 'lib/easy/mman.hpp'
SYSTEM_MMAN = re.compile(r'\s*#\s*include\s*<sys/mman\.h>')


def inline(path: Path, seen: set[Path]) -> list[str]:
    lines = []
    for line in path.read_text().splitlines():
        match = base.INCLUDE.match(line)
        header = base.resolve(match.group(1), path) if match else None
        if header is None and path != MMAN and SYSTEM_MMAN.match(line):
            header = MMAN
        if header is not None:
            if header not in seen:
                seen.add(header)
                lines += [f'// {base.name(header)}'] + inline(header, seen)
        elif line.strip() != '#pragma once':
            lines.append(line)
    return lines


def bundle(source: Path) -> str:
    source = source.resolve()
    header = f'// Generated by showcase/bundle.py from {base.name(source)}. Edit that file instead.'
    return '\n'.join([header] + inline(source, {source})) + '\n'


def solutions() -> list[Path]:
    return sorted(ROOT.glob('showcase/*/*/solution.cpp'))


def main() -> int:
    args = sys.argv[1:]
    if args == ['--check']:
        stale = [s for s in solutions() if (s.parent / 'main.cpp').read_text() != bundle(s)]
        for s in stale:
            print(f'{s.parent.relative_to(ROOT)}/main.cpp is stale: run showcase/bundle.py --all')
        return 1 if stale else 0
    if args == ['--all']:
        for s in solutions():
            (s.parent / 'main.cpp').write_text(bundle(s))
        return 0
    if len(args) not in (1, 2):
        print(__doc__)
        return 2
    source = Path(args[0])
    out = Path(args[1]) if len(args) == 2 else source.parent / 'main.cpp'
    out.write_text(bundle(source))
    return 0


if __name__ == '__main__':
    sys.exit(main())
