// Generated by tools/bundle.py from problems/convolution/bitwise_and_convolution/solution.cpp. Edit that file instead.
// Bitwise AND convolution mod 998244353: c = mu(zeta(a) * zeta(b)), where zeta(f)[i] sums f over
// the supersets of i and mu inverts it. One level per index bit; the levels commute.
//
// Layout: 2^lg values as rows of 2^block_log values. Bands of up to 4 rows are contiguous and read
// by one Reader call; each band (of a, then of b) starts kBandSkew values after the previous one
// ends, so equal columns of the rows of a and b spread over 4 groups of cache sets (without a skew,
// the column pass takes 12 times as long). Each band's rows are transformed over their own bits
// right after it is parsed; one pass over columns then does the row-bit levels of a and b, the
// product and the inverse row-bit levels; each row then gets its inverse low levels and is printed.
#include <sys/mman.h>
#include <unistd.h>

// lib/io/io.hpp
// Fast integer and text I/O on file descriptors (stdin and stdout by default).
// Linux, x86-64 with AVX2. Design and measurements: lib/io/notes.md.
//
//   io::Reader in;                            // takes all of stdin
//   io::Writer out;                           // flushes in its destructor
//   const auto n = in.read<std::uint32_t>();
//   std::vector<std::uint32_t> a(n);
//   in.read(a.data(), n);                     // bulk; AVX2 for uint32_t
//   const auto s = in.read<std::uint64_t, 16>();  // promise: at most 16 digits (faster)
//   out.write("n = ", n, '\n');               // any mix of integers, chars, strings
//   out.write<16>(s, '\n');                   // promise: integers of at most 16 digits
//   out.write_array(a.data(), n, ' ');        // bulk; AVX2 for uint32_t
//   out.write('\n');
//
// Input: tokens separated by whitespace (any bytes <= ' '). Integer tokens are an optional '-'
// (signed types only) followed by decimal digits, and fit the requested type. Reading past the
// last token is undefined. The 64 bytes before the input and after its end are readable zeros, so
// custom parsers may load up to 64 bytes around any token from word().

#include <fcntl.h>
#include <immintrin.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <unistd.h>

#include <algorithm>
#include <array>
#include <bit>
#include <cerrno>
#include <concepts>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <string_view>
#include <type_traits>

namespace io {
namespace detail {

// Zero bytes before and after the input. Loads reach at most 63 bytes past either end.
inline constexpr std::size_t kPadding = 64;
inline constexpr std::size_t kPage = 4096;

// Input as mapped or read: data [start, end), kPadding zero bytes before and after it.
struct Input {
    char* base;           // allocation or mapping to release
    std::size_t mapped;   // bytes mapped, or 0 for a heap buffer
    const char* start;
    const char* end;
};

inline Input map_input(int fd, std::size_t size) {
    const off_t offset = ::lseek(fd, 0, SEEK_CUR);
    if (offset < 0 || std::size_t(offset) >= size) return {};
    // One anonymous zero page before the file. After it, the rest of the last file page reads as
    // zero; if fewer than kPadding bytes remain, one more anonymous page follows.
    const std::size_t file_bytes = (size + kPage - 1) & ~(kPage - 1);
    const std::size_t mapped = kPage + file_bytes + (file_bytes - size < kPadding ? kPage : 0);
    void* base = ::mmap(nullptr, mapped, PROT_READ, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
    if (base == MAP_FAILED) return {};
    char* const file = static_cast<char*>(base) + kPage;
    if (::mmap(file, file_bytes, PROT_READ, MAP_PRIVATE | MAP_FIXED, fd, 0) == MAP_FAILED) {
        ::munmap(base, mapped);
        return {};
    }
    return {static_cast<char*>(base), mapped, file + offset, file + size};
}

// Capacity bytes for data, with kPadding bytes before and after; returns the data start.
inline char* allocate(std::size_t capacity) {
    auto* p = static_cast<char*>(std::aligned_alloc(64, capacity + 2 * kPadding));
    if (!p) std::abort();
    std::memset(p, 0, kPadding);
    return p + kPadding;
}

// Reads fd until end of file, or until size bytes for a regular file of that size.
inline Input read_input(int fd, std::size_t size = std::size_t(-1)) {
    std::size_t done = 0, capacity = std::size_t(1) << 16;
    char* data = allocate(capacity);
    while (done < size) {
        if (done == capacity) {
            char* bigger = allocate(capacity *= 2);
            std::memcpy(bigger, data, done);
            std::free(data - kPadding);
            data = bigger;
        }
        const ssize_t got = ::read(fd, data + done, capacity - done);
        if (got > 0) done += std::size_t(got);
        else if (got == 0) break;
        else if (errno != EINTR) std::abort();
    }
    std::memset(data + done, 0, kPadding);
    return {data - kPadding, 0, data, data + done};
}

// Files over kMapAbove bytes are mapped; smaller ones and other inputs are read, which takes
// fewer system calls.
inline constexpr std::size_t kMapAbove = std::size_t(1) << 16;

inline Input open_input(int fd) {
    struct stat st;
    if (::fstat(fd, &st) == 0 && S_ISREG(st.st_mode)) {
        const auto size = std::size_t(st.st_size);
        if (size <= kMapAbove) return read_input(fd, size);
        if (const Input input = map_input(fd, size); input.base) return input;
    }
    return read_input(fd);
}

inline void release(const Input& input) {
    if (input.mapped) ::munmap(input.base, input.mapped);
    else std::free(input.base);
}

// Bit i set iff byte i is whitespace (<= ' ').
inline unsigned separators(__m128i bytes) {
    return unsigned(_mm_movemask_epi8(_mm_cmpgt_epi8(_mm_set1_epi8(' ' + 1), bytes)));
}

inline std::uint32_t separators(__m256i bytes) {
    return std::uint32_t(_mm256_movemask_epi8(_mm256_cmpgt_epi8(_mm256_set1_epi8(' ' + 1), bytes)));
}

// Separators in the 64-byte aligned block.
inline std::uint64_t block_separators(const char* block) {
    const std::uint64_t low = separators(_mm256_load_si256(reinterpret_cast<const __m256i*>(block)));
    const std::uint64_t high = separators(_mm256_load_si256(reinterpret_cast<const __m256i*>(block + 32)));
    return low | high << 32;
}

// The 16 bytes at kRightAlign[n + 1] move the first n bytes (1 <= n <= 16) of a 16-byte window
// to its end and zero the rest: byte k + 1 is k - 16 for 16 <= k < 32, else -128. For the other
// lengths (-1, 0, 17..32) byte 15 of the window is negative, which marks the token as invalid.
alignas(64) inline constexpr auto kRightAlign = [] {
    std::array<std::int8_t, 64> t{};
    for (int k = -1; k < 63; ++k) t[k + 1] = k >= 16 && k < 32 ? std::int8_t(k - 16) : std::int8_t(-128);
    return t;
}();

// Shuffle control for a token of length index - 1.
inline __m128i align_row(std::size_t index) {
    return _mm_loadu_si128(reinterpret_cast<const __m128i*>(kRightAlign.data() + index));
}

// Right-aligned digits (byte values 0..9) -> 4-digit groups, one per dword.
inline __m128i digit_groups(__m128i digits) {
    return _mm_madd_epi16(_mm_maddubs_epi16(digits, _mm_set1_epi16(0x010A)), _mm_set1_epi32(0x00010064));
}

inline __m256i digit_groups(__m256i digits) {
    return _mm256_madd_epi16(_mm256_maddubs_epi16(digits, _mm256_set1_epi16(0x010A)), _mm256_set1_epi32(0x00010064));
}

// Value of the first n digits (0 <= n <= 16) of the window. Result < 10^16.
inline std::uint64_t parse16(__m128i window, unsigned n) {
    const __m128i digits = _mm_shuffle_epi8(_mm_subs_epu8(window, _mm_set1_epi8('0')), align_row(n + 1));
    const __m128i groups = digit_groups(digits);
    const __m128i halves = _mm_madd_epi16(_mm_packus_epi32(groups, groups), _mm_set1_epi32(0x00012710));
    const auto both = std::uint64_t(_mm_cvtsi128_si64(halves));  // 8-digit halves, high one first
    return (both & 0xFFFFFFFF) * 100000000 + (both >> 32);
}

// kKeep[32 - k..64 - k) keeps the last k bytes of 32.
alignas(64) inline constexpr auto kKeep = [] {
    std::array<std::uint8_t, 64> t{};
    for (std::size_t i = 32; i < 64; ++i) t[i] = 0xFF;
    return t;
}();

// Value of the n <= 16 digits that end at end. Bytes below '0' before them (a sign) count as 0.
inline std::uint64_t parse_ending16(const char* end, unsigned n) {
    const __m128i bytes = _mm_loadu_si128(reinterpret_cast<const __m128i*>(end - 16));
    const __m128i keep = _mm_loadu_si128(reinterpret_cast<const __m128i*>(kKeep.data() + 16 + n));
    const __m128i groups = digit_groups(_mm_and_si128(_mm_subs_epu8(bytes, _mm_set1_epi8('0')), keep));
    const __m128i halves = _mm_madd_epi16(_mm_packus_epi32(groups, groups), _mm_set1_epi32(0x00012710));
    const auto both = std::uint64_t(_mm_cvtsi128_si64(halves));  // 8-digit halves, high one first
    return (both & 0xFFFFFFFF) * 100000000 + (both >> 32);
}

// Value of the n <= 24 digits that end at end; at most 20 for a result below 2^64.
inline std::uint64_t parse_ending24(const char* end, unsigned n) {
    const __m256i bytes = _mm256_loadu_si256(reinterpret_cast<const __m256i*>(end - 32));
    const __m256i keep = _mm256_loadu_si256(reinterpret_cast<const __m256i*>(kKeep.data() + n));
    const __m256i groups = digit_groups(_mm256_and_si256(_mm256_subs_epu8(bytes, _mm256_set1_epi8('0')), keep));
    // 8-digit quarters; the first is 0. Dword 1 of the low lane, dwords 0 and 1 of the high lane.
    const __m256i quarters = _mm256_madd_epi16(_mm256_packus_epi32(groups, groups), _mm256_set1_epi32(0x00012710));
    const std::uint64_t high = std::uint64_t(_mm256_extract_epi64(quarters, 0)) >> 32;
    const auto low = std::uint64_t(_mm256_extract_epi64(quarters, 2));
    return (high * 100000000 + (low & 0xFFFFFFFF)) * 100000000 + (low >> 32);
}

// kQuad[x] for x < 10^4: its 4 digits with leading zeros, first digit in the lowest byte.
alignas(64) inline constexpr auto kQuad = [] {
    std::array<std::uint32_t, 10000> t{};
    for (std::uint32_t x = 0; x < t.size(); ++x)
        t[x] = ('0' + x / 1000) | ('0' + x / 100 % 10) << 8 | ('0' + x / 10 % 10) << 16 | ('0' + x % 10) << 24;
    return t;
}();

// Digits of x (x >= 1) = (x + kDigitCount32[floor(log2(x))]) >> 32: the low word of an entry
// carries into the high word exactly when x reaches the next power of ten.
inline constexpr auto kDigitCount32 = [] {
    std::array<std::uint64_t, 32> t{};
    for (int i = 0; i < 32; ++i) {
        const std::uint64_t low = std::uint64_t(1) << i, high = 2 * low - 1;
        std::uint64_t digits = 0, power = 1;
        while (power <= low) power *= 10, ++digits;
        t[i] = (digits << 32) + (power <= high ? (std::uint64_t(1) << 32) - power : 0);
    }
    return t;
}();

inline unsigned digit_count(std::uint32_t x) {
    return unsigned((x + kDigitCount32[31 - std::countl_zero(x | 1)]) >> 32);
}

// Digits of x = kDigitCount64[0][b] + (x > kDigitCount64[1][b]), where b = bit width of x | 1.
inline constexpr auto kDigitCount64 = [] {
    std::array<std::array<std::uint64_t, 65>, 2> t{};
    for (int b = 1; b <= 64; ++b) {
        const unsigned __int128 low = (unsigned __int128)1 << (b - 1), high = 2 * low - 1;
        std::uint64_t digits = 1;
        unsigned __int128 power = 10;
        while (power <= low) power *= 10, ++digits;
        t[0][b] = digits;
        t[1][b] = power <= high ? std::uint64_t(power - 1) : ~std::uint64_t(0);
    }
    return t;
}();

inline unsigned digit_count(std::uint64_t x) {
    const int b = std::bit_width(x | 1);
    return unsigned(kDigitCount64[0][b] + (x > kDigitCount64[1][b]));
}

// Bytes kShiftWindow[k..k + 16) shuffle a vector down by k bytes.
alignas(32) inline constexpr std::int8_t kShiftWindow[32] = {0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  10,
                                                             11, 12, 13, 14, 15, -1, -1, -1, -1, -1, -1,
                                                             -1, -1, -1, -1, -1, -1, -1, -1, -1, -1};

inline __m128i shift_down(__m128i v, unsigned k) {
    return _mm_shuffle_epi8(v, _mm_loadu_si128(reinterpret_cast<const __m128i*>(kShiftWindow + k)));
}

// Writes x in decimal at p and returns the end. Stores 16 bytes.
inline char* format(char* p, std::uint32_t x) {
    // Twelve digits with leading zeros, as three groups of four, then shifted down past the zeros.
    const std::uint32_t top = x / 100000000, rest = x % 100000000;
    const std::uint32_t high = rest / 10000, low = rest % 10000;
    const __m128i digits = _mm_insert_epi32(
        _mm_cvtsi64_si128(std::int64_t(kQuad[top] | std::uint64_t(kQuad[high]) << 32)), int(kQuad[low]), 2);
    const unsigned n = digit_count(x);
    _mm_storeu_si128(reinterpret_cast<__m128i*>(p), shift_down(digits, 12 - n));
    return p + n;
}

// high, low < 10^8 as 16 digits with leading zeros.
inline __m128i sixteen_digits(std::uint32_t high, std::uint32_t low) {
    return _mm_set_epi64x(std::int64_t(kQuad[low / 10000] | std::uint64_t(kQuad[low % 10000]) << 32),
                          std::int64_t(kQuad[high / 10000] | std::uint64_t(kQuad[high % 10000]) << 32));
}

// Writes x in decimal at p and returns the end. Stores up to 20 bytes. MaxDigits <= 16 promises
// x < 10^16, which saves a division.
template <int MaxDigits>
inline char* format64(char* p, std::uint64_t x) {
    const std::uint64_t q = x / 100000000;  // < 1.9 * 10^11
    const auto low = std::uint32_t(x - q * 100000000);
    const unsigned n = digit_count(x);
    if constexpr (MaxDigits <= 16) {
        _mm_storeu_si128(reinterpret_cast<__m128i*>(p), shift_down(sixteen_digits(std::uint32_t(q), low), 16 - n));
        return p + n;
    } else {
        // Twenty digits with leading zeros: a head of four, then sixteen.
        const auto top = std::uint32_t(q / 100000000);  // < 1845
        const auto middle = std::uint32_t(q - std::uint64_t(top) * 100000000);
        const unsigned head = n > 16 ? n - 16 : 0;
        const auto head_digits = std::uint32_t(std::uint64_t(kQuad[top]) >> (32 - 8 * head));
        std::memcpy(p, &head_digits, 4);
        _mm_storeu_si128(reinterpret_cast<__m128i*>(p + head), shift_down(sixteen_digits(middle, low), 16 - (n - head)));
        return p + n;
    }
}

// floor(x / d) for every dword x, as (x * Magic) >> Shift. The test checks each use exhaustively.
template <std::uint32_t Magic, int Shift>
inline __m256i divide(__m256i x) {
    const __m256i magic = _mm256_set1_epi64x(Magic);
    const __m256i even = _mm256_srli_epi64(_mm256_mul_epu32(x, magic), Shift);
    const __m256i odd = _mm256_srli_epi64(_mm256_mul_epu32(_mm256_srli_epi64(x, 32), magic), Shift);
    return _mm256_blend_epi32(even, _mm256_slli_epi64(odd, 32), 0xAA);
}

// Each dword g < 10^4 -> its 4 ASCII digits, first digit in the lowest byte.
inline __m256i quad_digits(__m256i g) {
    const __m256i high = _mm256_srli_epi16(_mm256_mulhi_epu16(g, _mm256_set1_epi16(5243)), 3);  // g / 100
    const __m256i low = _mm256_sub_epi16(g, _mm256_mullo_epi16(high, _mm256_set1_epi16(100)));
    const __m256i pairs = _mm256_or_si256(high, _mm256_slli_epi32(low, 16));  // 16-bit halves < 100
    const __m256i tens = _mm256_mulhi_epu16(pairs, _mm256_set1_epi16(6554));  // pair / 10
    const __m256i units = _mm256_sub_epi16(pairs, _mm256_mullo_epi16(tens, _mm256_set1_epi16(10)));
    return _mm256_or_si256(_mm256_or_si256(tens, _mm256_slli_epi16(units, 8)), _mm256_set1_epi8('0'));
}

// Digit counts of the eight dwords of v, one per byte in order.
inline std::uint64_t digit_counts(__m256i v) {
    // Unsigned v >= 10^k via a signed compare after flipping the sign bits; summed as a tree.
    const __m256i x = _mm256_xor_si256(v, _mm256_set1_epi32(int(0x80000000)));
    const auto at_least = [&](std::uint32_t power) {
        return _mm256_cmpgt_epi32(x, _mm256_set1_epi32(int((power - 1) ^ 0x80000000)));
    };
    const __m256i a = _mm256_add_epi32(_mm256_add_epi32(at_least(10), at_least(100)),
                                       _mm256_add_epi32(at_least(1000), at_least(10000)));
    const __m256i b = _mm256_add_epi32(_mm256_add_epi32(at_least(100000), at_least(1000000)),
                                       _mm256_add_epi32(at_least(10000000), at_least(100000000)));
    const __m256i n = _mm256_sub_epi32(_mm256_sub_epi32(_mm256_set1_epi32(1), at_least(1000000000)),
                                       _mm256_add_epi32(a, b));
    const __m256i bytes = _mm256_packus_epi16(_mm256_packus_epi32(n, n), n);  // per lane: 4 counts first
    return std::uint64_t(_mm256_extract_epi32(bytes, 0)) | std::uint64_t(_mm256_extract_epi32(bytes, 4)) << 32;
}

// Stores the two 16-byte lanes of w, values of 12 digits with leading zeros and a separator, as
// their last n0 and n1 digits and the separator. Returns the end; stores 16 bytes per lane.
inline char* put_pair(char* p, __m256i w, unsigned n0, unsigned n1) {
    const __m256i shifted = _mm256_shuffle_epi8(w, _mm256_loadu2_m128i(
        reinterpret_cast<const __m128i*>(kShiftWindow + 12 - n1), reinterpret_cast<const __m128i*>(kShiftWindow + 12 - n0)));
    _mm_storeu_si128(reinterpret_cast<__m128i*>(p), _mm256_castsi256_si128(shifted));
    p += n0 + 1;
    _mm_storeu_si128(reinterpret_cast<__m128i*>(p), _mm256_extracti128_si256(shifted, 1));
    return p + n1 + 1;
}

// Writes the eight dwords of v in decimal, each followed by separator, and returns the end.
// Stores up to 15 bytes past the end.
inline char* format8(char* p, __m256i v, char separator) {
    // Digit counts first, from v: the store addresses then do not wait for the digits.
    const std::uint64_t n = digit_counts(v);
    // Lanes [v0 v2 v4 v6 | v1 v3 v5 v7], so the transpose below pairs consecutive values.
    v = _mm256_permutevar8x32_epi32(v, _mm256_setr_epi32(0, 2, 4, 6, 1, 3, 5, 7));
    const __m256i top = divide<1441151881, 57>(v);  // v / 10^8
    const __m256i rest = _mm256_sub_epi32(v, _mm256_mullo_epi32(top, _mm256_set1_epi32(100000000)));
    const __m256i high = divide<3518437209, 45>(rest);  // rest / 10^4
    const __m256i low = _mm256_sub_epi32(rest, _mm256_madd_epi16(high, _mm256_set1_epi32(10000)));
    const __m256i t = quad_digits(top), h = quad_digits(high), l = quad_digits(low);
    const __m256i s = _mm256_set1_epi32(static_cast<unsigned char>(separator));
    // Transpose: each 16-byte lane becomes one value as dwords [top, high, low, separator].
    const __m256i th_low = _mm256_unpacklo_epi32(t, h), th_high = _mm256_unpackhi_epi32(t, h);
    const __m256i ls_low = _mm256_unpacklo_epi32(l, s), ls_high = _mm256_unpackhi_epi32(l, s);
    const auto count = [n](int i) { return unsigned(n >> 8 * i & 0xFF); };
    p = put_pair(p, _mm256_unpacklo_epi64(th_low, ls_low), count(0), count(1));
    p = put_pair(p, _mm256_unpackhi_epi64(th_low, ls_low), count(2), count(3));
    p = put_pair(p, _mm256_unpacklo_epi64(th_high, ls_high), count(4), count(5));
    return put_pair(p, _mm256_unpackhi_epi64(th_high, ls_high), count(6), count(7));
}

// Parses uint32 tokens from the token at p into dst: at most count, from input that is valid up
// to limit. Stops when fewer than kMinTokens tokens or 1 KiB of input remain. Returns where it
// stopped and the tokens parsed. Each chunk of input is cut
// into four streams at token boundaries. The streams advance in lockstep, two tokens per step, so
// four independent pointer chains overlap.
class BulkParser {
public:
    static constexpr std::size_t kMinTokens = 1024;

    struct Result {
        const char* end;
        std::size_t parsed;
    };

    static Result parse(const char* p, const char* limit, std::uint32_t* dst, std::size_t count) {
        std::uint32_t* const first = dst;
        while (count >= kMinTokens && limit - p >= 1024 + 64) {
            // With tokens of at most 16 bytes a chunk spans at most chunk + 33 bytes, so it holds
            // at most chunk / 2 + 17 < count tokens: all of them belong to this array. It ends
            // before limit.
            const std::size_t chunk =
                std::min({kChunk, 2 * (count - 32), std::size_t(limit - p) - 64}) & ~std::size_t(3);
            const std::size_t stream = chunk / 4;
            const char* s[4] = {p, after_separator(p + stream), after_separator(p + 2 * stream),
                                after_separator(p + 3 * stream)};
            const char* const end[4] = {s[1], s[2], s[3], after_separator(p + chunk)};
            std::uint32_t* const out[4] = {dst, scratch_[0], scratch_[1], scratch_[2]};
            __m256i invalid = _mm256_setzero_si256();
            const std::size_t done = lockstep(s, end, out, invalid);
            std::size_t n[4];
            bool overrun = false;
            for (int k = 0; k < 4; ++k) {
                n[k] = done;
                while (s[k] < end[k] && n[k] < kCapacity) out[k][n[k]++] = one_token(s[k], invalid);
                overrun |= s[k] != end[k];
            }
            if (overrun || (std::uint32_t(_mm256_movemask_epi8(invalid)) & 0x80008000)) [[unlikely]] {
                // Irregular whitespace or tokens: this chunk one token at a time.
                const std::size_t tokens = std::min(count_tokens(p, end[3]), count);
                p = parse_slowly(p, dst, tokens);
                dst += tokens;
                count -= tokens;
                continue;
            }
            std::uint32_t* next = dst + n[0];
            for (int k = 1; k < 4; ++k) {
                std::memcpy(next, out[k], n[k] * sizeof(std::uint32_t));
                next += n[k];
            }
            dst = next;
            count -= n[0] + n[1] + n[2] + n[3];
            p = skip_whitespace(end[3]);
        }
        return {p, std::size_t(dst - first)};
    }

private:
    static constexpr std::size_t kChunk = std::size_t(1) << 17;
    // A step advances a stream by 2..33 bytes and yields two values, so a stream of at most
    // kChunk / 4 + 33 bytes yields at most kChunk / 4 + 66 values.
    static constexpr std::size_t kCapacity = kChunk / 4 + 66;
    alignas(64) static inline std::uint32_t scratch_[3][kCapacity];

    // Steps all streams while each has 33 bytes left; returns the values per stream. Works on
    // local copies of the stream state, which stay in registers.
    static std::size_t lockstep(const char* (&streams)[4], const char* const (&end)[4],
                                std::uint32_t* const (&outputs)[4], __m256i& flags) {
        const char* s[4] = {streams[0], streams[1], streams[2], streams[3]};
        std::uint32_t* const out[4] = {outputs[0], outputs[1], outputs[2], outputs[3]};
        __m256i invalid = flags;
        std::size_t done = 0;
        for (;;) {
            std::ptrdiff_t left = end[0] - s[0];
            for (int k = 1; k < 4; ++k) left = std::min(left, end[k] - s[k]);
            if (left < 33) break;
            for (std::ptrdiff_t steps = left / 33; steps; --steps, done += 2) {
                const __m256i g0 = two_tokens(s[0], invalid), g1 = two_tokens(s[1], invalid);
                const __m256i g2 = two_tokens(s[2], invalid), g3 = two_tokens(s[3], invalid);
                const __m256i k = _mm256_set1_epi32(0x00012710);
                // 8-digit halves: [s0 high, s0 low, s1 high, s1 low | second tokens likewise].
                const __m256 h01 = _mm256_castsi256_ps(_mm256_madd_epi16(_mm256_packus_epi32(g0, g1), k));
                const __m256 h23 = _mm256_castsi256_ps(_mm256_madd_epi16(_mm256_packus_epi32(g2, g3), k));
                const __m256i high = _mm256_castps_si256(_mm256_shuffle_ps(h01, h23, 0x88));
                const __m256i low = _mm256_castps_si256(_mm256_shuffle_ps(h01, h23, 0xDD));
                const __m256i v = _mm256_add_epi32(_mm256_mullo_epi32(high, _mm256_set1_epi32(100000000)), low);
                // [s0 a, s0 b, s1 a, s1 b | s2 a, s2 b, s3 a, s3 b]
                const __m256i q = _mm256_permutevar8x32_epi32(v, _mm256_setr_epi32(0, 4, 1, 5, 2, 6, 3, 7));
                const __m128i q01 = _mm256_castsi256_si128(q), q23 = _mm256_extracti128_si256(q, 1);
                _mm_storel_epi64(reinterpret_cast<__m128i*>(out[0] + done), q01);
                _mm_storeh_pd(reinterpret_cast<double*>(out[1] + done), _mm_castsi128_pd(q01));
                _mm_storel_epi64(reinterpret_cast<__m128i*>(out[2] + done), q23);
                _mm_storeh_pd(reinterpret_cast<double*>(out[3] + done), _mm_castsi128_pd(q23));
            }
        }
        for (int k = 0; k < 4; ++k) streams[k] = s[k];
        flags = invalid;
        return done;
    }

    // Two tokens at s, as 4-digit groups [first | second]. Lengths outside 1..16 (repeated
    // whitespace, long tokens) set the sign bit of byte 15 or 31 of invalid.
    [[gnu::always_inline]] static __m256i two_tokens(const char*& s, __m256i& invalid) {
        const __m256i bytes = _mm256_loadu_si256(reinterpret_cast<const __m256i*>(s));
        const std::uint32_t sep = separators(bytes);
        const auto first = std::size_t(std::countr_zero(sep));              // length of the first token
        const auto second = std::size_t(std::countr_zero(sep & (sep - 1)));  // 32 if none
        const __m256i windows =
            _mm256_inserti128_si256(bytes, _mm_loadu_si128(reinterpret_cast<const __m128i*>(s + first + 1)), 1);
        const __m256i rows = _mm256_set_m128i(align_row(second - first), align_row(first + 1));
        invalid = _mm256_or_si256(invalid, rows);
        s += second + 1;
        return digit_groups(_mm256_shuffle_epi8(_mm256_subs_epu8(windows, _mm256_set1_epi8('0')), rows));
    }

    static std::uint32_t one_token(const char*& s, __m256i& invalid) {
        const __m128i window = _mm_loadu_si128(reinterpret_cast<const __m128i*>(s));
        const unsigned n = unsigned(std::countr_zero(separators(window) | 0x10000));
        invalid = _mm256_or_si256(invalid, _mm256_castsi128_si256(align_row(n + 1)));
        s += n + 1;
        return std::uint32_t(parse16(window, n));
    }

    // The byte after the first separator at or after q.
    static const char* after_separator(const char* q) {
        for (;; q += 32)
            if (const std::uint32_t sep = separators(_mm256_loadu_si256(reinterpret_cast<const __m256i*>(q))))
                return q + std::countr_zero(sep) + 1;
    }

    static const char* skip_whitespace(const char* p) {
        while (static_cast<unsigned char>(*p) <= ' ') ++p;
        return p;
    }

    // Tokens in [p, end), where p starts a token.
    static std::size_t count_tokens(const char* p, const char* end) {
        std::size_t tokens = 1;
        for (const char* q = p + 1; q < end; ++q)
            tokens += static_cast<unsigned char>(*q) > ' ' && static_cast<unsigned char>(q[-1]) <= ' ';
        return tokens;
    }

    static const char* parse_slowly(const char* p, std::uint32_t* dst, std::size_t count) {
        for (std::size_t i = 0; i < count; ++i) {
            p = skip_whitespace(p);
            const __m128i window = _mm_loadu_si128(reinterpret_cast<const __m128i*>(p));
            const unsigned n = unsigned(std::countr_zero(separators(window) | 0x10000));
            dst[i] = std::uint32_t(parse16(window, n));
            p += n + 1;
        }
        return p;
    }
};

}  // namespace detail

// Token boundaries come from separator bitmasks of aligned 64-byte blocks: finding the next token
// clears one bit, so consecutive reads do not wait on each other's parsing.
class Reader {
public:
    // Takes everything that remains on fd (stdin by default).
    explicit Reader(int fd = 0) : input_(detail::open_input(fd)) { seek(input_.start); }

    ~Reader() { detail::release(input_); }

    Reader(const Reader&) = delete;
    Reader& operator=(const Reader&) = delete;

    // Next integer token, or the next non-whitespace character for char. MaxDigits, if set, promises
    // at most that many digits; for 64-bit types, 16 or fewer selects a faster parser.
    // Non-negative values parse faster as unsigned types (10-18%, see notes.md).
    template <class T, int MaxDigits = 0>
        requires std::integral<T> && (!std::same_as<T, bool>)
    T read() {
        if constexpr (std::same_as<T, char>) {
            skip_whitespace();
            return *cur_++;
        } else {
            const auto [start, length] = next_token();
            // A leading '-' sits below '0' and parses as a zero digit.
            const auto magnitude = parse<(sizeof(T) > 4), MaxDigits>(start + length, length);
            if constexpr (std::is_unsigned_v<T>) return T(magnitude);
            else return T(*start == '-' ? 0 - magnitude : magnitude);
        }
    }

    // count tokens into dst. uint32_t uses the AVX2 bulk parser; other types read one by one.
    template <int MaxDigits = 0, class T>
    void read(T* dst, std::size_t count) {
        if constexpr (std::same_as<T, std::uint32_t>) {
            skip_whitespace();
            const auto [stop, parsed] = detail::BulkParser::parse(cur_, input_.end, dst, count);
            seek(stop);
            for (std::size_t i = parsed; i < count; ++i) dst[i] = read<T>();
        } else {
            for (std::size_t i = 0; i < count; ++i) dst[i] = read<T, MaxDigits>();
        }
    }

    // Next token; valid while the Reader lives.
    std::string_view word() {
        const auto [start, length] = next_token();
        return {start, length};
    }

    // Tokenizer state, for custom token loops. separators has one bit per whitespace byte of the
    // 64-byte block at block, at or after cur. The lowest bit is the end of the token at cur: clear
    // it to move on. With no bits left, advance block by 64 and take detail::block_separators.
    struct Scan {
        const char* cur;
        const char* block;
        std::uint64_t separators;
    };

    Scan scan() const { return {cur_, block_, separators_}; }

    void resume(const Scan& scan) {
        cur_ = scan.cur;
        block_ = scan.block;
        separators_ = scan.separators;
    }

private:
    struct Token {
        const char* start;
        unsigned length;
    };

    // Continue reading at p.
    void seek(const char* p) {
        cur_ = p;
        block_ = reinterpret_cast<const char*>(reinterpret_cast<std::uintptr_t>(p) & ~std::uintptr_t(63));
        separators_ = detail::block_separators(block_) & ~std::uint64_t(0) << (cur_ - block_);
    }

    // Position of the next separator; at or after cur_.
    const char* next_separator() {
        while (!separators_) [[unlikely]] {
            block_ += 64;
            separators_ = detail::block_separators(block_);
        }
        return block_ + std::countr_zero(separators_);
    }

    void skip_whitespace() {
        while (next_separator() == cur_) {
            separators_ &= separators_ - 1;
            ++cur_;
        }
    }

    Token next_token() {
        for (;;) {
            const char* end = next_separator();
            separators_ &= separators_ - 1;
            const char* start = cur_;
            cur_ = end + 1;
            if (end != start) [[likely]] return {start, unsigned(end - start)};
        }
    }

    // Value of the n characters that end at end.
    template <bool Wide, int MaxDigits>
    static auto parse(const char* end, unsigned n) {
        if constexpr (!Wide) return std::uint32_t(detail::parse_ending16(end, n));
        else if constexpr (MaxDigits > 0 && MaxDigits <= 16) return detail::parse_ending16(end, n);
        else return detail::parse_ending24(end, n);
    }

    detail::Input input_;
    const char* cur_;             // next unread byte
    const char* block_;           // 64-byte block holding the next separator
    std::uint64_t separators_;    // separators in block_ at or after cur_
};

// Buffered output. write() takes any mix of integers, chars and strings:
//   out.write(x, ' ', y, '\n');
// MaxDigits, if set, promises integers of at most that many digits; for 64-bit types, 16 or fewer
// selects a faster formatter: out.write<16>(sum, '\n').
class Writer {
public:
    explicit Writer(int fd = 1) : fd_(fd) {}
    ~Writer() { flush(); }

    Writer(const Writer&) = delete;
    Writer& operator=(const Writer&) = delete;

    template <int MaxDigits = 0, class... Ts>
    void write(const Ts&... values) {
        const std::size_t needed = (std::size_t(0) + ... + max_size(values));
        if (needed > kCapacity) [[unlikely]] {
            (write_alone<MaxDigits>(values), ...);
            return;
        }
        if (std::size_t(buffer_ + kCapacity - cur_) < needed) [[unlikely]] flush();
        char* p = cur_;
        ((p = put<MaxDigits>(p, values)), ...);
        cur_ = p;
    }

    // Custom formatting: fill(p) may store up to max_size <= 64 KiB bytes at p and returns the end
    // of what it wrote.
    template <class Fill>
    void write_with(std::size_t max_size, Fill fill) {
        if (std::size_t(buffer_ + kCapacity - cur_) < max_size) [[unlikely]] flush();
        cur_ = fill(cur_);
    }

    // values[0..count) joined by separator. uint32_t uses the AVX2 formatter.
    template <int MaxDigits = 0, class T>
    void write_array(const T* values, std::size_t count, char separator) {
        if (!count) return;
        std::size_t i = 0;
        if constexpr (std::same_as<T, std::uint32_t>) {
            constexpr std::size_t kBatch = 8 * 11 + 16;  // eight values and separators, plus overhang
            char* p = cur_;
            for (; i + 8 <= count; i += 8) {
                if (std::size_t(buffer_ + kCapacity - p) < kBatch) [[unlikely]] {
                    cur_ = p;
                    flush();
                    p = cur_;
                }
                p = detail::format8(p, _mm256_loadu_si256(reinterpret_cast<const __m256i*>(values + i)), separator);
            }
            cur_ = p;
        }
        for (; i < count; ++i) write<MaxDigits>(values[i], separator);
        --cur_;  // no separator after the last value
    }

    void flush() {
        write_all(fd_, buffer_, std::size_t(cur_ - buffer_));
        cur_ = buffer_;
    }

private:
    static constexpr std::size_t kCapacity = std::size_t(1) << 16;

    template <class T>
    static constexpr bool kInteger = std::integral<T> && !std::same_as<T, char> && !std::same_as<T, bool>;

    // Bytes put() may store, which can exceed what it writes.
    template <class T>
    static std::size_t max_size(const T& value) {
        if constexpr (std::same_as<T, char>) return 1;
        else if constexpr (kInteger<T>) return 1 + 20;  // a sign, then format() stores up to 20 bytes
        else return std::string_view(value).size();
    }

    template <int MaxDigits, class T>
    static char* put(char* p, const T& value) {
        if constexpr (std::same_as<T, char>) {
            *p = value;
            return p + 1;
        } else if constexpr (kInteger<T>) {
            using U = std::conditional_t<sizeof(T) <= 4, std::uint32_t, std::uint64_t>;
            if constexpr (std::is_signed_v<T>) {
                *p = '-';
                p += value < 0;
                return put<MaxDigits>(p, value < 0 ? U(0 - U(value)) : U(value));
            } else if constexpr (sizeof(T) <= 4) {
                return detail::format(p, U(value));
            } else {
                return detail::format64<MaxDigits == 0 ? 20 : MaxDigits>(p, U(value));
            }
        } else {
            const std::string_view s(value);
            std::memcpy(p, s.data(), s.size());
            return p + s.size();
        }
    }

    // A value longer than the buffer: flush, then write it directly.
    template <int MaxDigits, class T>
    void write_alone(const T& value) {
        if constexpr (std::same_as<T, char> || kInteger<T>) {
            write<MaxDigits>(value);
        } else {
            flush();
            const std::string_view s(value);
            write_all(fd_, s.data(), s.size());
        }
    }

    static void write_all(int fd, const char* data, std::size_t size) {
        while (size) {
            const ssize_t put = ::write(fd, data, size);
            if (put > 0) data += put, size -= std::size_t(put);
            else if (put < 0 && errno == EINTR) continue;
            else std::abort();
        }
    }

    int fd_;
    char* cur_ = buffer_;
    alignas(64) char buffer_[kCapacity];
};

}  // namespace io
// problems/convolution/fixed_width.hpp
// Fixed-width output of residues < 10^9: each value right-aligned in 9 characters, then a space;
// the last separator is a newline. Judge-specific: the checker compares tokens, so the padding is
// accepted. No branches on value size, and four 32-byte stores per eight values.


namespace fixed_width {

namespace detail {

struct alignas(32) Lanes {
    std::uint32_t lane[8];
};

constexpr Lanes all(std::uint32_t x) { return {{x, x, x, x, x, x, x, x}}; }

constexpr Lanes bytes(const int (&b)[32]) {
    Lanes t{};
    for (int i = 0; i < 32; ++i) t.lane[i / 4] |= std::uint32_t(b[i] & 0xFF) << 8 * (i % 4);
    return t;
}

constexpr int x = 0x80;  // shuffle control: zero byte

struct Constants {
    Lanes div4 = all(3518437209), div8 = all(720575941);  // ceil(2^45 / 10^4), ceil(2^56 / 10^8)
    Lanes ten4 = all(10000);
    Lanes by100 = all(0x147B147B), hundreds_up = all(65436);  // 5243 in each 16-bit half
    Lanes by10 = all(0x199A199A), tens_up = all(0x00F600F6);  // 6554 and 246 in each half
    Lanes zero = all(0x30303030), lead = all(0x20000020), lead_shown = all(0x10);
    // max_below[e] = 10^e - 1; blank masks for the low and high digit dwords, and the shift
    // offset of the high one (its digits come 4 after the low ones: 8 * 3 bits).
    Lanes max_below[9] = {all(0),     all(9),      all(99),      all(999),     all(9999),
                          all(99999), all(999999), all(9999999), all(99999999)};
    Lanes blank_low = all(0x10101000), blank_high = all(0x10101010), high_offset = all(24);
    // Two fields from one lane's [high_i, low_i, high_i+1, low_i+1] digit dwords, copied to both
    // lanes; the 9th digits (bytes 0, 10) and separators (9, 19) come from lead dwords j, j + 1.
    Lanes order = bytes({x, 3, 2, 1, 0, 7, 6, 5, 4, x, x, 11, 10, 9, 8, 15,  //
                         14, 13, 12, x, x, x, x, x, x, x, x, x, x, x, x, x});
    Lanes ends[2] = {bytes({0, x, x, x, x, x, x, x, x, 3, 4, x, x, x, x, x,  //
                            x, x, x, 7, x, x, x, x, x, x, x, x, x, x, x, x}),
                     bytes({8, x, x, x, x, x, x, x, x, 11, 12, x, x, x, x, x,  //
                            x, x, x, 15, x, x, x, x, x, x, x, x, x, x, x, x})};
};

inline constexpr Constants kConstants{};

// kConstants through a pointer the compiler cannot see through: the output stores might change
// the table, so each use stays a memory operand instead of a constant rebuilt in a register.
inline const Constants& constants() {
    const Constants* k = &kConstants;
    asm("" : "+r"(k));
    return *k;
}

[[gnu::always_inline]] inline __m256i load(const Lanes& l) {
    return _mm256_load_si256(reinterpret_cast<const __m256i*>(&l));
}

// floor(v / d) for each dword v < 10^9 as (v * magic) >> Shift; odd: v >> 32 per qword. The odd
// lanes shift 32 bits less, which leaves the quotient in the high dword.
template <int Shift>
[[gnu::always_inline]] inline __m256i divide(__m256i v, __m256i odd, const Lanes& magic) {
    return _mm256_blend_epi32(_mm256_srli_epi64(_mm256_mul_epu32(v, load(magic)), Shift),
                              _mm256_srli_epi64(_mm256_mul_epu32(odd, load(magic)), Shift - 32), 0xAA);
}

// Each dword y < 10^4 -> its 4 decimal digits as byte values, least significant first.
[[gnu::always_inline]] inline __m256i digits4(__m256i y, const Constants& k) {
    const __m256i hundreds = _mm256_srli_epi16(_mm256_mulhi_epu16(y, load(k.by100)), 3);
    const __m256i halves = _mm256_add_epi32(y, _mm256_mullo_epi32(hundreds, load(k.hundreds_up)));  // [y % 100, y / 100]
    const __m256i tens = _mm256_mulhi_epu16(halves, load(k.by10));  // each 16-bit half / 10
    return _mm256_add_epi16(halves, _mm256_mullo_epi16(tens, load(k.tens_up)));  // [x % 10, x / 10] bytes
}

// Eight values < 10^9 as 80 bytes at p. Stores 12 bytes past the end.
[[gnu::always_inline]] inline void format8(char* p, __m256i v, const Constants& k) {
    const __m256i odd = _mm256_srli_epi64(v, 32);
    const __m256i q4 = divide<45>(v, odd, k.div4);  // v / 10^4
    const __m256i q8 = divide<56>(v, odd, k.div8);  // v / 10^8
    const __m256i high = _mm256_sub_epi32(q4, _mm256_mullo_epi32(q8, load(k.ten4)));
    const __m256i low = _mm256_sub_epi32(v, _mm256_mullo_epi32(q4, load(k.ten4)));
    // v has n digits: the 9 - n leading positions are blank, '0' - 0x10 = ' '. Blank masks (0x10
    // per byte, the most significant digit in the top byte) shift left by 8 (n - 1) bits for the
    // low dword, 8 (n - 4) for the high one. c = 1 - n from the compares v >= 10^e, e = 1..8.
    const auto at_least = [&](int e) { return _mm256_cmpgt_epi32(v, load(k.max_below[e])); };
    const auto sum = [](__m256i a, __m256i b) { return _mm256_add_epi32(a, b); };
    const __m256i at_least8 = at_least(8);
    const __m256i c = sum(sum(sum(at_least(1), at_least(2)), sum(at_least(3), at_least(4))),
                          sum(sum(at_least(5), at_least(6)), sum(at_least(7), at_least8)));
    const __m256i shift = _mm256_slli_epi32(_mm256_abs_epi32(c), 3);
    const __m256i blank_low = _mm256_sllv_epi32(load(k.blank_low), shift);  // the units always shown
    const __m256i high_shift = _mm256_subs_epu16(shift, load(k.high_offset));  // 0 if n < 4
    const __m256i blank_high = _mm256_sllv_epi32(load(k.blank_high), high_shift);
    const __m256i h = _mm256_sub_epi8(_mm256_add_epi8(digits4(high, k), load(k.zero)), blank_high);
    const __m256i l = _mm256_sub_epi8(_mm256_add_epi8(digits4(low, k), load(k.zero)), blank_low);
    // Lead dwords: the digit of 10^8 (or a space) in byte 0, the separator in byte 3.
    const __m256i lead_digit = _mm256_and_si256(at_least8, load(k.lead_shown));  // ' ' + 0x10 = '0'
    const __m256i lead = _mm256_add_epi32(_mm256_add_epi32(q8, load(k.lead)), lead_digit);
    const __m256i hl01 = _mm256_unpacklo_epi32(h, l);  // [h0 l0 h1 l1 | h4 l4 h5 l5]
    const __m256i hl23 = _mm256_unpackhi_epi32(h, l);  // [h2 l2 h3 l3 | h6 l6 h7 l7]
    // Each lane copied to both lanes.
    const auto low_lane = [](__m256i a) { return _mm256_inserti128_si256(a, _mm256_castsi256_si128(a), 1); };
    const auto high_lane = [](__m256i a) { return _mm256_permute2x128_si256(a, a, 0x11); };
    const __m256i lead_low = low_lane(lead), lead_high = high_lane(lead);
    const auto two_fields = [&](__m256i digits, __m256i leads, int j) {
        return _mm256_or_si256(_mm256_shuffle_epi8(digits, load(k.order)),
                               _mm256_shuffle_epi8(leads, load(k.ends[j])));
    };
    const auto store = [](char* q, __m256i f) { _mm256_storeu_si256(reinterpret_cast<__m256i*>(q), f); };
    store(p, two_fields(low_lane(hl01), lead_low, 0));
    store(p + 20, two_fields(low_lane(hl23), lead_low, 1));
    store(p + 40, two_fields(high_lane(hl01), lead_high, 0));
    store(p + 60, two_fields(high_lane(hl23), lead_high, 1));
}

}  // namespace detail

// values[0, count), count >= 1, as fixed-width fields. They are formatted in blocks of 250 KB,
// longer than the Writer's buffer, so the Writer hands each block to write(2) directly: on a
// 331 MB output 3% faster than 64 KiB writes.
inline void write(io::Writer& out, const std::uint32_t* values, std::size_t count) {
    constexpr std::size_t kBlock = 25600;  // values
    alignas(64) static char text[10 * kBlock + 96];
    const detail::Constants& k = detail::constants();
    for (std::size_t i = 0; i < count; i += kBlock) {
        const std::size_t n = std::min(kBlock, count - i);
        char* p = text;
        std::size_t j = 0;
        for (; j + 8 <= n; j += 8, p += 80)
            detail::format8(p, _mm256_loadu_si256(reinterpret_cast<const __m256i*>(values + i + j)), k);
        if (j < n) {
            alignas(32) std::uint32_t tail[8] = {};
            std::memcpy(tail, values + i + j, (n - j) * sizeof(std::uint32_t));
            detail::format8(p, _mm256_load_si256(reinterpret_cast<const __m256i*>(tail)), k);
            p += 10 * (n - j);
        }
        if (i + n == count) p[-1] = '\n';
        out.write(std::string_view(text, std::size_t(p - text)));
    }
}

}  // namespace fixed_width

namespace {

using Vec = __m256i;

constexpr std::uint32_t kP = 998244353;
constexpr std::uint32_t kBarrett = std::uint32_t((std::uint64_t(1) << 61) / kP);

#ifndef BLOCK_LOG
#define BLOCK_LOG 17  // tests set 6 to get several rows from small inputs
#endif

constexpr int kMinLog = 6;  // shorter inputs are padded with zeros (zero entries add nothing)
constexpr int kBlockLog = BLOCK_LOG;  // row length
constexpr int kMaxRowsLog = 3;        // N <= 20
constexpr int kBandRowsLog = 2;       // 2 MiB per Reader call at N = 20
constexpr int kPieceLog = 12;         // 16 KiB, in L1
constexpr std::size_t kBandSkew = 256;  // 16 cache lines: 4 bands spread over 64 L1 sets

// Offset of row r in an array: rows of a band are contiguous, bands are kBandSkew apart.
constexpr std::size_t row_offset(std::size_t r, std::size_t block) {
    return r * block + (r >> kBandRowsLog) * kBandSkew;
}

inline Vec broadcast(std::uint32_t x) { return _mm256_set1_epi32(int(x)); }

// x + y (zeta) or x - y (mu) mod P, for x, y < P.
template <bool Inverse>
[[gnu::always_inline]] inline Vec step(Vec x, Vec y) {
    if constexpr (Inverse) {
        const Vec d = _mm256_sub_epi32(x, y);
        return _mm256_min_epu32(d, _mm256_add_epi32(d, broadcast(kP)));
    } else {
        const Vec s = _mm256_add_epi32(x, y);
        return _mm256_min_epu32(s, _mm256_sub_epi32(s, broadcast(kP)));
    }
}

// The levels of the K bits of the index into x[0, 2^K).
template <bool Inverse, int K>
[[gnu::always_inline]] inline void butterflies(Vec* x) {
#pragma GCC unroll 8
    for (int bit = 1; bit < (1 << K); bit <<= 1)
#pragma GCC unroll 32
        for (int k = 0; k < (1 << K); ++k)
            if (!(k & bit)) x[k] = step<Inverse>(x[k], x[k | bit]);
}

// x[i] lane j <-> x[j] lane i.
[[gnu::always_inline]] inline void transpose(Vec* x) {
    Vec t[8], u[8];
#pragma GCC unroll 4
    for (int k = 0; k < 8; k += 2) {
        t[k] = _mm256_unpacklo_epi32(x[k], x[k + 1]);
        t[k + 1] = _mm256_unpackhi_epi32(x[k], x[k + 1]);
    }
#pragma GCC unroll 2
    for (int k = 0; k < 8; k += 4) {
        u[k] = _mm256_unpacklo_epi64(t[k], t[k + 2]);
        u[k + 1] = _mm256_unpackhi_epi64(t[k], t[k + 2]);
        u[k + 2] = _mm256_unpacklo_epi64(t[k + 1], t[k + 3]);
        u[k + 3] = _mm256_unpackhi_epi64(t[k + 1], t[k + 3]);
    }
#pragma GCC unroll 4
    for (int k = 0; k < 4; ++k) {
        x[k] = _mm256_permute2x128_si256(u[k], u[k + 4], 0x20);
        x[k + 4] = _mm256_permute2x128_si256(u[k], u[k + 4], 0x31);
    }
}

// Levels of K vector-index bits from stride h (vectors) on f[0, count).
template <bool Inverse, int K>
void sweep(Vec* f, std::size_t count, std::size_t h) {
    for (std::size_t g = 0; g < count; g += h << K)
        for (std::size_t j = g; j < g + h; ++j) {
            Vec x[1 << K];
#pragma GCC unroll 8
            for (int k = 0; k < (1 << K); ++k) x[k] = f[j + k * h];
            butterflies<Inverse, K>(x);
            // x[2^K - 1] has every bit set: no level changes it.
#pragma GCC unroll 8
            for (int k = 0; k + 1 < (1 << K); ++k) f[j + k * h] = x[k];
        }
}

// Levels of the vector-index bits [from, to) on f[0, count).
template <bool Inverse>
void sweeps(Vec* f, std::size_t count, int from, int to) {
    for (; from + 3 <= to; from += 3) sweep<Inverse, 3>(f, count, std::size_t(1) << from);
    if (to - from == 2) sweep<Inverse, 2>(f, count, std::size_t(1) << from);
    if (to - from == 1) sweep<Inverse, 1>(f, count, std::size_t(1) << from);
}

// The lane bits and the 3 vector-index bits above them, tile by tile (8 vectors): the vector bits,
// a transpose, then the former lane bits. The transform leaves each tile transposed; the inverse
// takes transposed tiles and restores them.
template <bool Inverse>
void tiles(Vec* f, std::size_t count) {
    for (std::size_t g = 0; g < count; g += 8) {
        Vec x[8];
#pragma GCC unroll 8
        for (int k = 0; k < 8; ++k) x[k] = f[g + k];
        butterflies<Inverse, 3>(x);
        transpose(x);
        butterflies<Inverse, 3>(x);
#pragma GCC unroll 8
        for (int k = 0; k < 8; ++k) f[g + k] = x[k];
    }
}

// All levels of a row of 2^bits values, bits >= 6: pieces of 2^kPieceLog values (in L1), then the
// row's upper bits. The inverse goes the other way, so each piece ends in natural order.
template <bool Inverse>
void row_levels(std::uint32_t* row, int bits) {
    Vec* f = reinterpret_cast<Vec*>(row);
    const std::size_t count = std::size_t(1) << (bits - 3);
    const int piece_bits = std::min(bits, kPieceLog) - 3;  // vector-index bits
    const std::size_t piece = std::size_t(1) << piece_bits;
    if constexpr (Inverse) sweeps<true>(f, count, piece_bits, bits - 3);
    for (std::size_t p = 0; p < count; p += piece) {
        tiles<Inverse>(f + p, piece);
        sweeps<Inverse>(f + p, piece, 3, piece_bits);
    }
    if constexpr (!Inverse) sweeps<false>(f, count, piece_bits, bits - 3);
}

// x y mod P in [0, P), for x, y < P: Barrett. t = floor(x y / 2^29) < 2^31 and
// q = floor(t floor(2^61 / P) / 2^32) is floor(x y / P) or one less, so x y - q P < 2P < 2^32:
// the low words of x y and q P give it.
[[gnu::always_inline]] inline Vec multiply(Vec x, Vec y) {
    const Vec even = _mm256_mul_epu32(x, y);
    const Vec odd = _mm256_mul_epu32(_mm256_srli_epi64(x, 32), _mm256_srli_epi64(y, 32));
    const Vec q_even = _mm256_mul_epu32(_mm256_srli_epi64(even, 29), broadcast(kBarrett));
    const Vec q_odd = _mm256_mul_epu32(_mm256_srli_epi64(odd, 29), broadcast(kBarrett));
    const Vec q = _mm256_blend_epi32(_mm256_srli_epi64(q_even, 32), q_odd, 0xAA);
    const Vec r = _mm256_sub_epi32(_mm256_mullo_epi32(x, y), _mm256_mullo_epi32(q, broadcast(kP)));
    return _mm256_min_epu32(r, _mm256_sub_epi32(r, broadcast(kP)));
}

// Column by column: the row-bit levels of a and b, the product into a, the inverse row-bit levels.
template <int RowsLog>
void combine(std::uint32_t* a_rows, const std::uint32_t* b_rows, std::size_t block) {
    constexpr int kRows = 1 << RowsLog;
    Vec* a = reinterpret_cast<Vec*>(a_rows);
    const Vec* b = reinterpret_cast<const Vec*>(b_rows);
    std::size_t row[kRows];  // in vectors
    for (int r = 0; r < kRows; ++r) row[r] = row_offset(r, block) / 8;
    for (std::size_t j = 0; j < block / 8; ++j) {
        Vec x[kRows], y[kRows];
#pragma GCC unroll 8
        for (int r = 0; r < kRows; ++r) x[r] = a[row[r] + j], y[r] = b[row[r] + j];
        butterflies<false, RowsLog>(x);
        butterflies<false, RowsLog>(y);
#pragma GCC unroll 8
        for (int r = 0; r < kRows; ++r) x[r] = multiply(x[r], y[r]);
        butterflies<true, RowsLog>(x);
#pragma GCC unroll 8
        for (int r = 0; r < kRows; ++r) a[row[r] + j] = x[r];
    }
}

// Zeroed memory for words values: whole 2 MiB pages (huge where the kernel allows), and a remainder
// under 1 MiB in small pages just below them. At N = 20, 8 MiB + 4 KiB: 4 huge pages and 1 small.
std::uint32_t* allocate(std::size_t words) {
    constexpr std::size_t kHuge = std::size_t(1) << 21, kPage = 4096;
    const std::size_t bytes = words * sizeof(std::uint32_t);
    std::size_t huge = bytes / kHuge * kHuge, small = (bytes - huge + kPage - 1) / kPage * kPage;
    if (small >= kHuge / 2) huge += kHuge, small = 0;
    void* region = ::mmap(nullptr, small + huge + kHuge, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
    if (region == MAP_FAILED) std::abort();
    const std::uintptr_t start = (reinterpret_cast<std::uintptr_t>(region) + small + kHuge - 1) & ~(kHuge - 1);
#ifdef MADV_HUGEPAGE
    ::madvise(reinterpret_cast<void*>(start), huge, MADV_HUGEPAGE);
#endif
    return reinterpret_cast<std::uint32_t*>(start - small);
}

void solve() {
    io::Reader in;
    const int n = int(in.read<std::uint32_t>());
    const std::size_t total = std::size_t(1) << n;
    const int lg = std::max(n, kMinLog), block_log = std::min(lg, kBlockLog), rows_log = lg - block_log;
    const std::size_t block = std::size_t(1) << block_log, rows = std::size_t(1) << rows_log;
    const std::size_t band_rows = std::min(rows, std::size_t(1) << kBandRowsLog), bands = rows / band_rows;
    const std::size_t size = row_offset(rows - 1, block) + block + kBandSkew;  // an array, then a skew
    std::uint32_t* const a = allocate(2 * size);
    std::uint32_t* const b = a + size;
    for (std::uint32_t* f : {a, b})
        for (std::size_t r = 0; r < rows; r += band_rows) {
            in.read(f + row_offset(r, block), std::min(band_rows * block, total));
            for (std::size_t k = r; k < r + band_rows; ++k) row_levels<false>(f + row_offset(k, block), block_log);
        }
    switch (rows_log) {
    case 0: combine<0>(a, b, block); break;
    case 1: combine<1>(a, b, block); break;
    case 2: combine<2>(a, b, block); break;
    default: combine<kMaxRowsLog>(a, b, block); break;
    }
    io::Writer out;
    for (std::size_t r = 0; r < rows; ++r) {
        row_levels<true>(a + row_offset(r, block), block_log);
        fixed_width::write(out, a + row_offset(r, block), std::min(block, total));
    }
}

#ifdef __ELF__
// The program runs from the executable's pre-initializers, before the C++ runtime initializes
// iostreams and locales (unused here), and _exit skips their teardown.
void run_early(int, char**, char**) {
    solve();
    ::_exit(0);
}

[[gnu::used, gnu::section(".preinit_array")]] void (*const preinit)(int, char**, char**) = run_early;
#endif

}  // namespace

int main() { solve(); }  // reached only without .preinit_array support
