#!/usr/bin/env python3
"""Generate the radix-16 butterfly kernel of solution.cpp: four levels of (x, y) -> (x + y, x - y)
on the 16 vectors p[j * step], AVX2 assembly with one spill.

Schedule: butterflies (j, h) pair logical vectors j and j + h at level h = 8, 4, 2, 1. Level 8
takes its second operand from memory, so a pair needs only its two result registers. The pair
(7, 15) and the butterflies that depend on it (3, 7, 11, 15 at level 4; 1, 3, 5, 7, ... at level 2)
come last: until then two registers are free. When the last pair is loaded all 16 are in use,
so vector 0 (which only level 1 still needs) goes to a stack slot. A butterfly writes its sum
to a free register and its difference over the second operand; level 1 stores both.
Count: 64 additions and subtractions, 17 stores, 26 loads.

Addresses: p + j * step from four bases (p, p + 4 step, p + 8 step, p + 12 step) and the index
registers s = step and s3 = 3 step, in bytes.

Usage: gen_radix16.py           print the kernel
       gen_radix16.py --check   simulate it, and exit 1 unless solution.cpp holds it
"""
import random
import re
import sys
from pathlib import Path

SOLUTION = Path(__file__).resolve().parent / 'solution.cpp'
BEGIN = '        // Generated by gen_radix16.py: begin\n'
END = '        // Generated by gen_radix16.py: end\n'


def address(j: int) -> str:
    base = f'%[p{4 * (j // 4)}]'
    return [f'({base})', f'({base}, %[s])', f'({base}, %[s], 2)', f'({base}, %[s3])'][j % 4]


def order() -> list[tuple[int, int]]:
    early = [(j, 8) for j in range(7)] + [(j, 4) for j in (0, 1, 2, 8, 9, 10)] + [(j, 2) for j in (0, 4, 8, 12)]
    late = [(7, 8), (3, 4), (11, 4)] + [(j, 2) for j in (1, 5, 9, 13)]
    return early + late + [(j, 1) for j in range(0, 16, 2)]


def kernel() -> list[str]:
    lines = []
    reg = {}                # logical vector -> register, or None in the slot
    free = list(range(16))
    for j, h in order():
        k = j + h
        if h == 8:
            x, y = free.pop(0), free.pop(0)
            lines += [f'vmovdqa {address(j)}, %%ymm{x}', f'vpsubq {address(k)}, %%ymm{x}, %%ymm{y}',
                      f'vpaddq {address(k)}, %%ymm{x}, %%ymm{x}']
            reg[j], reg[k] = x, y
            continue
        y = reg[k]
        if reg[j] is None:  # vector 0 at level 1
            f = free.pop(0)
            lines += [f'vpaddq %[slot], %%ymm{y}, %%ymm{f}', f'vmovdqa %%ymm{f}, {address(j)}',
                      f'vmovdqa %[slot], %%ymm{f}', f'vpsubq %%ymm{y}, %%ymm{f}, %%ymm{y}',
                      f'vmovdqa %%ymm{y}, {address(k)}']
            free += [f, y]
            continue
        if not free:  # once, after the last pair is loaded: spill vector 0
            lines.append(f'vmovdqa %%ymm{reg[0]}, %[slot]')
            free.append(reg[0])
            reg[0] = None
        x, f = reg[j], free.pop(0)
        lines += [f'vpaddq %%ymm{y}, %%ymm{x}, %%ymm{f}', f'vpsubq %%ymm{y}, %%ymm{x}, %%ymm{y}']
        if h == 1:
            lines += [f'vmovdqa %%ymm{f}, {address(j)}', f'vmovdqa %%ymm{y}, {address(k)}']
            free += [x, f, y]
        else:
            reg[j] = f
            free.append(x)
    return lines


def simulate(lines: list[str], values: list[int]) -> list[int]:
    """Run the kernel on 16 integers."""
    memory, reg, slot = list(values), [0] * 16, [0]

    def index(operand: str) -> int:
        base, step, scale = re.match(r'\(%\[p(\d+)\](?:, %\[(s3?)\](?:, (\d))?)?\)', operand).groups()
        return int(base) + (0 if step is None else 3 if step == 's3' else int(scale or 1))

    def read(operand: str) -> int:
        if operand.startswith('%%ymm'):
            return reg[int(operand[5:])]
        return slot[0] if operand == '%[slot]' else memory[index(operand)]

    for line in lines:
        op, rest = line.split(' ', 1)
        operands = re.split(r',\s*(?![^()]*\))', rest)
        if op == 'vmovdqa':
            value, target = read(operands[0]), operands[1]
            if target.startswith('%%ymm'):
                reg[int(target[5:])] = value
            elif target == '%[slot]':
                slot[0] = value
            else:
                memory[index(target)] = value
        else:  # AT&T: op src2, src1, dst
            src2, src1, target = (read(operands[0]), read(operands[1]), operands[2])
            reg[int(target[5:])] = src1 + src2 if op == 'vpaddq' else src1 - src2
    return memory


def reference(values: list[int]) -> list[int]:
    v = list(values)
    for h in (1, 2, 4, 8):
        for j in range(16):
            if not j & h:
                v[j], v[j + h] = v[j] + v[j + h], v[j] - v[j + h]
    return v


def text() -> str:
    return ''.join(f'        "{line}\\n"\n' for line in kernel())


def main() -> int:
    if sys.argv[1:] == ['--check']:
        rng = random.Random(1)
        for _ in range(1000):
            values = [rng.randrange(-2**50, 2**50) for _ in range(16)]
            if simulate(kernel(), values) != reference(values):
                print('gen_radix16.py: the kernel does not compute the transform')
                return 1
        source = SOLUTION.read_text()
        current = source.split(BEGIN, 1)[1].split(END, 1)[0] if BEGIN in source else None
        if current != text():
            print(f'{SOLUTION.name}: radix-16 kernel differs from gen_radix16.py output')
            return 1
        return 0
    sys.stdout.write(text())
    return 0


if __name__ == '__main__':
    sys.exit(main())
