// c_k = sum of a_i b_j over i xor j = k, mod 998244353, for 2^N terms (N <= 20).
// c = H (H a . H b) / 2^N, H the Walsh-Hadamard transform. The transforms run on signed 64-bit
// lanes: a level at most doubles |x|, so values stay below 2^20 * 1.6 P < 2^51 and no level
// reduces. Design and measurements: notes.md.
//
// Layout: the 2^N values are 2^H rows of 2^L (L = min(N, 12)). A row is 2^(L-2) vectors of four
// int64; rows are S = 2^(L-2) + 2 vectors apart, so the rows of a column fall in different cache
// sets. Within each group of four vectors the forward transform leaves the values transposed
// (vector bits 0-1 <-> lane bits); the inverse transposes back.
//
// Order: a's rows as it is parsed, a's columns, a mod P kept as dwords; then b in the same
// array: rows, columns, the products with a, the inverse columns; the inverse rows, printed in
// chunks. Each int64 array is transformed while it is still in the cache.
#include "lib/io/io.hpp"
#include "../fixed_width.hpp"

#include <sys/mman.h>

#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <cstdlib>

namespace {

using Vec = __m256i;

constexpr std::uint32_t kP = 998244353;
constexpr int kMaxRowLog = 12;
constexpr int kChunkLog = 16;            // values per bulk parse
constexpr std::size_t kStrip = 2;        // vectors per row in a column strip: one cache line

constexpr std::uint32_t power(std::uint64_t x, std::uint64_t e) {
    std::uint64_t r = 1;
    for (; e; e >>= 1, x = x * x % kP)
        if (e & 1) r = r * x % kP;
    return std::uint32_t(r);
}

// P^-1 mod 2^32 by Newton's iteration.
constexpr std::uint32_t kPInverse = [] {
    std::uint32_t x = kP;
    for (int i = 0; i < 5; ++i) x *= 2 - kP * x;
    return x;
}();
static_assert(kP * kPInverse == 1);

Vec broadcast(std::int64_t x) { return _mm256_set1_epi64x(x); }

// Bits levels of butterflies (x, y) -> (x + y, x - y) on v[0, 2^Bits). The empty asm after each
// level keeps GCC from reassociating the sums across levels, which costs extra operations.
template <int Bits>
[[gnu::always_inline]] inline void butterflies(Vec (&v)[1 << Bits]) {
#pragma GCC unroll 4
    for (int level = 0; level < Bits; ++level) {
#pragma GCC unroll 16
        for (int j = 0; j < (1 << Bits); ++j)
            if (const int h = 1 << level; !(j & h)) {
                const Vec x = v[j], y = v[j + h];
                v[j] = _mm256_add_epi64(x, y);
                v[j + h] = _mm256_sub_epi64(x, y);
            }
#pragma GCC unroll 16
        for (int j = 0; j < (1 << Bits); ++j) asm("" : "+x"(v[j]));
    }
}

// The butterflies of 2^Bits vectors p[j * step].
template <int Bits>
[[gnu::always_inline]] inline void pass(Vec* p, std::size_t step) {
    Vec v[1 << Bits];
#pragma GCC unroll 16
    for (int j = 0; j < (1 << Bits); ++j) v[j] = _mm256_load_si256(p + j * step);
    butterflies<Bits>(v);
#pragma GCC unroll 16
    for (int j = 0; j < (1 << Bits); ++j) _mm256_store_si256(p + j * step, v[j]);
}

// pass<4> in assembly, generated by gen_radix16.py: one spill, where GCC spills about ten and
// reassociates the sums.
[[gnu::always_inline]] inline void radix16(Vec* p, std::size_t step) {
    const std::size_t s = step * sizeof(Vec);
    Vec slot;
    asm volatile(
        // Generated by gen_radix16.py: begin
        "vmovdqa (%[p0]), %%ymm0\n"
        "vpsubq (%[p8]), %%ymm0, %%ymm1\n"
        "vpaddq (%[p8]), %%ymm0, %%ymm0\n"
        "vmovdqa (%[p0], %[s]), %%ymm2\n"
        "vpsubq (%[p8], %[s]), %%ymm2, %%ymm3\n"
        "vpaddq (%[p8], %[s]), %%ymm2, %%ymm2\n"
        "vmovdqa (%[p0], %[s], 2), %%ymm4\n"
        "vpsubq (%[p8], %[s], 2), %%ymm4, %%ymm5\n"
        "vpaddq (%[p8], %[s], 2), %%ymm4, %%ymm4\n"
        "vmovdqa (%[p0], %[s3]), %%ymm6\n"
        "vpsubq (%[p8], %[s3]), %%ymm6, %%ymm7\n"
        "vpaddq (%[p8], %[s3]), %%ymm6, %%ymm6\n"
        "vmovdqa (%[p4]), %%ymm8\n"
        "vpsubq (%[p12]), %%ymm8, %%ymm9\n"
        "vpaddq (%[p12]), %%ymm8, %%ymm8\n"
        "vmovdqa (%[p4], %[s]), %%ymm10\n"
        "vpsubq (%[p12], %[s]), %%ymm10, %%ymm11\n"
        "vpaddq (%[p12], %[s]), %%ymm10, %%ymm10\n"
        "vmovdqa (%[p4], %[s], 2), %%ymm12\n"
        "vpsubq (%[p12], %[s], 2), %%ymm12, %%ymm13\n"
        "vpaddq (%[p12], %[s], 2), %%ymm12, %%ymm12\n"
        "vpaddq %%ymm8, %%ymm0, %%ymm14\n"
        "vpsubq %%ymm8, %%ymm0, %%ymm8\n"
        "vpaddq %%ymm10, %%ymm2, %%ymm15\n"
        "vpsubq %%ymm10, %%ymm2, %%ymm10\n"
        "vpaddq %%ymm12, %%ymm4, %%ymm0\n"
        "vpsubq %%ymm12, %%ymm4, %%ymm12\n"
        "vpaddq %%ymm9, %%ymm1, %%ymm2\n"
        "vpsubq %%ymm9, %%ymm1, %%ymm9\n"
        "vpaddq %%ymm11, %%ymm3, %%ymm4\n"
        "vpsubq %%ymm11, %%ymm3, %%ymm11\n"
        "vpaddq %%ymm13, %%ymm5, %%ymm1\n"
        "vpsubq %%ymm13, %%ymm5, %%ymm13\n"
        "vpaddq %%ymm0, %%ymm14, %%ymm3\n"
        "vpsubq %%ymm0, %%ymm14, %%ymm0\n"
        "vpaddq %%ymm12, %%ymm8, %%ymm5\n"
        "vpsubq %%ymm12, %%ymm8, %%ymm12\n"
        "vpaddq %%ymm1, %%ymm2, %%ymm14\n"
        "vpsubq %%ymm1, %%ymm2, %%ymm1\n"
        "vpaddq %%ymm13, %%ymm9, %%ymm8\n"
        "vpsubq %%ymm13, %%ymm9, %%ymm13\n"
        "vmovdqa (%[p4], %[s3]), %%ymm2\n"
        "vpsubq (%[p12], %[s3]), %%ymm2, %%ymm9\n"
        "vpaddq (%[p12], %[s3]), %%ymm2, %%ymm2\n"
        "vmovdqa %%ymm3, %[slot]\n"
        "vpaddq %%ymm2, %%ymm6, %%ymm3\n"
        "vpsubq %%ymm2, %%ymm6, %%ymm2\n"
        "vpaddq %%ymm9, %%ymm7, %%ymm6\n"
        "vpsubq %%ymm9, %%ymm7, %%ymm9\n"
        "vpaddq %%ymm3, %%ymm15, %%ymm7\n"
        "vpsubq %%ymm3, %%ymm15, %%ymm3\n"
        "vpaddq %%ymm2, %%ymm10, %%ymm15\n"
        "vpsubq %%ymm2, %%ymm10, %%ymm2\n"
        "vpaddq %%ymm6, %%ymm4, %%ymm10\n"
        "vpsubq %%ymm6, %%ymm4, %%ymm6\n"
        "vpaddq %%ymm9, %%ymm11, %%ymm4\n"
        "vpsubq %%ymm9, %%ymm11, %%ymm9\n"
        "vpaddq %[slot], %%ymm7, %%ymm11\n"
        "vmovdqa %%ymm11, (%[p0])\n"
        "vmovdqa %[slot], %%ymm11\n"
        "vpsubq %%ymm7, %%ymm11, %%ymm7\n"
        "vmovdqa %%ymm7, (%[p0], %[s])\n"
        "vpaddq %%ymm3, %%ymm0, %%ymm11\n"
        "vpsubq %%ymm3, %%ymm0, %%ymm3\n"
        "vmovdqa %%ymm11, (%[p0], %[s], 2)\n"
        "vmovdqa %%ymm3, (%[p0], %[s3])\n"
        "vpaddq %%ymm15, %%ymm5, %%ymm7\n"
        "vpsubq %%ymm15, %%ymm5, %%ymm15\n"
        "vmovdqa %%ymm7, (%[p4])\n"
        "vmovdqa %%ymm15, (%[p4], %[s])\n"
        "vpaddq %%ymm2, %%ymm12, %%ymm0\n"
        "vpsubq %%ymm2, %%ymm12, %%ymm2\n"
        "vmovdqa %%ymm0, (%[p4], %[s], 2)\n"
        "vmovdqa %%ymm2, (%[p4], %[s3])\n"
        "vpaddq %%ymm10, %%ymm14, %%ymm11\n"
        "vpsubq %%ymm10, %%ymm14, %%ymm10\n"
        "vmovdqa %%ymm11, (%[p8])\n"
        "vmovdqa %%ymm10, (%[p8], %[s])\n"
        "vpaddq %%ymm6, %%ymm1, %%ymm3\n"
        "vpsubq %%ymm6, %%ymm1, %%ymm6\n"
        "vmovdqa %%ymm3, (%[p8], %[s], 2)\n"
        "vmovdqa %%ymm6, (%[p8], %[s3])\n"
        "vpaddq %%ymm4, %%ymm8, %%ymm5\n"
        "vpsubq %%ymm4, %%ymm8, %%ymm4\n"
        "vmovdqa %%ymm5, (%[p12])\n"
        "vmovdqa %%ymm4, (%[p12], %[s])\n"
        "vpaddq %%ymm9, %%ymm13, %%ymm7\n"
        "vpsubq %%ymm9, %%ymm13, %%ymm9\n"
        "vmovdqa %%ymm7, (%[p12], %[s], 2)\n"
        "vmovdqa %%ymm9, (%[p12], %[s3])\n"
        // Generated by gen_radix16.py: end
        : [slot] "=m"(slot)
        : [p0] "r"(p), [p4] "r"(p + 4 * step), [p8] "r"(p + 8 * step), [p12] "r"(p + 12 * step), [s] "r"(s),
          [s3] "r"(3 * s)
        : "memory", "xmm0", "xmm1", "xmm2", "xmm3", "xmm4", "xmm5", "xmm6", "xmm7", "xmm8", "xmm9", "xmm10", "xmm11", "xmm12", "xmm13", "xmm14", "xmm15");
}

// Levels for row bits [lo, lo + Bits) of 2^rows_log rows of width vectors, stride vectors apart.
template <int Bits>
void levels(Vec* base, int lo, int rows_log, std::size_t stride, std::size_t width) {
    const std::size_t span = std::size_t(1) << lo, block = span << Bits, rows = std::size_t(1) << rows_log;
    for (std::size_t r0 = 0; r0 < rows; r0 += block)
        for (std::size_t r = r0; r < r0 + span; ++r)
            for (std::size_t c = 0; c < width; ++c) {
                if constexpr (Bits == 4) radix16(base + r * stride + c, span * stride);
                else pass<Bits>(base + r * stride + c, span * stride);
            }
}

// Levels for row bits [lo, hi), four at a time.
void transform(Vec* base, int lo, int hi, int rows_log, std::size_t stride, std::size_t width) {
    for (; hi - lo >= 4; lo += 4) levels<4>(base, lo, rows_log, stride, width);
    switch (hi - lo) {
        case 3: levels<3>(base, lo, rows_log, stride, width); break;
        case 2: levels<2>(base, lo, rows_log, stride, width); break;
        case 1: levels<1>(base, lo, rows_log, stride, width); break;
        default: break;
    }
}

// 4x4 transpose of 64-bit lanes: v[i] lane j <-> v[j] lane i.
[[gnu::always_inline]] inline void transpose(Vec (&v)[4]) {
    const Vec t0 = _mm256_unpacklo_epi64(v[0], v[1]), t1 = _mm256_unpackhi_epi64(v[0], v[1]);
    const Vec t2 = _mm256_unpacklo_epi64(v[2], v[3]), t3 = _mm256_unpackhi_epi64(v[2], v[3]);
    v[0] = _mm256_permute2x128_si256(t0, t2, 0x20);
    v[1] = _mm256_permute2x128_si256(t1, t3, 0x20);
    v[2] = _mm256_permute2x128_si256(t0, t2, 0x31);
    v[3] = _mm256_permute2x128_si256(t1, t3, 0x31);
}

// x mod P for |x| < 2^51: r = x - q P with |x / P - q| < 0.9, so |r| < 0.9 P. The bits of
// x + kMagicBits are the double M + x (M = 1.5 * 2^52), and fma(M + x, 1/P, M - M/P) =
// M + x/P + e rounds to M + q in the low mantissa bits; e (the rounding of M - M/P) is below 0.4.
constexpr std::int64_t kMagicBits = 0x4338000000000000;
constexpr double kMagic = 0x1.8p52;
constexpr double kInverseP = 1.0 / kP;
constexpr double kRoundingOffset = kMagic - kMagic * kInverseP;
constexpr long double kOffsetError = (kRoundingOffset - kMagic) + (long double)kMagic * kInverseP;  // exact
static_assert(kOffsetError > -0.4L && kOffsetError < 0.4L);

// The arithmetic below runs stage by stage over K vectors, so that their dependency chains overlap.
template <int K>
[[gnu::always_inline]] inline void reduce(Vec (&x)[K]) {
    Vec q[K];
#pragma GCC unroll 8
    for (int k = 0; k < K; ++k) q[k] = _mm256_add_epi64(x[k], broadcast(kMagicBits));
#pragma GCC unroll 8
    for (int k = 0; k < K; ++k)
        q[k] = _mm256_castpd_si256(_mm256_fmadd_pd(_mm256_castsi256_pd(q[k]), _mm256_set1_pd(kInverseP),
                                                   _mm256_set1_pd(kRoundingOffset)));
#pragma GCC unroll 8
    for (int k = 0; k < K; ++k) q[k] = _mm256_sub_epi64(q[k], broadcast(kMagicBits));
#pragma GCC unroll 8
    for (int k = 0; k < K; ++k) x[k] = _mm256_sub_epi64(x[k], _mm256_mul_epi32(q[k], broadcast(kP)));
}

// t / 2^32 mod P (Montgomery) for |t| < 2^62: a signed low dword below |t| / 2^32 + P / 2 in
// magnitude; the high dword is zero.
template <int K>
[[gnu::always_inline]] inline void redc(Vec (&t)[K]) {
    Vec m[K];
#pragma GCC unroll 8
    for (int k = 0; k < K; ++k) m[k] = _mm256_mul_epu32(t[k], broadcast(kPInverse));  // low dword: t / P mod 2^32
#pragma GCC unroll 8
    for (int k = 0; k < K; ++k) m[k] = _mm256_mul_epi32(m[k], broadcast(kP));
#pragma GCC unroll 8
    for (int k = 0; k < K; ++k) t[k] = _mm256_srli_epi64(_mm256_sub_epi64(t[k], m[k]), 32);
}

// y = x y / 2^N mod P for reduced x (signed low dwords, |x| < 0.9 P) and transformed y
// (|y| < 2^51), as values in (0, 1.6 P); scale holds 2^(64 - N) mod P, centered. Bounds: reduced
// |y| < 0.9 P; redc(x y) = u, |u| < 0.2 P + P / 2; redc(u scale) below 0.1 P + P / 2; then + P.
template <int K>
[[gnu::always_inline]] inline void multiply(const Vec (&x)[K], Vec (&y)[K], Vec scale) {
    reduce(y);
#pragma GCC unroll 8
    for (int k = 0; k < K; ++k) y[k] = _mm256_mul_epi32(x[k], y[k]);
    redc(y);
#pragma GCC unroll 8
    for (int k = 0; k < K; ++k) y[k] = _mm256_mul_epi32(y[k], scale);
    redc(y);
#pragma GCC unroll 8
    for (int k = 0; k < K; ++k)
        y[k] = _mm256_add_epi32(y[k], _mm256_setr_epi32(int(kP), 0, int(kP), 0, int(kP), 0, int(kP), 0));
}

// The low dwords of r0 and r1, in order.
[[gnu::always_inline]] inline Vec pack(Vec r0, Vec r1) {
    const Vec low = _mm256_castps_si256(
        _mm256_shuffle_ps(_mm256_castsi256_ps(r0), _mm256_castsi256_ps(r1), 0x88));  // r0 01 r1 01 | r0 23 r1 23
    return _mm256_permute4x64_epi64(low, 0xD8);
}

// Dwords in (-P, P) -> their residues in [0, P).
[[gnu::always_inline]] inline Vec canonical(Vec v) {
    return _mm256_min_epu32(v, _mm256_add_epi32(v, _mm256_set1_epi32(int(kP))));
}

// One row of 2^L input values < P -> its row of vectors, low L bits transformed, transposed in
// groups of four.
void forward_row(const std::uint32_t* src, Vec* row, int row_log) {
    const std::size_t vectors = std::size_t(1) << (row_log - 2);
    for (std::size_t i = 0; i < vectors; i += 4) {
        Vec v[4];
#pragma GCC unroll 4
        for (int t = 0; t < 4; ++t)
            v[t] = _mm256_cvtepu32_epi64(_mm_load_si128(reinterpret_cast<const __m128i*>(src + 4 * (i + t))));
        butterflies<2>(v);  // value bits 2, 3
        transpose(v);
        butterflies<2>(v);  // value bits 0, 1
#pragma GCC unroll 4
        for (int t = 0; t < 4; ++t) _mm256_store_si256(row + i + t, v[t]);
    }
    transform(row, 2, row_log - 2, row_log - 2, 1, 1);
}

// Inverse of forward_row, then the residues in [0, P) of the 2^L values.
void inverse_row(Vec* row, std::uint32_t* dst, int row_log) {
    transform(row, 2, row_log - 2, row_log - 2, 1, 1);
    const std::size_t vectors = std::size_t(1) << (row_log - 2);
    for (std::size_t i = 0; i < vectors; i += 4) {
        Vec v[4];
#pragma GCC unroll 4
        for (int t = 0; t < 4; ++t) v[t] = _mm256_load_si256(row + i + t);
        butterflies<2>(v);
        transpose(v);
        butterflies<2>(v);
        reduce(v);
        auto* out = reinterpret_cast<Vec*>(dst + 4 * i);
        _mm256_store_si256(out, canonical(pack(v[0], v[1])));
        _mm256_store_si256(out + 1, canonical(pack(v[2], v[3])));
    }
}

// The column pass works on strips of two vectors (one cache line) per row; a holds such a strip
// reduced to eight dwords per row.
static_assert(kStrip == 2);

// x mod P (|r| < 0.9 P) for one strip, Rows rows at a time, as signed dwords into a; a's rows
// are stride_a vectors apart. Prefetches the next strip.
template <int Rows>
void reduce_strip(const Vec* x, Vec* a, std::size_t rows, std::size_t stride, std::size_t stride_a, bool last) {
    for (std::size_t r = 0; r < rows; r += Rows, x += Rows * stride, a += Rows * stride_a) {
        Vec v[2 * Rows];
#pragma GCC unroll 4
        for (int i = 0; i < Rows; ++i) {
            v[2 * i] = x[i * stride];
            v[2 * i + 1] = x[i * stride + 1];
            if (!last) _mm_prefetch(reinterpret_cast<const char*>(x + i * stride + kStrip), _MM_HINT_T0);
        }
        reduce(v);
#pragma GCC unroll 4
        for (int i = 0; i < Rows; ++i) a[i * stride_a] = pack(v[2 * i], v[2 * i + 1]);
    }
}

// The high H bits of x's transform; then x mod P, as signed dwords, into a.
void forward_columns(Vec* x, Vec* a, int rows_log, std::size_t row_vectors, std::size_t stride, std::size_t stride_a) {
    const std::size_t rows = std::size_t(1) << rows_log;
    for (std::size_t c = 0; c < row_vectors; c += kStrip) {
        transform(x + c, 0, rows_log, rows_log, stride, kStrip);
        const bool last = c + kStrip == row_vectors;
        if (rows >= 2) reduce_strip<2>(x + c, a + c / kStrip, rows, stride, stride_a, last);
        else reduce_strip<1>(x + c, a + c / kStrip, rows, stride, stride_a, last);
    }
}

// y = multiply(a, y) for one strip, Rows rows at a time. Prefetches the next strip.
template <int Rows>
void multiply_strip(Vec* y, const Vec* a, std::size_t rows, std::size_t stride, std::size_t stride_a, Vec scale,
                    bool last) {
    for (std::size_t r = 0; r < rows; r += Rows, y += Rows * stride, a += Rows * stride_a) {
        Vec x[2 * Rows], v[2 * Rows];
#pragma GCC unroll 4
        for (int i = 0; i < Rows; ++i) {
            const auto* dwords = reinterpret_cast<const __m128i*>(a + i * stride_a);
            x[2 * i] = _mm256_cvtepu32_epi64(_mm_load_si128(dwords));
            x[2 * i + 1] = _mm256_cvtepu32_epi64(_mm_load_si128(dwords + 1));
            v[2 * i] = y[i * stride];
            v[2 * i + 1] = y[i * stride + 1];
            if (!last) {
                _mm_prefetch(reinterpret_cast<const char*>(y + i * stride + kStrip), _MM_HINT_T0);
                _mm_prefetch(reinterpret_cast<const char*>(a + i * stride_a + 1), _MM_HINT_T0);
            }
        }
        multiply(x, v, scale);
#pragma GCC unroll 4
        for (int i = 0; i < Rows; ++i) {
            y[i * stride] = v[2 * i];
            y[i * stride + 1] = v[2 * i + 1];
        }
    }
}

// The high H bits of y's transform, the products with a over 2^N, and the inverse transform of
// the high bits, into y.
void columns(Vec* y, const Vec* a, int rows_log, std::size_t row_vectors, std::size_t stride, std::size_t stride_a,
             Vec scale) {
    const std::size_t rows = std::size_t(1) << rows_log;
    for (std::size_t c = 0; c < row_vectors; c += kStrip) {
        transform(y + c, 0, rows_log, rows_log, stride, kStrip);
        const bool last = c + kStrip == row_vectors;
        if (rows >= 2) multiply_strip<2>(y + c, a + c / kStrip, rows, stride, stride_a, scale, last);
        else multiply_strip<1>(y + c, a + c / kStrip, rows, stride, stride_a, scale, last);
        transform(y + c, 0, rows_log, rows_log, stride, kStrip);
    }
}

// count vectors in 2 MiB pages where the kernel allows.
Vec* allocate(std::size_t count) {
    constexpr std::size_t kHuge = std::size_t(1) << 21;
    const std::size_t bytes = count * sizeof(Vec) + kHuge;
    void* region = ::mmap(nullptr, bytes, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
    if (region == MAP_FAILED) std::abort();
    const std::uintptr_t start = (reinterpret_cast<std::uintptr_t>(region) + kHuge - 1) & ~(kHuge - 1);
#ifdef MADV_HUGEPAGE
    ::madvise(reinterpret_cast<void*>(start), bytes - kHuge, MADV_HUGEPAGE);
#endif
    return reinterpret_cast<Vec*>(start);
}

// N < 4: the definition.
void solve_small(io::Reader& in, io::Writer& out, int n_log) {
    const std::size_t n = std::size_t(1) << n_log;
    std::uint64_t a[8], b[8], c[8] = {};
    for (std::size_t i = 0; i < n; ++i) a[i] = in.read<std::uint32_t>();
    for (std::size_t i = 0; i < n; ++i) b[i] = in.read<std::uint32_t>();
    for (std::size_t i = 0; i < n; ++i)
        for (std::size_t j = 0; j < n; ++j) c[i ^ j] = (c[i ^ j] + a[i] * b[j]) % kP;
    for (std::size_t i = 0; i < n; ++i) out.write(c[i], i + 1 < n ? ' ' : '\n');
}

}  // namespace

int main() {
    io::Reader in;
    io::Writer out;
    const int n_log = int(in.read<std::uint32_t>());
    if (n_log < 4) {
        solve_small(in, out, n_log);
        out.flush();
        std::_Exit(0);
    }
    const int row_log = std::min(n_log, kMaxRowLog), rows_log = n_log - row_log;
    const std::size_t row_vectors = std::size_t(1) << (row_log - 2), stride = row_vectors + 2;
    const std::size_t stride_a = row_vectors / 2 + 2;
    const std::size_t rows = std::size_t(1) << rows_log, row_values = std::size_t(1) << row_log;
    const std::size_t chunk = std::size_t(1) << std::min(n_log, kChunkLog), chunk_rows = chunk / row_values;
    // x: one factor during its transform (int64); a: the transformed a, reduced (dwords);
    // values: a chunk of input or output values.
    Vec* const x = allocate(rows * stride + rows * stride_a + chunk / 8);
    Vec* const a = x + rows * stride;
    auto* const values = reinterpret_cast<std::uint32_t*>(a + rows * stride_a);

    const auto forward_rows = [&] {
        for (std::size_t r = 0; r < rows; r += chunk_rows) {
            in.read(values, chunk);
            for (std::size_t i = 0; i < chunk_rows; ++i)
                forward_row(values + i * row_values, x + (r + i) * stride, row_log);
        }
    };
    forward_rows();
    forward_columns(x, a, rows_log, row_vectors, stride, stride_a);
    forward_rows();
    // Two Montgomery reductions divide by 2^64: scale = 2^(64 - N), centered.
    const std::uint32_t scale = power(2, 64 - n_log);
    columns(x, a, rows_log, row_vectors, stride, stride_a,
            broadcast(scale > kP / 2 ? std::int64_t(scale) - kP : scale));

    // Each chunk ends with a newline: the checker compares tokens.
    for (std::size_t r = 0; r < rows; r += chunk_rows) {
        for (std::size_t i = 0; i < chunk_rows; ++i) inverse_row(x + (r + i) * stride, values + i * row_values, row_log);
        fixed_width::write(out, values, chunk);
    }
    out.flush();
    std::_Exit(0);
}
