#!/usr/bin/env python3
"""Bundle a solution and the lib/ headers it includes into one submittable file.

  bundle.py SOURCE [OUT]   inline every #include "..." of SOURCE (default OUT: main.cpp next to it)
  bundle.py --check        every problems/*/*/solution.cpp must bundle to its main.cpp
  bundle.py --all          regenerate every main.cpp that has a solution.cpp

Quoted includes resolve against the including file's directory, then the repository root.
Each header is inlined once; '#pragma once' lines are dropped. System includes stay as they are.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INCLUDE = re.compile(r'\s*#\s*include\s*"([^"]+)"')


def resolve(name: str, including: Path) -> Path:
    for base in (including.parent, ROOT):
        if (base / name).is_file():
            return (base / name).resolve()
    sys.exit(f'{including}: cannot find "{name}"')


def inline(path: Path, seen: set[Path]) -> list[str]:
    lines = []
    for line in path.read_text().splitlines():
        match = INCLUDE.match(line)
        if match:
            header = resolve(match.group(1), path)
            if header not in seen:
                seen.add(header)
                lines += [f'// {name(header)}'] + inline(header, seen)
        elif line.strip() != '#pragma once':
            lines.append(line)
    return lines


def name(path: Path) -> Path:
    return path.relative_to(ROOT) if path.is_relative_to(ROOT) else path


def bundle(source: Path) -> str:
    source = source.resolve()
    header = f'// Generated by tools/bundle.py from {name(source)}. Edit that file instead.'
    return '\n'.join([header] + inline(source, {source})) + '\n'


def solutions() -> list[Path]:
    return sorted(ROOT.glob('problems/*/*/solution.cpp'))


def main() -> int:
    args = sys.argv[1:]
    if args == ['--check']:
        stale = [s for s in solutions() if (s.parent / 'main.cpp').read_text() != bundle(s)]
        for s in stale:
            print(f'{s.parent.relative_to(ROOT)}/main.cpp is stale: run tools/bundle.py --all')
        return 1 if stale else 0
    if args == ['--all']:
        for s in solutions():
            (s.parent / 'main.cpp').write_text(bundle(s))
        return 0
    if len(args) in (1, 2) and not args[0].startswith('-'):
        source = Path(args[0])
        out = Path(args[1]) if len(args) == 2 else source.parent / 'main.cpp'
        out.write_text(bundle(source))
        return 0
    sys.exit(__doc__)


if __name__ == '__main__':
    sys.exit(main())
