#!/usr/bin/env python3
"""Generate kernels.hpp, the asm kernels of product.hpp:

- ntt::Product's kernels (lib/ntt/gen_product_kernels.py) with lib/multimod's modulus: P, 2P and
  -1/P mod 2^32 are lib/multimod's variables, set before each prime. The instructions are the same.
- forward_radix8_wide: lib/multimod's forward_radix8 on Wide (64-bit) input, one column per
  iteration, list-scheduled with lib/ntt/gen_kernels.py (same arithmetic, same output).

Usage: gen_kernels.py [--check]   (--check: exit 1 if kernels.hpp differs from the output)
"""
import argparse
import importlib.util
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
OUT = HERE / 'kernels.hpp'

REPLACEMENTS = [
    ('// Generated by gen_product_kernels.py. Do not edit.',
     f'// Generated by {HERE.relative_to(ROOT)}/gen_kernels.py, partly from\n'
     '// lib/ntt/gen_product_kernels.py. Do not edit.'),
    ('// Kernels of ntt::Product (product.hpp). The bottom stage runs two radix-4 groups with h = 1 per\n'
     '// statement (kernels.hpp runs one). A batch of four vectors is a group; each output vector v_t is a\n'
     '// leaf, a polynomial mod x^8 - w_t with w_t = y, -y, z, -z from the group\'s twiddles y = r[2k],\n'
     '// z = r[2k + 1]. buf, cur: leaf buffers, 384 bytes per batch, 64-byte aligned. x, y, ix, iy:\n'
     '// twiddles of the first batch, whose group index is even.',
     '// Kernels of product.hpp. First ntt::Product\'s (lib/ntt/product.hpp) modulo lib/multimod\'s prime,\n'
     '// set at run time. The bottom stage runs two radix-4 groups with h = 1 per statement. A batch of\n'
     '// four vectors is a group; each output vector v_t is a leaf, a polynomial mod x^8 - w_t with\n'
     '// w_t = y, -y, z, -z from the group\'s twiddles y = r[2k], z = r[2k + 1]. buf, cur: leaf buffers,\n'
     '// 384 bytes per batch, 64-byte aligned. x, y, ix, iy: twiddles of the first batch, whose group\n'
     '// index is even.'),
    ('#include "lib/ntt/kernels.hpp"', '#include "lib/multimod/kernels.hpp"'),
    ('namespace ntt::product_kernels', 'namespace wide::kernels'),
    ('using kernels::', 'using multimod::kernels::'),
]


def load(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


sys.path.insert(0, str(ROOT / 'lib/ntt'))
gk = load('gen_kernels', ROOT / 'lib/ntt/gen_kernels.py')
gpk = load('gen_product_kernels', ROOT / 'lib/ntt/gen_product_kernels.py')

# Zen 3: shuffles share the two shift pipes (vpermq modeled at 4 cycles).
LATENCY = dict(gk.LATENCY, vshufps=1, vpermq=4)
PIPE = dict(gk.PIPE, vshufps='shift', vpermq='shift')

# Broadcast constants of forward_radix8_wide, in this order in w: 4P, then R = 2^32 mod P and the
# twiddles i, y, z, each followed by its Shoup quotient.
CONSTANTS = ['4P', 'WR', 'QR', 'WI', 'QI', 'WY', 'QY', 'WZ', 'QZ']


def address(mem):
    """gen_kernels.address, with the input quarters (base x) at stride hx = 64q bytes."""
    base, index, disp = mem
    if index is None or base != 'x':
        return gk.address(mem)
    pattern = ['({b})', '({b},%[hx])', '({b},%[hx],2)', '({b},%[hx3])'][index]
    return (str(disp) if disp else '') + pattern.format(b=f'%[{base}]')


def emit(o, reg):
    """gen_kernels.emit with the x addresses above and one-source vpermq."""
    operand = lambda v: (address(v.mem) if v.kind == 'mem' else gk.operand(v, reg))
    if o.store is not None:
        return f'vmovdqa {operand(o.srcs[0])}, {gk.address(o.store)}'
    dst = f'%%ymm{reg[o.dst]}'
    if o.mnemonic in gk.LOADS:
        return f'{o.mnemonic} {operand(o.srcs[0])}, {dst}'
    if o.mnemonic in ('vpsrlq', 'vpermq'):
        return f'{o.mnemonic} ${o.imm}, {operand(o.srcs[0])}, {dst}'
    x, y = o.srcs  # dst = x OP y is "op y, x, dst"; only y may be in memory
    if o.mnemonic in gk.COMMUTATIVE and x.in_memory:
        x, y = y, x
    imm = f'${o.imm}, ' if o.imm is not None else ''
    return f'{o.mnemonic} {imm}{operand(y)}, {operand(x)}, {dst}'


def narrow(g, t):
    """Words [8j, 8j + 8) of quarter t: hi 2^32 + lo -> canonical hi R + lo mod P, lanes in order."""
    c = g.c
    v0, v1 = g.materialize(g.quarter(t)), g.quarter(t, 32)
    lo = g.op('vshufps', v0, v1, imm=0x88)  # dwords of words [0 1 4 5 | 2 3 6 7]
    hi = g.op('vshufps', v0, v1, imm=0xDD)
    low = g.low(g.op('vpminud', lo, g.op('vpsubd', lo, c['4P'])))  # lo < 8P -> < 2P
    s = g.canonical(g.add(g.shoup(hi, c['WR'], c['QR']), low))
    r = gk.Value('reg')
    g.ops.append(gk.Op('vpermq', r, [s], imm=0xD8))
    return r


def radix8_column(g):
    """lib/multimod's forward_radix8 for one column: inputs canonical, outputs < 4P."""
    c = g.c
    f0, f1, f2, f3 = (narrow(g, t) for t in range(4))
    diff_p = lambda x, y: g.op('vpsubd', g.op('vpaddd', x, c['P']), y)  # x - y + P
    g0, g1 = g.add(f0, f2), g.add(f1, f3)
    h0, ih1 = diff_p(f0, f2), g.shoup(diff_p(f1, f3), c['WI'], c['QI'])
    outs = [g.add(g0, g1), g.diff(g0, g1), g.add(h0, ih1), g.diff(h0, ih1)]
    if2, if3 = g.shoup(f2, c['WI'], c['QI']), g.shoup(f3, c['WI'], c['QI'])
    u0, v0 = g.low(g.add(f0, if2)), g.low(g.diff(f0, if2))
    yu1 = g.shoup(g.add(f1, if3), c['WY'], c['QY'])
    zv1 = g.shoup(g.diff(f1, if3), c['WZ'], c['QZ'])
    outs += [g.add(u0, yu1), g.diff(u0, yu1), g.add(v0, zv1), g.diff(v0, zv1)]
    for k, v in enumerate(outs):
        g.store(v, 'a' if k < 4 else 'b', k % 4, 0)


def radix8_body():
    consts = {'P': gk.Value('creg', reg=15), '2P': gk.Value('creg', reg=14)}
    consts.update({name: gk.Value('cmem', mem=32 * i) for i, name in enumerate(CONSTANTS)})
    g = gk.Graph(consts, array='x')
    radix8_column(g)
    saved = gk.LATENCY, gk.PIPE
    gk.LATENCY, gk.PIPE = LATENCY, PIPE
    try:
        seq = gk.schedule(g.ops, 14, gk.Knobs())
    finally:
        gk.LATENCY, gk.PIPE = saved
    reg = gk.allocate(seq, {14, 15})
    head = ['vpbroadcastd %[P], %%ymm15', 'vpbroadcastd %[P2], %%ymm14', '.p2align 5', '1:']
    tail = ['add $64, %[x]', 'add $32, %[a]', 'add $32, %[b]', 'cmp %[end], %[a]', 'jne 1b']
    return head + [emit(o, reg) for o in seq] + tail


RADIX8_DOC = '''\
// First level of a factor of 64q words whose upper half is zero, from 64-bit words: lib/multimod's
// forward_radix8 on Wide input (same output). Reads x[0, 32q), each word reduced as
// hi (2^32 mod P) + lo; writes the first radix-4 group of both halves, f[0, 8q), values < 4P.
// x and f 32-byte aligned, q >= 1. w: broadcast 4P, then 2^32 mod P and the twiddles r[1], r[2],
// r[3], each followed by its Shoup quotient.
inline void forward_radix8_wide(Vec* f, std::size_t q, const std::uint64_t* x, const Vec* w) {
    Vec* b = f + 4 * q;
    Vec* const end = f + q;
    asm volatile('''


def radix8_function():
    lines = RADIX8_DOC.split('\n')
    lines += gk.asm_lines(radix8_body())
    lines += ['        : [a] "+r"(f), [b] "+r"(b), [x] "+r"(x)',
              '        : [end] "r"(end), [h] "r"(32 * q), [h3] "r"(96 * q), [hx] "r"(64 * q), [hx3] "r"(192 * q),',
              '          [w] "r"(w), [P] "m"(kP), [P2] "m"(k2P)',
              '        : ' + gk.CLOBBERS + ', "cc");', '}']
    return lines


def generate() -> str:
    text = gpk.generate()
    for old, new in REPLACEMENTS:
        if old not in text:
            sys.exit(f'lib/ntt/gen_product_kernels.py output changed: missing {old!r}')
        text = text.replace(old, new)
    close = '}  // namespace wide::kernels\n'
    return text[:-len(close)] + '\n'.join(radix8_function()) + '\n\n' + close


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    text = generate()
    if args.check:
        if not OUT.exists() or OUT.read_text() != text:
            print(f'{OUT} is stale: run {Path(__file__).name}')
            return 1
        return 0
    OUT.write_text(text)
    return 0


if __name__ == '__main__':
    sys.exit(main())
